#%RAML 1.0
title: Example API
types:
  lat-long:
    properties:
      lat:
        type: number
      long:
        type: number
  loc:
    properties:
      location:
        type: nil
  paging:
    properties:
      start:
        type: number
      page-size:
        type: number
securitySchemes:
  oauth_2_0:
    type: OAuth 2.0
    describedBy:
      queryString:
        type:
          - paging
          - lat-long | loc