#%RAML 1.0
types:
  A:
title: test
/test:
  get:
    responses:
      "200":
        body:
          application/json:
            properties:
              a:
/test/{pathParam}:
  get:
    body:
      application/json:
        properties:
          property:
    queryParameters:
      queryParam:
    responses:
      "200":
        headers:
          header:
        body:
          application/json:
            type: any
