#%RAML 1.0
title: test
version: 1
baseUri: https://api.domain.com/{version}
securitySchemes:
    invalid:
        type: OAuth 2.0
        settings:
          authorizationGrants: [ password ]

    valid:
        type: OAuth 2.0
        settings:
          accessTokenUri: https://www.domain.com/1/oauth2/token
          authorizationGrants: [ password ]
