#%RAML 1.0
title: My API With Types
types:
  Dog:
    properties:
      bite:
        type: string
    type: object
  Cat:
    properties:
      claw:
        type: string
    type: object
  Parrot:
    properties:
      feathers:
        type: string
        maxLength: 5
    type: object
  HasHome:
    properties:
      livesInside:
        type: boolean
    type: object
  IsOnFarm:
    properties:
      livesOutside:
        type: boolean
    type: object
  HomeAnimal:
    type:
      - HasHome | IsOnFarm
      - Dog | Cat | Parrot
    properties:
      discriminator:
        type: string
    example:
      discriminator: HasHome Parrot
      livesInside: a
      feathers: colourful
/send:
  post:
    body:
      application/json:
        type: HomeAnimal
