#%RAML 1.0 ResourceType
  description: <<collectionSummary>>
  get:
    description: <<collectionDescription>>
    is: [ 200-collection: {collectionType: <<collectionType>>, collectionExample: <<collectionExample>>}, 
        304-fault,400-fault,401-fault,403-fault,404-fault,405-fault,406-fault,407-fault,415-fault,422-fault,429-fault,500-fault,503-fault,504-fault ]
        
  post:
    description: <<collectionDescription>>
    body:
      type: <<collectionType>>
      example: <<postExample>>
    is: [ 201-item: {itemType: <<collectionType>>, itemExample: <<postExample>>}, 202-item: {itemType: <<collectionType>>, itemExample: <<postExample>>},
        400-fault,401-fault,403-fault,404-fault,405-fault,406-fault,407-fault,415-fault,422-fault,429-fault,500-fault,503-fault,504-fault ]        

  put:
    description: <<collectionDescription>>
    body:
      type: <<collectionType>>
      example: <<postExample>>
    is: [ 204-response,
        400-fault,401-fault,403-fault,404-fault,405-fault,406-fault,407-fault,415-fault,422-fault,429-fault,500-fault,503-fault,504-fault ]        

  patch:
    description: <<collectionDescription>>
    body:
      type: <<collectionType>>
      example: <<postExample>>
    is: [ 204-response,
        400-fault,401-fault,403-fault,404-fault,405-fault,406-fault,407-fault,415-fault,422-fault,429-fault,500-fault,503-fault,504-fault ]        
  
  delete:
    description: <<collectionDescription>>
    body:
      type: <<collectionType>>
      example: <<postExample>>
    is: [ 200-item: {itemType: <<collectionType>>, itemExample: <<postExample>>}, 204-response,
        400-fault,401-fault,403-fault,404-fault,405-fault,406-fault,407-fault,415-fault,422-fault,429-fault,500-fault,503-fault,504-fault ]                