#%RAML 1.0
title: API
version: v2
protocols:
  - https
baseUri: app.com/api
/location:
  get:
    queryString:
      examples:
        first:
          content:
            lat: 12
            lon: 13
      type: object
    queryParameters:
      id:
