package amf.agentfabric.internal.convert

import amf.shapes.internal.convert.ShapesBaseClientConverter

trait AgentFabricBaseClientConverter extends AgentFabricBaseConverter with ShapesBaseClientConverter
