#%RAML 1.0 Extension
extends: file://amf-client/shared/src/test/resources/org/raml/api/v10/extension/master.raml
title: extension test
traits:
  dynamic:
    body:
      text/xml:
        type: <<model>>
/extended:
  post:
    is:
      -
        dynamic:
          model: User
