#%RAML 1.0

resourceTypes: :
  rt:
    get:
      responses:
        200:
          body:
            application/json:
              type:
                properties:
                  a: string
                  b: integer
