#%RAML 1.0 DataType

type: object
description: LocalContributor model for creation
properties:
#  href:
#    type: string
#    example: https://svcsqa.harpercollins.com/GlobalIdentifiers/v1/LocalAuthors/HCUS/42472
#    required: false
  country:
    type: string
    example: USA
    required: false
  firstName:
    type: string
    example: Veronica
    required: false
  lastName:
    type: string
    example: Bartles
    required: false
  fullName:
    type: string
    example: Veronica Bartles
    required: false
  state:
    type: string
    example: PA
    required: false
  dateLastUpdated:
    type: string
    example: 11/24/2015 10:24:11 AM
    required: false
  globalAuthorId:
    type: string
    example: "880000030958"
    required: false
  mapped:
    type: boolean
    example: false
    required: false
  modifiedBy:
    type: string
    example: PIX Auto Update
    required: false
  owningEntity:
    type: string
    example: HCUS
    required: false