#%Dialect 1.0
dialect: Test
version: "1.0"
nodeMappings:
  Local:
    classTerm: v3.Local
    mapping:
      a:
        propertyTerm: v3.a
        range: string
        patch: insert
        unique: true
        mandatory: true
external:
  v3: http://test.com/v3#
documents:
  root:
    encodes: Local
  options:
    selfEncoded: true
