#%Dialect 1.0
dialect: Test
version: "1.0"
nodeMappings:
  nodeB:
    classTerm: v2.A
    mapping:
      za:
        propertyTerm: v2.a
        range: nodeA
        mapTermKey: v2.t
      zb:
        propertyTerm: v2.a
        range: nodeA
        mapTermKey: v2.t
        mapTermValue: v2.q
  nodeA:
    classTerm: v2.A
    mapping:
      a:
        propertyTerm: v2.a
        range: string
        mandatory: true
        pattern: a-z
        minimum: 1.5
        maximum: 10.5
        allowMultiple: true
        sorted: true
        enum:
          - hey
          - ho
      b:
        propertyTerm: v2.t
        range: string
      c:
        propertyTerm: v2.q
        range: string
documents:
  root:
    encodes: nodeA
    declares:
      DecB: nodeB
external:
  v2: http://test.com/v2#
