#%Dialect 1.0
dialect: Test
version: "1.0"
nodeMappings:
  Local:
    classTerm: v3.Local
    mapping:
      a:
        propertyTerm: v3.a
        range: string
        patch: insert
        unique: true
        mandatory: true
  Declarations:
    classTerm: v3.Decla
    mapping:
      b:
        propertyTerm: v3.b
        range: string
        mandatory: true
  UnionNode:
    union:
      - Local
      - Declarations
    typeDiscriminator:
      local: Local
      decls: Declarations
    typeDiscriminatorName: lala
  Root:
    classTerm: v3.Root
    mapping:
      union:
        propertyTerm: v3.union
        range: UnionNode
documents:
  root:
    encodes: Root
    declares:
      nodes: UnionNode
external:
  v3: http://test.com/v3#
