#%Dialect 1.0
dialect: Test
version: "1.0"
nodeMappings:
  Local:
    classTerm: v3.Local
    mapping:
      a:
        propertyTerm: v3.a
        range: string
        unique: true
        mandatory: true
      b:
        propertyTerm: v3.b
        range: string
        unique: true
        mandatory: true
      c:
        propertyTerm: v3.c
        range: string
    idTemplate: "#/{a}_{b}"
external:
  v3: http://test.com/v3#
documents:
  root:
    encodes: Local
