#%Dialect 1.0
dialect: TestInstance
version: 1.2
nodeMappings:
  A:
    classTerm: tmp.A
    mapping:
      a1:
        propertyTerm: tmp.a1
        range: string
      a2:
        propertyTerm: tmp.a2
        range: B
  B:
    classTerm: tmp.B
    mapping:
      b1:
        propertyTerm: tmp.b1
        range: string
      b2:
        propertyTerm: tmp.b2
        range: A
  RootNode:
    classTerm: tmp.Test
    mapping:
      a:
        propertyTerm: tmp.a
        range: A
      b:
        propertyTerm: tmp.b
        range: B
      str:
        propertyTerm: tmp.str
        range: string
documents:
  root:
    encodes: RootNode
external:
  tmp: http://test.com/tmp#