#%RAML 0.8
title: test
version: "2"
/prehook/api:
  post:
    headers:
      Authorization:
        example: AAAA wong=pakdfn
        type: string
    responses:
      "200":
        description: OK, the original request can go ahead
        body: {}
    description: Requests requiring authentication.
    body: {}
