#%RAML 0.8
title: test
version: 2
mediaType: application/json

traits:
  - secured:
      usage: Apply this to any method that needs to be secured
      description: Requests requiring authentication.
      headers:
        Authorization:
          example: AAAA wong=pakdfn

/prehook/api:
  is: [secured]
  post:
    responses: &responses
       200:
         description: OK, the original request can go ahead