#%RAML 0.8
baseUri: http://mocksvc.mulesoft.com/mocks/0e536537-1d65-4332-99a2-ba99f5429465
title: SalesODS API
version: 1.1

resourceTypes:
  - reservation-list:
      description: collection of reservations
      get:
        description: Get a list of reservations.
        responses:
          200:
            body:
              application/json:

/reservations:
  /{pnrnumber}:
    type:
        reservation-list:
    get:
      description: Get a reservation determined by pnrnumber + creation date