#%RAML 0.8
baseUri: https://mocksvc.mulesoft.com/mocks/57977fa7-a233-45fd-8a82-82114a298950
title: American Flight Api
version: "1.0"
/flights:
  get:
    description: ""
    responses:
      "200":
        body:
          application/json:
