#%RAML 0.8
title: "test raml project"
baseUri: https://mocksvc.mulesoft.com/mocks/af61f92b-2715-4164-bc71-b8e149a10875{endpoint}/{apiPath}/{version}
version: 1
baseUriParameters:

/users:
  get:
    description: get all users filtering by parameters
    headers:
    queryParameters:
      # test
    responses:
      200: