#%RAML 0.8
title: test
/test:
  post:
    responses:
      "201":
        body:
          application/json: |-
            {
              "name": "someName",
              "id" : "schema id"
            }
