#%RAML 0.8

# Objective: The following example shows how to apply a security scheme to a method.
# Expected result: no error message and the content from external files are applied respectively

# tags: security schemes, securedBy

title: test
version: 1
#securedBy: [oauth_2_0]
securitySchemes:
    - oauth_2_0: !include resources/oauth-2-0.yml
    - oauth_1_0: !include resources/oauth-1-0.raml
/users:
    get:
        securedBy: [oauth_2_0]
traits:
  allergyIntoleranceSearch:
    queryParameters: !include resources/deviceParams.yaml