#%RAML 0.8
title: test
version: "1"
securitySchemes:
  oauth_2_0:
    description: |
      OAuth 2.0 for authenticating all API requests.
    type: OAuth 2.0
    describedBy:
      headers:
        Authorization:
          description: |
            Used to send a valid OAuth 2 access token. Do not use with the "access_token" query string parameter.
          type: string
      queryParameters:
        access_token:
          description: |
            Used to send a valid OAuth 2 access token. Do not use together with the "Authorization" header
          type: string
      responses:
        "401":
          description: |
            Bad or expired token. This can happen if the user or Platform revoked or expired an access token. To fix, you should re-authenticate the user.
        "403":
          description: |
            Bad OAuth request (wrong consumer key, bad nonce, expired timestamp...). Unfortunately, re-authenticating the user won't help here.
    settings:
      authorizationUri: http://raml.link/oauth2/authorize
      accessTokenUri: http://raml.link/oauth2/token
      authorizationGrants:
        - code
        - token
  oauth_1_0:
    description: |
      OAuth 2.0 for authenticating all API requests.
    type: OAuth 2.0
    describedBy:
      headers:
        Authorization:
          description: |
            Used to send a valid OAuth 2 access token. Do not use with the "access_token" query string parameter.
          type: string
      queryParameters:
        access_token:
          description: |
            Used to send a valid OAuth 2 access token. Do not use together with the "Authorization" header
          type: string
      responses:
        "401":
          description: |
            Bad or expired token. This can happen if the user or Platform revoked or expired an access token. To fix, you should re-authenticate the user.
        "403":
          description: |
            Bad OAuth request (wrong consumer key, bad nonce, expired timestamp...). Unfortunately, re-authenticating the user won't help here.
    settings:
      authorizationUri: http://raml.link/oauth2/authorize
      accessTokenUri: http://raml.link/oauth2/token
      authorizationGrants:
        - code
        - token
/users:
  get:
    securedBy:
      - oauth_2_0
traits:
  allergyIntoleranceSearch:
    queryParameters:
      identifier:
        type: string
        required: false
        description: Instance id from manufacturer, owner, and others
      location:
        required: false
        description: A location, where the resource is found
      manufacturer:
        required: false
        description: The manufacturer of the device
      model:
        required: false
        description: The model of the device
      organization:
        required: false
        description: The organization responsible for the device
      patient:
        required: false
        description: Patient information, if the resource is affixed to a person
      type:
        required: false
        description: The type of the device
      udi:
        required: false
        description: FDA mandated Unique Device Identifier
      url:
        required: false
        description: Network address to contact device
