#%Vocabulary 1.0

vocabulary: mule-runtime
base: http://mulesoft.com/vocabularies/mule-runtime#

usage: This vocabulary describes the Mule Runtime

external:
  schema-org: http://schema.org/

classTerms:

  Runtime:
    displayName: Mule Runtime
    properties:
      - instrumented

  MulePlugin:
    displayName: Mule Plugin
    description: Component that can be installed as an extension to the core components of the Mule Runtime

  Agent:
    displayName: Mule Agent
    description: Service provided by the Runtime to allow remote introspection and manipulation of the Runtime
    extends: MulePlugin
    properties:
      - transport
      - supportsService
      - internalHandler
      - externalHandler

  AgentComponent:
    displayName: Mule Agent Component
    description: Modular component of the Mule Agent
    properties:
      - componentId
      - enabled

  AgentExtensibleComponent:
    displayName: Agent Extensible Component
    description: A Mule Component that can be
    extends: AgentComponent

  MessageHandler:
    displayName: Message Handler
    description: Component in the Mule Agnet processing an event
    extends: AgentExtensibleComponent

  InternalMessageHandler:
    displayName: Internal Message Handler
    extends: MessageHandler
    description: Message handler invoked by the Mule Agent as the result of an internal Mule event

  DomainDeploymentNotificationHandler:
    displayName: Domain Deployment Notification Handler
    extends: InternalMessageHandler

  ApplicationDeploymentNotificationHandler:
    displayName: Application Deployment Notification Handler
    extends: InternalMessageHandler

  ExternalMessageHandler:
    displayName: External Message Handler
    description: Message handler invoked by an external client through the Mule Agent
    extends: MessageHandler

  DomainRequestHandler:
    displayName: Domain Request Handler
    extends: ExternalMessageHandler

  ApplicationRequestHandler:
    displayName: Application Request Handler
    extends: ExternalMessageHandler

  Service:
    displayName: Mule Agent Service
    description: Capability supported by the Mule Agent exposing a capability of the Mule Runtime
    extends: AgentExtensibleComponent

  ApplicationService:
    displayName: Application Service
    extends: Service

  DomainService:
    displayName: Domain Service
    extends: Service

  JmxPublisherService:
    displayName: JXM Publisher Service
    extends: Service

  Transport:
    displayName: Transport
    description: Network transport used to communicate with the Mule Agent
    extends: AgentComponent

  RestTransport:
    displayName: REST Transport
    description: Network transport built on top of the HTTPS protocol
    extends: Transport

  WebSocketsTransport:
    displayName: Web Sockets Transport
    description: Network transport built on top of the WebSocket protocol
    extends: Transport

  TransportConfiguration:
    displayName: Transport Configuration
    description: Configuration of a specific network transport

  RestTransportConfiguration:
    displayName: REST Transport Configuration
    description: Configuration of the REST transport
    extends: TransportConfiguration

  KeyStore:
    displayName: Key Store
    description: encrypted repository of keys
    properties:
      - keyStorePassword
      - keyAlias
      - keyAliasPassword

  HttpProxy:
    displayName: HTTP Proxy

propertyTerms:

  host:
    displayName: host
    description: Host name
    range: string

  tcpPort:
    displayName: tcp port
    description: TCP protocol port number
    range: integer

  componentId:
    displayName: component ID
    description: ID of a component in the Mule Runtime
    range: string

  enabledComponent:
    displayName: enabled component
    description: flag advertising if this Agent Component is enabled
    range: boolean

  schema-org.version:
    displayName: version
    description: version of a component of the mule platform
    range: string

  instrumented:
    displayName: instrumented
    description: Mule Runtimes have been instrumented when the Mule Agent has been installed and configured
    range: boolean

  supportsService:
    displayName: supports service
    description: Service supported by the Mule Runtime
    range: Service

  transport:
    displayName: transport
    description: Transport that is enabled to communicate with a component of the runtime
    range: Transport

  internalHandler:
    displayName: internal handler
    description: internal handlers associated to the agent
    range: InternalMessageHandler

  externalHandler:
    displayName: external handler
    description: external handlers associated to the agent
    range: ExternalMessageHandler

  keystore:
    displayName: keystore
    description: Key store associated to a component of the Runtime
    range: KeyStore

  keyStorePassword:
    displayName: key store password
    extends: schema-org.accessCode

  keyAlias:
    displayName: key alias
    extends: schema-org.alternateName

  keyAliasPassword:
    displayName: key store alias password
    extends: schema-org.accessCode

  proxyPassword:
    displayName: proxy password
    extends: schema-org.accessCode
    range: string

  proxyUser:
    displayName: proxy username
    extends: schema-org.alternateName
    range: string

  introduced:
    displayName: introduced
    description: Version of Mule Agent introducing this service
    extends: schema-org.version
    range: string

  frequency:
    displayName: frequency

  timeUnit:
    displayName: time unit
