#%RAML 1.0 NamedExample
value:
  [
    {
      "name":
        {
          "first": "Jane",
          "last": "Smith" 
        },
      "job_title": "Field Adjuster",
      "address":
        {
          "address1": "118 2nd Ave SE",
          "city": "Cedar Rapids",
          "state": "IA",
          "zip": "52407"
        },
      "phone_number": "3191234567",
      "email": "jsmith@unitedfiregroup.com",
      "availability": "Available",
      "organization":
        {
          "offices": 
            [
              "UFG Cedar Rapids Office"
            ],
          "regions":
            [
              "UFG Work Comp Region",
              "UFG Midwest Region"
            ],
          "assignment_groups":
            [
              "PC Assignment Group Midwest 1",
              "PC Assignment Group Midwest 2",
              "PC Assignment Group Midwest 3"
            ]
        }
    },
    {
      "name":
        {
          "first": "Mark",
          "last": "Smith" 
        },
      "job_title": "Field Adjuster",
      "address":
        {
          "address1": "118 2nd Ave SE",
          "city": "Cedar Rapids",
          "state": "IA",
          "zip": "52407"
        },
      "phone_number": "3191234567",
      "email": "msmith@unitedfiregroup.com",
      "availability": "Unavailable",
      "organization":
        {
          "offices": 
            [
              "UFG Cedar Rapids Office"
            ],
          "regions":
            [
              "UFG Midwest Region"
            ],
          "assignment_groups":
            [
              "PC Assignment Group Midwest 4",
              "PC Assignment Group Midwest 5"
            ]
        }
    }
  ]