#%RAML 1.0
title: API with Examples
types:
  User:
    type: object
    properties:
      name:
        type: string
      lastname:
        type: string
    example:
      name: Bob
      lastname: Marley
    examples:
      bob:
        name: Bob
        lastname: Marley