#%RAML 1.0

title: A title
version: 1.0

types:
  Person:
    type: object
    properties:
      dni:
        type: string
  Person2:
    type: object
    properties:
      cuil:
        type: string

/endPoint:
  get:
    responses:
      200:
        body:
          application/json:
            type: Person | Person2