delete?: 
  headers: 
    X-GitHub-Media-Type: 
      description: |
        You can check the current version of media type in responses.
    Accept: 
      description: Is used to set specified media type.
    X-RateLimit-Limit: 
      type: integer
    X-RateLimit-Remaining: 
      type: integer
    X-RateLimit-Reset: 
      type: integer
    X-GitHub-Request-Id: 
      type: integer
  responses: 
    403: 
      description: |
        API rate limit exceeded. See http://developer.github.com/v3/#rate-limiting
        for details.
post?: 
  headers: 
    X-GitHub-Media-Type: 
      description: |
        You can check the current version of media type in responses.
    Accept: 
      description: Is used to set specified media type.
    X-RateLimit-Limit: 
      type: integer
    X-RateLimit-Remaining: 
      type: integer
    X-RateLimit-Reset: 
      type: integer
    X-GitHub-Request-Id: 
      type: integer
  responses: 
    403: 
      description: |
        API rate limit exceeded. See http://developer.github.com/v3/#rate-limiting
        for details.
put?: 
  headers: 
    X-GitHub-Media-Type: 
      description: |
        You can check the current version of media type in responses.
    Accept: 
      description: Is used to set specified media type.
    X-RateLimit-Limit: 
      type: integer
    X-RateLimit-Remaining: 
      type: integer
    X-RateLimit-Reset: 
      type: integer
    X-GitHub-Request-Id: 
      type: integer
  responses: 
    403: 
      description: |
        API rate limit exceeded. See http://developer.github.com/v3/#rate-limiting
        for details.
get?: 
  headers: 
    X-GitHub-Media-Type: 
      description: |
        You can check the current version of media type in responses.
    Accept: 
      description: Is used to set specified media type.
    X-RateLimit-Limit: 
      type: integer
    X-RateLimit-Remaining: 
      type: integer
    X-RateLimit-Reset: 
      type: integer
    X-GitHub-Request-Id: 
      type: integer
  responses: 
    403: 
      description: |
        API rate limit exceeded. See http://developer.github.com/v3/#rate-limiting
        for details.
patch?: 
  headers: 
    X-GitHub-Media-Type: 
      description: |
        You can check the current version of media type in responses.
    Accept: 
      description: Is used to set specified media type.
    X-RateLimit-Limit: 
      type: integer
    X-RateLimit-Remaining: 
      type: integer
    X-RateLimit-Reset: 
      type: integer
    X-GitHub-Request-Id: 
      type: integer
  responses: 
    403: 
      description: |
        API rate limit exceeded. See http://developer.github.com/v3/#rate-limiting
        for details.
