#%RAML 1.0
title: Something
annotationTypes:
  tag:
    type: any
/sample:
  get:
    responses:
      "200":
        (tag):
          name: SomeTag
          type:
            value: SomeTagType
        description: A Response
