#%RAML 1.0
title: API with Examples
types:
  User:
    properties:
      name:
        type: string
        minLength: 5
      lastname:
        type: string
        maxLength: 5
    example:
      name: Bob
      lastname: Marley
    type: object
