{
    "info":{
        "title": "test"
    },
    "swagger":"2.0",
    "paths": {},
    "definitions":{
        "accounts-collection":{
            "type":"object",
            "properties":{
                "createdTime":{
                    "$ref":"#/definitions/accounts/properties/createdTime"
                },
                "arrayLink":{
                    "$ref":"#/definitions/accounts/properties/arrayDef/items"
                }
            }
        },
        "accounts":{
            "type":"object",
            "properties":{
                "createdTime":{
                    "type":"string"
                },
                "notificationPending":{
                    "type":"boolean"
                },
                "login":{
                    "type":"string"
                },
                "arrayDef":{
                    "type":"array",
                    "items": {
                      "type": "string"
                    }
                }
            }
        }
    }
}