#%RAML 1.0
title: My API With Types
types:
  Person:
    properties:
      //: # force all additional properties to be a string
        type: integer

/test:
  get:
    responses:
      200:
        body:
          application/json:
            type: Person
            example:
              note1: "US" # not valid as it is not an integer
              note2: 123 # valid as it does not match the pattern