#%RAML 1.0
title: My API With Types
types:
  Person:
    properties:
      /^note\d+$/: # restrict any properties whose keys start with "note"
                   # followed by a string of one or more digits
        type: integer

/test:
  get:
    responses:
      200:
        body:
          application/json:
            type: Person
            example:
              note1: "US" # not valid as it is not an integer
              note2: 123 # valid as it does not match the pattern