#%RAML 1.0
---
title: Library API
baseUri: http://localhost/library

/authors:
    /{authorId}:
        uriParameters:
            authorId:
                type: integer
                description: The ID of the author.
        /books:
            /{bookId}:
                get: