#%RAML 1.0
title: Library API
baseUri: http://localhost/library
/authors:
  /{authorId}:
    /books:
      /{bookId}:
        get: {}
        uriParameters:
          bookId:
            type: string
    uriParameters:
      authorId:
        type: integer
        description: The ID of the author.
