#%RAML 1.0

title: test api

version: v3.4

/v3.4/path:
  displayName: "resourceCamelCase"
  get:
    body:
      application/json:
        type: string
    responses:
      200:
        body:
          application/xml:
            type: string

/v3.4/pathxml:
  displayName: "resourceXML"
  get:
    headers:
      Accept:
        type: string
    body:
      application/xml:
        type: string
    responses:
      200:
        body:
          application/blah:
            type: string


/v3.5/resource/nested:
  displayName: "non_camel_case"
  get:
    headers:
      Accept:
        type: string
    body:
      application/json:
        type: object
        properties:
          underscored_property:
            type: string
    responses:
      200:
        body:
          application/json:
            type: object
            properties:
              camelCaseProperty:
                type: string

/path/duplicated:
  displayName: "resourceCamelCase"
  get:
    body:
      application/json:
        type: string
    headers:
      Accept:
        type: string
    responses:
      200:
        body:
          application/json:
            type: string
