#%Validation Profile 1.0

description: Validation profile implementing common validations

profile: Banking

warning:
  - json-payloads

violation:
  - resource-camel-case-identifiers
  - mandatory-version
  - version-format
  - version-in-urls
  - allowed-payloads
  - json-properties

validations:

  mandatory-version:
    message: All APIs must have a version
    targetClass: apiContract.WebAPI
    propertyConstraints:
      core.version:
        minCount: 1

  version-format:
    message: The version must be formatted as v[Major].[Minor] or v[Major], for example v2.3
    targetClass: apiContract.WebAPI
    propertyConstraints:
      core.version:
        pattern: "v[0-9]+(.[0-9]+)?"

  version-in-urls:
    message: The version must be before the resource name, for example v1.3/payments/
    targetClass: apiContract.EndPoint
    propertyConstraints:
      apiContract.path:
        pattern: "v[0-9]+(.[0-9]+)?\/.*"


  resource-camel-case-identifiers:
    message: Identifiers must be camel-cased
    targetClass: apiContract.EndPoint
    propertyConstraints:
      core.name:
        pattern: "[a-zA-Z]([A-Z0-9]*[a-z][a-z0-9]*[A-Z]|[a-z0-9]*[A-Z][A-Z0-9]*[a-z])[A-Za-z0-9]*"

  json-payloads:
    message: JSON should be used to format content passed in and out of an API in the message body
    targetClass: apiContract.Payload
    propertyConstraints:
      core.mediaType:
        in: ["application/json"]

  allowed-payloads:
    message: JSON should be used to format content passed in and out of an API in the message body
    targetClass: apiContract.Payload
    propertyConstraints:
      core.mediaType:
        in: ["application/json", "application/xml"]

  json-properties:
    message: Property keys must be camel cased
    targetClass: sh.PropertyShape
    propertyConstraints:
      sh.name:
        pattern: "[a-zA-Z]([A-Z0-9]*[a-z][a-z0-9]*[A-Z]|[a-z0-9]*[A-Z][A-Z0-9]*[a-z])[A-Za-z0-9]*"