#%RAML 1.0
title: Billing Engine APIs
version: v1
description: Billing Engine APIs
/api:
  displayName: api
  /DocumentConfigurations:
    get:
      displayName: ApiDocumentConfigurationsGetByConfigurationNameByNameGet
      responses:
        "200":
          description: Success
          body:
            text/plain:
              type: IServiceResponse[adasf]
types:
  IServiceResponse[adasf]:
    properties:
      success?:
        type: boolean
      message?:
        type: string
        facets:
          readOnly?:
            type: boolean
      warning?:
        type: string
        facets:
          readOnly?:
            type: boolean
