#%RAML 1.0 NamedExample
value:
  accountID: '12345'
  accountType: Savings
  accountNumber: '1234567890'
  accountOwner:
    - #item 1
      customerID: 8f19cb50-3f57-4d38
      displayName: John Doe 
      ssn: 123-456-7890
  accountBalance: 
    currency: USD
    amount: '8457.90'
  IBAN: GB29NWBK60161331926820
  bank:
    bankCode: NWBKGB2L
    bankName: ACME Bank
    routingNumber: '432159876'
  createdAt: 2012-03-07T00:00:00.001Z