#%RAML 1.0 NamedExample
value:
  customerID: 8f19cb50-3f57-4d38
  firstName: John
  lastName: Doe
  displayName: John Doe
  address: 
    addressLine1: 1234 Lane
    addressLine2: Apt.#620
    city: San Francisco
    state: California
    zipCode: '94108'
    country: United States
  phone: 415-000-0000
  email: johndoe@example.com
  ssn: 123-456-7890
  dateOfBirth: 1983-01-01