#%RAML 1.0 NamedExample
value:
  customerID: 1fe1c22s-3d3a-9n3v
  firstName: Molly
  lastName: Mule
  displayName: Molly the Mule
  address: 
    addressLine1: 123 Street
    addressLine2: Apt.#3D
    city: San Francisco
    state: California
    zipCode: '94110'
    country: United States
  phone: 415-000-0000
  email: molly@mulesoft.com
  ssn: 321-654-0987
  dateOfBirth: 1990-09-04