#%RAML 1.0 NamedExample
blah:
  - id: 8624
    addressType: STORE
    country: USA
    state: CA
    city: San Francisco
    street_address: 610 Old Mason Street
    zip: 94129
  - id: 8625
    addressType: STORE
    country: USA
    state: CA
    city: San Francisco
    street_address:  1590 Bryant St
    zip: 94103
  - id: 8626
    addressType: STORE
    country: USA
    state: CA
    city: Berkeley
    street_address:  2727 Milvia St
    zip: 94703