#%RAML 1.0 SecurityScheme

description: |
  This is fake definition to test the request editor.
type: Basic Authentication
describedBy:
  responses:
    401:
      description: |
        Authorization error.
