#%RAML 1.0 Library
types:
  ObjectArray:
    type: array
    items: object

  Parent:
    properties:
      myProperty:
        type: ObjectArray

  Child:
    type: Parent
    properties:
      myProperty:
        type: AnyDeclaration

  AnyDeclaration:
    type: any

