#%RAML 1.0
title: Security Scheme invalid ref in trait
securitySchemes:
  ssone:
    type: x-bosta
traits:
  secOk:
    <<field>>:
      - ssone
  secBroken:
    <<field>>:
      - undefined
  secMaybeBroken:
    securedBy:
      - <<ssname>>
/sec:
  get:
    is:
      -
        secOk:
          field: securedBy
  post:
    is:
      -
        secBroken:
          field: securedBy
  put:
    is:
      -
        secMaybeBroken:
          ssname: ssone
  delete:
    is:
      -
        secMaybeBroken:
          ssname: undefined
