package amf.plugins.document.apicontract.parser.spec.grpc

object TokenTypes {
  val PROTO = "proto"
  val SYNTAX = "syntax"
  val IMPORT_STATEMENT = "importStatement"
  val TOP_LEVEL_DEF = "topLevelDef"
  val PACKAGE_STATEMENT = "packageStatement"
  val FULL_IDENTIFIER = "fullIdent"
  val SERVICE_DEF = "serviceDef"
  val SERVICE_NAME = "serviceName"
  val SERVICE_ELEMENT = "serviceElement"
  val RPC = "rpc"
  val RPC_NAME = "rpcName"
  val MESSAGE_DEF = "messageDef"
  val MESSAGE_BODY = "messageBody"
  val MESSAGE_ELEMENT = "messageElement"
  val MESSAGE_NAME = "messageName"
  val MESSAGE_TYPE = "messageType"
  val FIELD = "field"
  val FIELD_NAME = "fieldName"
  val FIELD_NUMBER = "fieldNumber"
  val FIELD_TYPE = "type_"
  val ENUM_DEF = "enumDef"
  val ENUM_NAME = "enumName"
  val ENUM_BODY = "enumBody"
  val ENUM_ELEMENT = "enumElement"
  val ENUM_FIELD = "enumField"
  val ONE_OF = "oneof"
  val ONE_OF_NAME = "oneofName"
  val ONE_OF_FIELD = "oneofField"
  val MAP_FIELD = "mapField"
  val KEY_TYPE = "keyType"
  val MAP_NAME = "mapName"
  val REPEATED = "REPEATED"
  val IDENTIFIER = "ident"
  val KEYWORDS = "keywords"
  val OPTION_STATEMENT = "optionStatement"
  val OPTION = "option"
  val OPTION_NAME = "optionName"
  val CONSTANT = "constant"
  val BLOCK_LITERAL = "blockLit"
  val FLOAT_LITERAL = " floatLit"
  val STRING_LITERAL = "strLit"
  val BOOL_LITERAL = "boolLit"
  val INT_LITERAL = "intLit"
}
