#%RAML 1.0 DataType

description: Root batchnumbers default output resource
type: object
properties:
  status: 
    type: Status
  batchnumber:
    type: object
    properties:
      interface:
        type: string
        example: "JDE_123_INBOUND"
      batchnumber:
        type: string
        example: "00001"
      locked:
        type: boolean
        example: false