#%RAML 1.0
title: test

types:
  test1: |
    {
      "type": "object",
      "dependencies": {
        "undefinedProperty": {
          "type": "object",
          "properties": {
            "restrictedProperty": {
              "type": "string",
              "enum": [
                "A",
                "B"
              ]
            }
          }
        }
      }
    }

/ep1:
  get:
    responses:
      200:
        body:
          application/json:
            type: test1
            example:
              undefinedProperty: some value
              restrictedProperty: invalid value

/ep2:
  get:
    responses:
      200:
        body:
          application/json:
            type: test1
            example:
              undefinedProperty: some value
              restrictedProperty: A
