#%RAML 1.0
title: api
version: 1
resourceTypes:
  rt1:
    post?:
      body:
        application/json:
          type: asd
/endpoint1:
  type: rt1 # should not fail
/endpoint2:
  type: rt1
  post:     # should fail