#%RAML 1.0 Dialect

dialect: Other Dialect
version: 1.0

external:
  test: "http://test.com/"

nodeMappings:

  libraryNode:
    classTerm: test.LibraryNode
    mapping:
      other:
        propertyTerm: test.other
        range: string
        mandatory: true