#%RAML 1.0
title: Example API
version: v1
resourceTypes:
  collection:
    usage: This resourceType should be used for any collection of items
    description: The collection of <<resourcePathName>>
    get:
      description: Get all <<resourcePathName>>, optionally filtered
    post:
      description: Create a new <<resourcePathName | !singularize>>
      <<some>>: some
      body:
        application/json: a<<someType>>a
    <<someProperty>>: some value
traits:
  secured:
    usage: Apply this to any method that needs to be secured
    description: Some requests require authentication.
    headers:
    <<someProperty>>: some value
      access_token:
        <<some>>: some
        type: a<<someType>>a
        description: Access Token
        example: 5757gh76
        required: true