#%RAML 1.0
annotationTypes:
  amf-serverDescription:
    type: any
  amf-exclusiveMinimum:
    type: any
  amf-binding:
    type: any
  amf-pattern:
    type: any
  amf-payloads:
    type: any
  amf-exclusiveMaximum:
    type: any
  amf-consumes:
    type: any
  amf-additionalProperties:
    type: any
  amf-or:
    type: any
  amf-url:
    type: any
  amf-externalDocs:
    type: any
  amf-flow:
    type: any
  amf-oasDeprecated:
    type: any
  amf-contact:
    type: any
  amf-multipleOf:
    type: any
  amf-xor:
    type: any
  amf-not:
    type: any
  amf-callbacks:
    type: any
  amf-produces:
    type: any
  amf-format:
    type: any
  amf-license:
    type: any
  amf-summary:
    type: any
  amf-responses:
    type: any
  amf-maximum:
    type: any
  amf-tags:
    type: any
  amf-dependencies:
    type: any
  amf-readOnly:
    type: any
  amf-tuple:
    type: any
  amf-examples:
    type: any
  amf-collectionFormat:
    type: any
  amf-termsOfService:
    type: any
  amf-servers:
    type: any
  amf-xone:
    type: any
  amf-defaultResponse:
    type: any
  amf-baseUriParameters:
    type: any
  amf-parameters:
    type: any
  amf-minimum:
    type: any
  amf-recursive:
    type: any
  amf-and:
    type: any
securitySchemes:
  basic:
    type: Basic Authentication
    description: Basic HTTP Authentication
  apiKey:
    type: x-apiKey
    description: API Key
    describedBy:
      headers:
        default?:
          type: any
  oauth2Scheme:
    type: OAuth 2.0
    settings:
      authorizationUri: http://swagger.io/api/oauth/dialog
      accessTokenUri: ""
      scopes:
        - write:pets
        - read:pets
      authorizationGrants:
        - implicit
title: Secured API
baseUri: secured.api.com/
version: v1
protocols:
  - HTTPS
/ping:
  get:
    displayName: ping
    (amf-summary): Checks if service is capable of responding to requests
    (amf-tags):
      - ping
    (amf-consumes): []
    (amf-produces):
      - application/json
      - application/xml
    responses:
      "200":
        description: OK
        body:
          application/json:
            type: object
          application/xml:
            type: object
securedBy:
  - basic
  - apiKey
