#%RAML 1.0 Library
types:
  outletResponse: !include outlet/outletResponse.raml
  productResponse: !include product/productResponse.raml
  transactionRequest: !include transaction/transactionRequest.raml
  transactionResponse: !include transaction/transactionResponse.raml
  promotionResponse: !include promotion/promotionResponse.raml
    