#%RAML 1.0
title: Bells API
version: v1
baseUri: http://localhost/api
types:
  Bell:
    properties:
      id:
        type: integer
      name:
        type: string
/bells:
  get:
    responses:
      "200":
        body:
          application/json:
            type: Bell
  post:
    body:
      application/json:
        type: Bell
