#%RAML 1.0 DocumentationItem
title: Design Center Publication Status Process API
content: This API will provide the details on RAML specifications and fragments that are present in Design Center but not published to Exchange