#%RAML 1.0
title: my api
version: 1.0
traits:
  invalidTrait:
    asd1:
  invalidTrait2:
    is: [invalidTrait]
resourceTypes:
  rtNestedKO:
    is: [invalidTrait2]
  rtKO:
    is: [invalidTrait]
/e0:
  type: rtNestedKO
/e1:
  type: rtKO

