#%RAML 1.0
title: Resume API
mediaType: application/json
types:
  resumeAssessmentObject:
    type: object
    properties:
      explanation:
        type: string
        required: true
        example: ""
/resumes:
  description: "Gets the Resume data by id."
  get:
    responses:
      200:
        body:
          application/json:
            type: resumeAssessmentObject