#%RAML 1.0 Overlay
title: Slave RAML
extends: file://amf-client/shared/src/test/resources/org/raml/parser/overlays/with-uses/master.raml
/elements:
  get:
    description: |
      describing your method here
    (decls.important): null
uses:
  decls: lib.raml
