#%RAML 1.0
title: test title
types:
  person: lib.Person
  person2: lib2.Person
  person3: lib3.Person
uses:
  lib: lib/lib-declaration.raml
  lib2: lib/lib-declaration.raml
  lib3: lib/lib-declaration.raml
