#%ValidationExample 1.1
any_array:
  - hey
  - 1
  - 1.0
  - true
  - 2
  - 2017-08-30
  - 2017-08-30T19:56:58Z
  - http://roberto.com
any_array_sorted:
  - hey
  - 1
  - 1.0
  - true
  - 2
  - 2017-08-30
  - 2017-08-30T19:56:58Z
  - http://roberto.com