#%Dialect 1.0
dialect: ValidationExample
version: 1.3
nodeMappings:
  RootNode:
    classTerm: tmp.Test
    mapping:
      multiple:
        propertyTerm: tmp.multiple
        range: string
        allowMultiple: true
      single:
        propertyTerm: tmp.single
        range: string
documents:
  root:
    encodes: RootNode
external:
  tmp: http://test.com/tmp#