#%Dialect 1.0
dialect: ValidationExample
version: 1.1
nodeMappings:
  RootNode:
    classTerm: tmp.Test
    mapping:
      str:
        propertyTerm: tmp.str
        range: string
        mandatory: true
      int:
        propertyTerm: tmp.int
        range: integer
        mandatory: true
      float:
        propertyTerm: tmp.float
        range: float
        mandatory: true
      boolean:
        propertyTerm: tmp.boolean
        range: boolean
        mandatory: true
      number:
        propertyTerm: tmp.number
        range: number
        mandatory: true
      date:
        propertyTerm: tmp.date
        range: date
        mandatory: true
      dateTime:
        propertyTerm: tmp.dateTime
        range: dateTime
        mandatory: true
      uri:
        propertyTerm: tmp.uri
        range: uri
        mandatory: true
documents:
  root:
    encodes: RootNode
external:
  tmp: http://test.com/tmp#