#%Dialect 1.0
dialect: ValidationExample
version: 1.7
nodeMappings:
  RootNode:
    classTerm: tmp.Test
    mapping:
      nested:
        propertyTerm: tmp.nested
        range: DeclaredNode
  DeclaredNode:
    classTerm: tmp.Declared
    mapping:
      property:
        propertyTerm: tmp.property
        range: string
documents:
  root:
    declares:
      declarations: DeclaredNode
    encodes: RootNode
external:
  tmp: http://test.com/tmp#