#%Dialect 1.0
dialect: ValidationExample
version: 2.0
nodeMappings:
  RootNode:
    classTerm: tmp.Test
    mapping:
      mandatory:
        propertyTerm: tmp.b
        mandatory: true
        range: string
      optional:
        propertyTerm: tmp.c
        range: string
      a:
        propertyTerm: tmp.a
        mandatory: true
        range: string

documents:
  root:
    encodes: RootNode
  options:
    keyProperty: true
external:
  tmp: http://test.com/tmp#