#%Dialect 1.0
dialect: TestInstance
version: 1.1b
nodeMappings:
  RootNode:
    classTerm: tmp.Test
    mapping:
      timestampStr:
        propertyTerm: tmp.timestamp
        range: string
documents:
  root:
    encodes: RootNode
external:
  tmp: http://test.com/tmp#