#%Dialect 1.0
dialect: ValidationExample
version: 1.6
nodeMappings:
  RootNode:
    classTerm: tmp.Test
    mapping:
      enum:
        propertyTerm: tmp.enum
        range: string
        enum:
          - a
          - b
          - c
documents:
  root:
    encodes: RootNode
external:
  tmp: http://test.com/tmp#