#%Dialect 1.0
dialect: ValidationExample
version: 1.10
nodeMappings:
  RootNode:
    classTerm: tmp.Test
    mapping:
      date:
        propertyTerm: tmp.date
        range: date
        mandatory: true
      dateTime:
        propertyTerm: tmp.dateTime
        range: dateTime
        mandatory: true
documents:
  root:
    encodes: RootNode
external:
  tmp: http://test.com/tmp#