#%Validation Profile 1.0

profile: Custom Eng-Demos Validation

prefixes:
  eng-demos: http://mulesoft.com/vocabularies/eng-demos#
  schema-org: http://schema.org/

violation:
  - test-custom-validation
  - other-validation

validations:

  test-custom-validation:
    message: one error
    targetClass: eng-demos.Speaker
    propertyConstraints:
      schema-org.age:
        minCount: 3

  other-validation:
    message: another error
    targetClass: http://mulesoft.com/vocabularies/eng-demos#Speaker
    propertyConstraints:
      http://mulesoft.com/vocabularies/eng-demos#nonExistent:
        minCount: 1