#%Library / Eng Demos 0.1

products:
  amf:
    name: AMF
    version: 1.0.0
    description: Something we had to build becase we can
    resources:
      - https://github.com/mulesoft/amf
      - https://github.com/mulesoft-labs/amf-eng-demos
  api-query:
    name: API Query
    version: 0.0.2
    description: Querying APIs
    resources:
       - https://github.com/mulesoft-labs/api-query