#%RAML 0.8
title: test

traits:
  rateLimited:
    responses:
      200?:
        description: aDescription
      201?:
        description: anotherDescription
      204?:
        description: yetAnotherDescription
      429:
        description: Too Many Requests. The number of HTTP requests exceeds the SLA limit.
/test:
  get:
    is: [rateLimited]
    responses:
      200:
