#%RAML 1.0
title: some title

types:
  TheType:
    properties:
      name: string

resourceTypes:
  TheResourceType:
    delete:
      responses:
        200:
          body:
            application/json:
              type: TheType
              examples: <<examp>>
            application/xml:
              type: TheType
              examples: <<examp>>

/the-one-endpoint:
  type:
    TheResourceType:
      examp: !include some-example.raml