#%RAML 1.0
title: api
mediaType: application/json
resourceTypes:
  rt-explicit:
    get:
      body:
        application/json:
          type: number
  rt-implicit:
    get:
      body:
        type: number
/e-explicit:
  type: rt-implicit
  get:
    body:
      application/json:
        example: 1
/e-implicit:
  type: rt-explicit
  get:
    body:
      example: 1
