#%RAML 1.0 Trait
displayName: Enforce Client ID
headers:
  client_id:
    type: string
    displayName: Client ID
    required: true
  client_secret:
    type: string
    displayName: Client Secret
    required: true