#%RAML 1.0
title: Customer System API
version: "4.0"
baseUri: https://localhost:8081/api
/customer:
  displayName: Customers
  description: |
    Working with customers:
    * Retrieving all customers
    * Creating customers
  get:
    description: |
      Retrieve all the Customers.
    queryParameters:
      email:
        displayName: The account email address
        minLength: 0
        maxLength: 255
        required: false
      date:
        type: datetime
    responses:
      "200":
        body:
          application/json:
            items:
              properties:
                id?:
                  type: string
                customerName:
                  type: string
                phone:
                  type: string
                email:
                  type: string
                billingAddress?:
                  properties:
                    address?:
                      minItems: 1
                      items:
                        type: string
                    city?:
                      type: string
                    state?:
                      type: string
                    postalCode?:
                      type: string
                    country?:
                      type: string
                      displayName: Country Name
                      description: Country Name
                shippingAddress?:
                  properties:
                    address?:
                      minItems: 1
                      items:
                        type: string
                    city?:
                      type: string
                    state?:
                      type: string
                    postalCode?:
                      type: string
                    country?:
                      type: string
                      displayName: Country Name
                      description: Country Name
    body: {}
  post:
    description: |
      Create a new Customer
    responses:
      "201":
        description: Created
        body:
          application/json:
            type: any
    body:
      application/json:
        properties:
          id?:
            type: string
          customerName:
            type: string
          phone:
            type: string
          email:
            type: string
          billingAddress?:
            properties:
              address?:
                minItems: 1
                items:
                  type: string
              city?:
                type: string
              state?:
                type: string
              postalCode?:
                type: string
              country?:
                type: string
                displayName: Country Name
                description: Country Name
          shippingAddress?:
            properties:
              address?:
                minItems: 1
                items:
                  type: string
              city?:
                type: string
              state?:
                type: string
              postalCode?:
                type: string
              country?:
                type: string
                displayName: Country Name
                description: Country Name
  /{id}:
    displayName: Customer ID
    uriParameters:
      id:
        type: number
        example: 4.3
        description: Represents the customer unique id
    get:
      description: Get Customer by ID
      headers:
        GET-TYPES:
          type: array
        Accept:
          type: string
      responses:
        "400":
          body:
            application/json:
              examples:
                example_0:
                  message: Bad message
                example_1:
                  message: Resource not found
              properties:
                message:
                  type: string
                code?:
                  type: string
        "200":
          body:
            application/json:
              properties:
                id?:
                  type: string
                customerName:
                  type: string
                phone:
                  type: string
                email:
                  type: string
                billingAddress?:
                  properties:
                    address?:
                      minItems: 1
                      items:
                        type: string
                    city?:
                      type: string
                    state?:
                      type: string
                    postalCode?:
                      type: string
                    country?:
                      type: string
                      displayName: Country Name
                      description: Country Name
                shippingAddress?:
                  properties:
                    address?:
                      minItems: 1
                      items:
                        type: string
                    city?:
                      type: string
                    state?:
                      type: string
                    postalCode?:
                      type: string
                    country?:
                      type: string
                      displayName: Country Name
                      description: Country Name
        "404":
          body:
            application/json:
              examples:
                example_0:
                  message: Bad message
                example_1:
                  message: Resource not found
              properties:
                message:
                  type: string
                code?:
                  type: string
      body: {}
    put:
      responses:
        "204":
          body: {}
      body:
        application/json:
          properties:
            id?:
              type: string
            customerName:
              type: string
            phone:
              type: string
            email:
              type: string
            billingAddress?:
              properties:
                address?:
                  minItems: 1
                  items:
                    type: string
                city?:
                  type: string
                state?:
                  type: string
                postalCode?:
                  type: string
                country?:
                  type: string
                  displayName: Country Name
                  description: Country Name
            shippingAddress?:
              properties:
                address?:
                  minItems: 1
                  items:
                    type: string
                city?:
                  type: string
                state?:
                  type: string
                postalCode?:
                  type: string
                country?:
                  type: string
                  displayName: Country Name
                  description: Country Name
    delete:
      responses:
        "204":
          body: {}
/person:
  displayName: Person
  /{id}:
    displayName: Person ID
    uriParameters:
      id:
        type: number
        example: 4.3
        description: Represents the person unique id
    get:
      description: Get person by ID
      queryParameters:
        names:
          type: array
      responses:
        "400":
          body:
            application/json:
              examples:
                example_0:
                  message: Bad message
                example_1:
                  message: Resource not found
              properties:
                message:
                  type: string
                code?:
                  type: string
        "200":
          body:
            application/json:
              anyOf:
                -
                  properties:
                    id?:
                      type: string
                    customerName:
                      type: string
                    phone:
                      type: string
                    email:
                      type: string
                    billingAddress?:
                      properties:
                        address?:
                          minItems: 1
                          items:
                            type: string
                        city?:
                          type: string
                        state?:
                          type: string
                        postalCode?:
                          type: string
                        country?:
                          type: string
                          displayName: Country Name
                          description: Country Name
                    shippingAddress?:
                      properties:
                        address?:
                          minItems: 1
                          items:
                            type: string
                        city?:
                          type: string
                        state?:
                          type: string
                        postalCode?:
                          type: string
                        country?:
                          type: string
                          displayName: Country Name
                          description: Country Name
                -
                  properties:
                    id?:
                      type: string
                    sellerName:
                      type: string
                    phone:
                      type: string
                    email:
                      type: string
        "404":
          body:
            application/json:
              examples:
                example_0:
                  message: Bad message
                example_1:
                  message: Resource not found
              properties:
                message:
                  type: string
                code?:
                  type: string
      body: {}
