#%RAML 1.0
title: API
/test:
  get:
    body:
      application/json:
        anyOf:
          -
            items:
              anyOf:
                -
                  type: object
                  (amf-recursive): file://amf-cli/shared/src/test/resources/production/recursive-union.raml#/web-api/endpoint/%2Ftest/supportedOperation/get/expects/request/payload/application%2Fjson/any/schema/inherits/any/SomeType/inherits/array/SomeUnion/inherits/union/default-union/anyOf/array/default-array
                -
                  items:
                    anyOf:
                      -
                        type: object
                        (amf-recursive): file://amf-cli/shared/src/test/resources/production/recursive-union.raml#/web-api/endpoint/%2Ftest/supportedOperation/get/expects/request/payload/application%2Fjson/any/schema/inherits/any/SomeType/inherits/array/SomeUnion/inherits/union/default-union/anyOf/array/default-array
                      -
                        type: object
                        (amf-recursive): file://amf-cli/shared/src/test/resources/production/recursive-union.raml#/web-api/endpoint/%2Ftest/supportedOperation/get/expects/request/payload/application%2Fjson/any/schema/inherits/any/SomeType/inherits/array/SomeUnion/inherits/union/default-union/anyOf/array/default-array_1
          -
            items:
              anyOf:
                -
                  type: object
                  (amf-recursive): file://amf-cli/shared/src/test/resources/production/recursive-union.raml#/web-api/endpoint/%2Ftest/supportedOperation/get/expects/request/payload/application%2Fjson/any/schema/inherits/any/SomeType/inherits/array/SomeUnion/inherits/union/default-union/anyOf/array/default-array
                -
                  type: object
                  (amf-recursive): file://amf-cli/shared/src/test/resources/production/recursive-union.raml#/web-api/endpoint/%2Ftest/supportedOperation/get/expects/request/payload/application%2Fjson/any/schema/inherits/any/SomeType/inherits/array/SomeUnion/inherits/union/default-union/anyOf/array/default-array_1
