#%AsyncAPI 0.5

asyncapi: 1.0.0

baseTopic: hitch.accounts

messages:
  a_message:
    summary: a message

securitySchemes:
  api_key:
    type: httpApiKey
    description: API Key requirement
    in: apiKey
    scheme: https

security:
  - scheme:
      $ref: "#/securitySchemes/api_key"
    scopes: []

externalDocs:
  url: http://www.example.com/documentation
  description: main documentation link

info:
  version: 1.0.0
  title: AsyncAPI Sample App
  description: This is a sample server.
  termsOfService: http://asyncapi.org/terms/
  contact:
    name: API Support
    url: http://www.example.com/support
    email: support@example.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html

servers:
  - url: development.gigantic-server.com
    description: Development server
    scheme: mqtts
  - url: staging.gigantic-server.com
    description: Staging server
    scheme: mqtts
  - url: api.gigantic-server.com
    description: Production server
    scheme: mqtts
  - url: "{username}.gigantic-server.com:{port}/{basePath}"
    scheme: mqtts
    description: The production API Server
    variables:
      username:
        default: demo
        description: This value is assigned by the service provider, in this example `gigantic-server.com`
      port:
        enum:
          - '8883'
          - '8884'
        default: '8883'
      basePath:
        default: v2

topics:

  my.topic:
    publish:
      summary: a summary
      description: a description
      payload:
        type: object
        properties:
          a:
            type: string
          b:
            type: number
          c:
            type: object
            properties:
              d:
                type: string
    subscribe:
      payload:
        type: array
        items:
          type: string



  signup:

    subscribe:
      $ref: "#/messages/a_message"

    publish:
      summary: Action to sign a user up
      description: A longer description
      tags:
        - name: user
        - name: signup
        - name: register
      headers:
        type: object
        properties:
          qos:
            type: string
          retainFlag:
            type: string
      payload:
        type: object
        properties:
          user:
            type: string
          signup:
            type: string
      externalDocs:
        url: http://www.example.com/documentation#signup
        description: documentation about the signup action
