#%RAML 1.0
version: v1
title: Version Manager
/projects/{project_id}/versions:
  get:
    queryParameters:
      version_name?:
        description: name of the version. Looks for the exact name
        type: string
    responses:
      200:
        body:
          application/json:
            additionalProperties: true
            properties:
              project_versions:
                type: array
                items:
                  examples:
                    value:
                      description: SAP Connector v-3.2.0
                  additionalProperties: true
                  properties:
                    name:
                      type: string
                      required: true
                    id:
                      type: integer
                      required: false
                    description:
                      type: string
                      required: false
                    start_date:
                      type: date-only
                      required: false
                    release:
                      additionalProperties: true
                      properties:
                        release_date:
                          type: date-only
                          required: false
                        released:
                          type: boolean
                          default: false
                          required: false
                      required: false
                required: true
              customer_reported_project_versions:
                type: array
                items:
                  examples:
                    value:
                      description: SAP Connector v-3.2.0
                  additionalProperties: true
                  properties:
                    name:
                      type: string
                      required: true
                    id:
                      type: integer
                      required: false
                    description:
                      type: string
                      required: false
                    start_date:
                      type: date-only
                      required: false
                    release:
                      additionalProperties: true
                      properties:
                        release_date:
                          type: date-only
                          required: false
                        released:
                          type: boolean
                          default: false
                          required: false
                      required: false
                required: true
  post:
    description: Add a new <<resourcePathName | !singularize>>
    displayName: Add new <<resourcePathName | !singularize>>
    body:
      application/json:
        examples:
          value:
            description: SAP Connector v-3.2.0
        additionalProperties: true
        properties:
          name:
            type: string
            required: true
          id:
            type: integer
            required: false
          description:
            type: string
            required: false
          start_date:
            type: date-only
            required: false
          release:
            additionalProperties: true
            properties:
              release_date:
                type: date-only
                required: false
              released:
                type: boolean
                default: false
                required: false
            required: false
    responses:
      201:
        headers:
          Location:
            type: string
            description: URL of the new version  information
            example: /version/8f19cb50-3f57-4d38
        body:
          type: any
      503:
        body:
          application/json:
            type: object
            additionalProperties: true
            properties:
              statusCode:
                type: string
                required: true
              message:
                type: string
                required: true
  /{version_id}:
    get:
      displayName: Get version by version ID
      description: Retrieve a specific version
      responses:
        404:
          body:
            application/json:
              type: object
              additionalProperties: true
              properties:
                statusCode:
                  type: string
                  required: true
                message:
                  type: string
                  required: true
        200:
          body:
            application/json:
              examples:
                value:
                  description: SAP Connector v-3.2.0
              additionalProperties: true
              properties:
                name:
                  type: string
                  required: true
                id:
                  type: integer
                  required: false
                description:
                  type: string
                  required: false
                start_date:
                  type: date-only
                  required: false
                release:
                  additionalProperties: true
                  properties:
                    release_date:
                      type: date-only
                      required: false
                    released:
                      type: boolean
                      default: false
                      required: false
                  required: false
    put:
      body:
        application/json:
          examples:
            value:
              description: SAP Connector v-3.2.0
          additionalProperties: true
          properties:
            name:
              type: string
              required: true
            id:
              type: integer
              required: false
            description:
              type: string
              required: false
            start_date:
              type: date-only
              required: false
            release:
              additionalProperties: true
              properties:
                release_date:
                  type: date-only
                  required: false
                released:
                  type: boolean
                  default: false
                  required: false
              required: false
      displayName: Update version by version ID
      description: Update all data in version
      responses:
        204: {}
        404:
          body:
            application/json:
              type: object
              additionalProperties: true
              properties:
                statusCode:
                  type: string
                  required: true
                message:
                  type: string
                  required: true
    /releases:
      post: {}
      get:
        displayName: Get release by release ID
        description: Retrieve a specific release
        responses:
          404:
            body:
              application/json:
                type: object
                additionalProperties: true
                properties:
                  statusCode:
                    type: string
                    required: true
                  message:
                    type: string
                    required: true
          200:
            body:
              application/json:
                additionalProperties: true
                properties:
                  release_date:
                    type: date-only
                    required: false
                  released:
                    type: boolean
                    default: false
                    required: false
      put:
        body:
          application/json:
            additionalProperties: true
            properties:
              release_date:
                type: date-only
                required: false
              released:
                type: boolean
                default: false
                required: false
        description: modifies an object completly
        displayName: Update release by release ID
        responses:
          204: {}
          404:
            body:
              application/json:
                type: object
                additionalProperties: true
                properties:
                  statusCode:
                    type: string
                    required: true
                  message:
                    type: string
                    required: true
      patch:
        description: modifies a release based on a specific operation
        body:
          application/json:
            examples:
              value:
                value:
                  ops:
                    -
                      op: release
                    -
                      op: change_release_date
                      value: 2018-02-02
            additionalProperties: true
            properties:
              ops:
                type: array
                items:
                  additionalProperties: true
                  properties:
                    op:
                      type: string
                      enum:
                        - release
                        - unrelease
                        - change_release_date
                      required: true
                    value:
                      description: only need when using change_release_date or release operations
                      type: date-only
                      required: false
                required: true
        displayName: Update release by release ID
        responses:
          204: {}
          404:
            body:
              application/json:
                type: object
                additionalProperties: true
                properties:
                  statusCode:
                    type: string
                    required: true
                  message:
                    type: string
                    required: true
