#%RAML 1.0
title: test
securedBy:
  - oauth_2_0
securitySchemes:
  oauth_2_0: !include ../../../../references/fragments/security-scheme.raml
  oauth_1_0:
    description: OAuth 1.0 continues to be supported for all API requests, but OAuth 2.0 is now preferred.
    type: OAuth 1.0
    describedBy:
      headers:
        Authorization:
          description: Used to send a valid OAuth 2 access token.
          type: string
      queryParameters:
        access_token:
          description: Used to send a valid OAuth 2 access token.
      responses:
        "401":
          description: Authorization error.
          body:
            application/json:
              properties:
                merge:
                  type: string
    settings:
      requestTokenUri: https://api.mysampleapi.com/1/oauth/request_token
      authorizationUri: https://api.mysampleapi.com/1/oauth/authorize
      tokenCredentialsUri: https://api.mysampleapi.com/1/oauth/access_token
      signatures:
        - HMAC-SHA1
        - PLAINTEXT
/users:
  get:
    securedBy:
      - oauth_2_0
      - oauth_1_0
/users/{userid}/gists:
  get:
    securedBy:
      - null
      -
        oauth_2_0:
          scopes:
            - ADMINISTRATOR
