#%RAML 1.0
title: example security schemes
securitySchemes:
  oauth_2_0:
    type: OAuth 2.0
    describedBy:
      headers:
        Authorization:
          description: Used to send a valid OAuth 2 access token.
          type: string
      queryParameters:
        access_token:
          description: Used to send a valid OAuth 2 access token.
          type: string
      responses:
        "401":
          description: Bad or expired token.
        "403":
          description: Bad OAuth request (wrong consumer key, bad nonce, expired timestamp...).
    settings:
      authorizationUri: https://www.dropbox.com/1/oauth2/authorize
      accessTokenUri: https://api.dropbox.com/1/oauth2/token
      authorizationGrants:
        - authorization_code
        - implicit
  oauth_1_0:
    description: OAuth 1.0 continues to be supported for all API requests, but OAuth 2.0 is now preferred.
    type: OAuth 1.0
    settings:
      requestTokenUri: https://apidomain.com/1/oauth/request_token
      authorizationUri: https://www.site.com/1/oauth/authorize
      tokenCredentialsUri: https://apidomain.com/1/oauth/access_token
  basic_auth:
    type: Basic Authentication
  digest_auth:
    type: Digest Authentication
  api_key:
    type: x-amf-apiKey
    settings:
      name: HeaderName
      in: header_location
  custom_auth:
    type: x-custom
    settings:
      custom: Setting
