#%RAML 1.0 ResourceType
get?:
  responses: 
    200:
      body: 
        application/json:
          type: <<item>>
          example: <<itemExample>>
        application/xml:
          type: <<item>>
          example: <<itemExample>>
    404:
      body: 
        application/json:
          type: <<errorItem>>
          
delete?:
  responses: 
    200:
      body: 
        application/json:
          example:
            message: Deleted successfully the <<resourcePathName | !singularize>>