#%RAML 1.0 Library
types:
  A:
    type: array
    items:
      type: object
      additionalProperties: true
      properties:
        a:
          required: true
          type: union
          anyOf:
            -
              type: string
            -
              type: integer
        b:
          required: true
          type: any
  B:
    type: array
    items:
      type: object
      additionalProperties: true
      properties:
        a:
          required: true
          type: union
          anyOf:
            -
              type: string
            -
              type: integer
        b:
          required: true
          type: any
  C:
    type: array
    items:
      type: object
      additionalProperties: true
      properties:
        a:
          required: true
          type: union
          anyOf:
            -
              type: string
            -
              type: integer
        b:
          required: true
          type: any
        c:
          required: true
          type: number
