#%RAML 1.0 Library
types:
  A:
    items:
      additionalProperties: true
      properties:
        a:
          type: string | integer
          required: true
        b:
          type: nil
          required: true
