#%RAML 1.0 Library
types:
  Phone:
    type: object
    additionalProperties: true
    properties:
      manufacturer:
        required: true
        type: string
      numberOfSIMCards:
        required: true
        type: number
      kind:
        required: true
        type: string
  Device:
    type: object
    additionalProperties: true
    properties:
      manufacturer:
        required: true
        type: string
      numberOfUSBPorts:
        required: true
        type: number
      kind:
        required: true
        type: string
  Main:
    type: union
    anyOf:
      -
        type: object
        additionalProperties: true
        properties:
          manufacturer:
            required: true
            type: string
          numberOfSIMCards:
            required: true
            type: number
          kind:
            required: true
            type: string
          phone:
            required: true
            type: object
            additionalProperties: true
            properties:
              manufacturer:
                required: true
                type: string
              numberOfSIMCards:
                required: true
                type: number
              kind:
                required: true
                type: string
          device:
            required: true
            type: union
            anyOf:
              -
                type: object
                additionalProperties: true
                properties:
                  manufacturer:
                    required: true
                    type: string
                  numberOfSIMCards:
                    required: true
                    type: number
                  kind:
                    required: true
                    type: string
              -
                type: object
                additionalProperties: true
                properties:
                  manufacturer:
                    required: true
                    type: string
                  numberOfUSBPorts:
                    required: true
                    type: number
                  kind:
                    required: true
                    type: string
      -
        type: object
        additionalProperties: true
        properties:
          manufacturer:
            required: true
            type: string
          numberOfUSBPorts:
            required: true
            type: number
          kind:
            required: true
            type: string
          phone:
            required: true
            type: object
            additionalProperties: true
            properties:
              manufacturer:
                required: true
                type: string
              numberOfSIMCards:
                required: true
                type: number
              kind:
                required: true
                type: string
          device:
            required: true
            type: union
            anyOf:
              -
                type: object
                additionalProperties: true
                properties:
                  manufacturer:
                    required: true
                    type: string
                  numberOfSIMCards:
                    required: true
                    type: number
                  kind:
                    required: true
                    type: string
              -
                type: object
                additionalProperties: true
                properties:
                  manufacturer:
                    required: true
                    type: string
                  numberOfUSBPorts:
                    required: true
                    type: number
                  kind:
                    required: true
                    type: string
