#%RAML 1.0 Library
types:
  CatWithCity:
    additionalProperties: true
    properties:
      city:
        required: true
        type: string
  CatWithAddress:
    additionalProperties: true
    properties:
      address:
        required: true
        type: string
  Cat:
    type: object
    additionalProperties: true
    properties:
      city:
        required: true
        type: string
      address:
        required: true
        type: string
      age:
        required: true
        anyOf:
          -
            type: string
          -
            type: number
