#%RAML 1.0 Library
types:
  A:
    type: object
    additionalProperties: true
    properties:
      a:
        required: true
        type: number
  B:
    type: object
    additionalProperties: true
    properties:
      a:
        required: true
        type: number
      b:
        required: true
        type: string
