#%RAML 1.0 Library
types:
  Animal:
    additionalProperties: true
    properties:
      age:
        required: true
        type: integer
  Pet:
    additionalProperties: true
    properties:
      owner:
        required: true
        type: string
  Cat:
    type: object
    additionalProperties: true
    properties:
      age:
        required: true
        type: integer
      owner:
        required: true
        type: string
