#%RAML 1.0 Library
types:
  A:
    additionalProperties: true
    properties:
      a:
        required: true
        type: string
  B:
    additionalProperties: true
    properties:
      b:
        required: true
        type: integer
  C:
    additionalProperties: true
    properties:
      c:
        required: true
        type: any
  D:
    type: object
    additionalProperties: true
    properties:
      a:
        required: true
        type: string
      b:
        required: true
        type: integer
      c:
        required: true
        type: any
