#%RAML 1.0 Library
types:
  A:
    required: true
    type: string
  B:
    required: true
    type: integer
  C:
    required: true
    type: number
  D:
    additionalProperties: true
    properties:
      a:
        required: true
        type: string
      b:
        required: true
        type: integer
  E:
    additionalProperties: true
    properties:
      a:
        required: true
        type: string
      c:
        required: true
        type: number
  F:
    type: object
    additionalProperties: true
    properties:
      a:
        required: true
        type: string
      b:
        required: true
        type: integer
      c:
        required: true
        type: number
  G:
    anyOf:
      -
        additionalProperties: true
        properties:
          a:
            required: true
            type: string
          b:
            required: true
            type: integer
      -
        additionalProperties: true
        properties:
          a:
            required: true
            type: string
          c:
            required: true
            type: number
