#%RAML 1.0 Library

types:

  A: string
  B: integer
  C: number

  D:
    properties:
      a: A
      b: B

  E:
    properties:
      a: A
      c: C

  F:
    type:
      - D
      - E

  G: D | E