#%RAML 1.0 Library
types:
  A:
    type: string
  B:
    type: integer
  C:
    type: number
  D:
    additionalProperties: true
    properties:
      a:
        type: string
        required: true
      b:
        type: integer
        required: true
  E:
    additionalProperties: true
    properties:
      a:
        type: string
        required: true
      c:
        type: number
        required: true
  F:
    type: object
    additionalProperties: true
    properties:
      a:
        type: string
        required: true
      b:
        type: integer
        required: true
      c:
        type: number
        required: true
  G:
    anyOf:
      -
        additionalProperties: true
        properties:
          a:
            type: string
            required: true
          b:
            type: integer
            required: true
      -
        additionalProperties: true
        properties:
          a:
            type: string
            required: true
          c:
            type: number
            required: true
