#%RAML 1.0 DataType
additionalProperties: true
properties:
  name1?:
    required: true
    type: string
  name2:
    required: false
    type: string
  name3?:
    required: false
    type: string
  name4?:
    required: false
    type: string
