#%RAML 1.0 DataType
type: object
additionalProperties: true
properties:
  name1?:
    type: string
    required: true
  name2:
    required: false
    type: string
  name3?:
    type: string
    required: false
  name4?:
    required: false
    type: string