#%RAML 1.0 DataType
type: object
additionalProperties: true
properties:
  a:
    required: true
    type: string
  b:
    required: true
    anyOf:
      -
        type: number
      -
        type: string
