#%RAML 1.0 DataType
type: union
anyOf:
  -
    type: object
    additionalProperties: true
    properties:
      a:
        required: true
        type: string
  -
    type: object
    additionalProperties: true
    properties:
      b:
        required: true
        type: string
  -
    type: object
    additionalProperties: true
    properties:
      c:
        required: true
        type: string
  -
    type: object
    additionalProperties: true
    properties:
      d:
        required: true
        type: string
