#%RAML 1.0 DataType
type: object
additionalProperties: true
properties:
  a:
    required: true
    type: union
    anyOf:
      -
        type: datetime
      -
        type: integer
  b:
    required: true
    type: union
    anyOf:
      -
        type: number
      -
        type: string
