#%RAML 1.0
title: My API With Types
types:
  SomeType:
    type: object
    properties:
      some:
        type: string
  OtherType:
    type: object
    properties:
      other:
        type: string
  AnotherType:
    type: object
    properties:
      another:
        type: boolean
  UnionType:
    type:
      - SomeType | OtherType
      - AnotherType
/someEndpoint:
  post:
    body:
      application/json:
        type: UnionType
