#%RAML 1.0
title: Test Union
types:
  SomeType:
    properties:
      a:
        type: string
      b:
        type: integer
  OtherType:
    properties:
      c:
        type: number
      d:
        type: string
/someEndpoint:
  post:
    body:
      application/json:
        anyOf:
          -
            properties:
              a:
                type: string
              b:
                type: integer
          -
            properties:
              c:
                type: number
              d:
                type: string
