#%RAML 1.0
title: My API With Types
/someEndpoint:
  post:
    body:
      application/json:
        anyOf:
          -
            properties:
              some:
                type: string
              another:
                type: boolean
          -
            properties:
              other:
                type: string
              another:
                type: boolean
