#%RAML 1.0
title: My API With Types
types:
  SomeType:
    properties:
      some:
        type: string
  OtherType:
    properties:
      other:
        type: string
  AnotherType:
    properties:
      another:
        type: boolean
  UnionType:
    anyOf:
      -
        properties:
          some:
            type: string
          another:
            type: boolean
      -
        properties:
          other:
            type: string
          another:
            type: boolean
/someEndpoint:
  post:
    body:
      application/json:
        anyOf:
          -
            properties:
              some:
                type: string
              another:
                type: boolean
          -
            properties:
              other:
                type: string
              another:
                type: boolean
