#%RAML 1.0
title: New API
/someEndpoint:
  post:
    body:
      application/json:
        anyOf:
          -
            type: string
            description: some scalar with extra fields
            example: a string
          -
            type: string
