#%RAML 1.0
title: New API
types:
  UnionType:
    anyOf:
      -
        type: string
      -
        type: object
        (amf-recursive): amf://id#4
  ScalarType:
    type: string
    description: some scalar with extra fields
    example: a string
/someEndpoint:
  post:
    body:
      application/json:
        anyOf:
          -
            type: string
          -
            type: object
            (amf-recursive): amf://id#4
