#%RAML 1.0
title: New API
types:
  UnionType:
    type: integer
  SomeType:
    type: string
  OtherType:
    type: boolean | nil
/someEndpoint:
  post:
    body:
      application/json:
        type: integer
