#%RAML 1.0
title: New API
types:
  UnionType:
    anyOf:
      -
        anyOf:
          -
            type: string
          -
            type: boolean | nil
      -
        type: integer
  SomeType:
    anyOf:
      -
        type: string
      -
        type: boolean | nil
  OtherType:
    type: boolean | nil
/someEndpoint:
  post:
    body:
      application/json:
        anyOf:
          -
            anyOf:
              -
                type: string
              -
                type: boolean | nil
          -
            type: integer
