#%RAML 1.0
title: New API
types:
  UnionType:
    type: SomeType | OtherType
  SomeType:
    type: object
    properties:
      a:
        type: string
      b:
        type: integer
  OtherType:
    type: object
    properties:
      c:
        type: number
      d:
        type: boolean
/someEndpoint:
  post:
    body:
      application/json:
        type: UnionType
