#%RAML 1.0
title: New API

types:
  UnionType:
    type: SomeType | integer
  SomeType:
    type: object
    properties:
      a:
       type: string
      b:
       type: integer

/someEndpoint:
  post:
    body:
      application/json:
        type: UnionType