#%RAML 1.0
title: New API
/someEndpoint:
  post:
    body:
      application/json:
        anyOf:
          -
            properties:
              a:
                type: string
              b:
                type: integer
          -
            type: nil
