#%RAML 1.0
title: New API
types:
  OtherType:
    anyOf:
      -
        properties:
          a:
            type: string
          b:
            type: integer
      -
        type: nil
  SomeType:
    properties:
      a:
        type: string
      b:
        type: integer
/someEndpoint:
  post:
    body:
      application/json:
        anyOf:
          -
            properties:
              a:
                type: string
              b:
                type: integer
          -
            type: nil
