syntax = "proto3";

package all;

import "ref.proto";
import "google/protobuf/descriptor.proto";
import "google/protobuf/any.proto";

message MyOption {
  string a = 1;
  string b = 2;
}
message RequestMessage {
  string a = 1;
}
message Any {
  google.protobuf.Any message = 1;
  repeated google.protobuf.Any details = 2;
  map<string,google.protobuf.Any> metadata = 3;
}
message SearchRequest {
  bool bool_property = 1;
  string string_property = 2;
  bytes bytes_property = 3;
  double double_property = 4;
  fixed32 fixed32_property = 5;
  fixed64 fixed64_property = 6;
  sfixed32 sfixed32_property = 7;
  sfixed64 sfixed64_property = 8;
  float float_property = 9;
  int32 int32_property = 10;
  int64 int64_property = 11;
  sint32 sint32_property = 12;
  sint64 sint64_property = 13;
  uint32 uint32_property = 14;
  uint64 uint64_property = 15;
}
message ResponseMessage {
  string a = 1;
}
message ComplexMessage {
  map<string,SearchRequest> searches = 3;
  oneof oneOfProperty {
    string name = 18;
  }
  RootEnum something = 4;
  NestedMessage1.NestedMessage2 n3 = 10;
  .all.ComplexMessage.NestedMessage1 n4 = 11;
  reference.RefMessage reference = 15;
  repeated string complex_property = 1 [
    deprecated = true,
    packed = true
  ];
  string other_complex_property = 2 [(mystruct) = {  a:  "hello"}];
  option deprecated = true;
  message NestedMessage1 {
    string n1 = 1;
    NestedMessage2 n2 = 2;
    message NestedMessage2 {
      string nn1 = 1;
    }
  }
  enum enumProperty {
    UNIVERSAL = 0;
    WEB = 1;
    IMAGES = 2;
    LOCAL = 3;
    NEWS = 4;
    PRODUCTS = 5;
    VIDEO = 6;
  }
  reserved "reserved_2";
  reserved "reserved_3";
  reserved "reserved_1";
  reserved 50 to max;
  reserved 26;
  reserved 27;
  reserved 28 to 49;
  reserved 21 to 25;
  reserved 20;
}
enum RootEnum {
  SOMETHING = 0;
}
enum enumProperty {
  UNIVERSAL = 0;
  WEB = 1;
  IMAGES = 2;
  LOCAL = 3;
  NEWS = 4;
  PRODUCTS = 5;
  VIDEO = 6;
}
service Greeter {
  rpc PostExample(RequestMessage) returns (ResponseMessage) {
    option deprecated = true;
  }
  rpc PublishExample(stream RequestMessage) returns (ResponseMessage) {}
  rpc SubscribeExample(RequestMessage) returns (stream ResponseMessage) {}
  rpc PubSubExample(stream RequestMessage) returns (stream ResponseMessage) {}
  option deprecated = false;
}
extend google.protobuf.FieldOptions {
  MyOption mystruct = 5124;
}
option java_multiple_files = true;
option java_package = "io.grpc.examples.all";
option java_outer_classname = "AllExample";
option objc_class_prefix = "HLW";
