#%RAML 1.0
title: test API
types:
  T1:
    example:
      p1: "15"
      p2: "true"
      p3: 15
      p4: true
    properties:
      p1:
        type: string
      p2:
        type: string
      p3:
        type: number
      p4:
        type: boolean
