#%RAML 1.0
title: My API With Types
types:
  Initial_comments:
    maxProperties: 2
    properties:
      comment_id?:
        type: number
      initial_comments:
        type: string
      author?:
        type: string
    example:
      initial_comments: mm
      author: L
      comment_id: 666
    type: object
