#%RAML 1.0
title: World Music API
protocols:
  - http
baseUri: example.api.com/{version}
version: v1
traits:
  secured: !include secured/accessToken.raml
/songs:
  is:
    - secured
  get:
    (monitoringInterval): 30
    queryParameters:
      genre:
        description: filter the songs by genre
  post: {}
  /{songId}:
    get:
      responses:
        200:
          body:
            application/json:
              type: Song
            application/xml: |
              <?xml version="1.0" encoding="UTF-8"?>
              <xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
                elementFormDefault="qualified" attributeFormDefault="unqualified">
                <xs:element name="song">
                  <xs:complexType>
                    <xs:sequence>
                      <xs:element name="title" type="xs:string" />
                      <xs:element name="artist" type="xs:string" />
                    </xs:sequence>
                  </xs:complexType>
                </xs:element>
              </xs:schema>
annotationTypes:
  monitoringInterval:
    type: integer
uses:
  Songs: songs-library.raml
