#%RAML 1.0

title: positive test case for the JSON API profile

types:
  A:
    type: object
    properties:
      id: string
      type: string
      attributes:
        properties:
          a1: string
          a2: string

  B:
    type: object
    properties:
      id: string
      type: string
      attributes:
        properties:
          b1: string
          b2: string

/test1:
  post:
    headers:
      Content-type: string
      X-Authentication: string
    body:
      application/vnd.api+json:
        type: object
        properties:
          meta:
            type: object
    responses:
      415:
      406:

  get:
    headers:
      Content-type: string
    responses:
      200:
        headers:
          "Content-type": string
        body:
          application/vnd.api+json:
            type: object
            properties:
              data:
                properties:
                  id: string
                  type: string
                  attributes:
                    properties:
                      name: string
                      birth_date: string
                  relationships:
                    properties:
                      address:
                        properties:
                          data:
                            properties:
                              type: string
              links:
                properties:
                  self: string
                  related:
                    properties:
                      href: string
                      meta:
                        type: object
                        properties:
                          author: string
                          category: string

/test2:
  post:
    headers:
      Content-type: string
      X-Authentication: string
    body:
      application/vnd.api+json:
        type: object
        properties:
          errors:
            type: object
    responses:
      415:
      406:

/test3:
  post:
    headers:
      Content-type: string
      X-Authentication: string
    body:
      application/vnd.api+json:
        type: object
        properties:
          data:
            type: array
            items:
              properties:
                type: string
                attributes:
                  properties:
                    name: string
                    birth_date: string
                relationships:
                  properties:
                    address:
                      properties:
                        meta:
                          type: object
          included:
            type: array
            items: A

    responses:
      415:
      406:
