#%RAML 1.0

title: negative test case for the JSON API profile

/test0:
  post:
    body:
      application/json:
  get:
    responses:
      200:
        body:
          application/json:

/test1:
  post:
    body:
      application/vnd.api+json:
        type: object
        properties:
          a: string
  get:
    responses:
      200:
        body:
          application/vnd.api+json:
            type: object
            properties:
              b: integer
/test2:
  post:
    body:
      application/vnd.api+json:
        type: object
        properties:
          c: number

/test3:
  post:
    body:
      application/vnd.api+json:
        type: object
        properties:
          data:
            type: object
          errors:
            type: object

/test4:
  post:
    body:
      application/vnd.api+json:
        type: object
        properties:
          links:
            properties:
              lala: string

/test5:
  post:
    body:
      application/vnd.api+json:
        type: object
        properties:
          data:
            type: string

/test6:
  post:
    body:
      application/vnd.api+json:
        type: object
        properties:
          data:
            type: object

/test7:
  post:
    body:
      application/vnd.api+json:
        type: object
        properties:
          meta: string
          data:
            type: array
            items:
              type: object

/test8:
  get:
    headers:
      Content-type: string
    responses:
      200:
        headers:
          "Content-type": string
        body:
          application/vnd.api+json:
            type: object
            properties:
              data:
                properties:
                  id: string
                  type: string
                  attributes:
                    properties:
                      id: string
                      name: string
                      birth_date: string

/test9:
  get:
    headers:
      Content-type: string
    responses:
      200:
        headers:
          "Content-type": string
        body:
          application/vnd.api+json:
            type: object
            properties:
              data:
                properties:
                  id: string
                  type: string
                  attributes:
                    properties:
                      type: string
                      name: string
                      birth_date: string

/test10:
  get:
    headers:
      Content-type: string
    responses:
      200:
        headers:
          "Content-type": string
        body:
          application/vnd.api+json:
            type: object
            properties:
              data:
                properties:
                  id: string
                  type: string
                  attributes:
                    properties:
                      type: string
                      name: string
                      birth_date: string
                  relationships:
                    properties:
                      name:
                        type: object

/test11:
  get:
    headers:
      Content-type: string
    responses:
      200:
        headers:
          "Content-type": string
        body:
          application/vnd.api+json:
            type: object
            properties:
              data:
                properties:
                  id: string
                  type: string
                  attributes:
                    properties:
                      name: string
                      birth_date: string
                  relationships:
                    properties:
                      address:
                        properties:
                          data:
                            properties:
                              type: string
              links:
                properties:
                  self: number

/test12:
  get:
    headers:
      Content-type: string
    responses:
      200:
        headers:
          "Content-type": string
        body:
          application/vnd.api+json:
            type: object
            properties:
              data:
                properties:
                  id: string
                  type: string
                  attributes:
                    properties:
                      name: string
                      birth_date: string
                  relationships:
                    properties:
                      address:
                        properties:
                          data:
                            properties:
                              type: string
              links:
                properties:
                  related:
                    properties:
                      wadus: string

/test13:
  post:
    headers:
      Content-type: string
      X-Authentication: string
    body:
      application/vnd.api+json:
        type: object
        properties:
          data:
            type: array
            items:
              properties:
                type: string
                attributes:
                  properties:
                    name: string
                    birth_date: string
                relationships:
                  properties:
                    address:
                      properties:
                        meta:
                          type: object
          included:
            type: array
            items: string

/test14:
  post:
    headers:
      Content-type: string
      X-Authentication: string
    body:
      application/vnd.api+json:
        type: object
        properties:
          data:
            type: array
            items:
              properties:
                type: string
                attributes:
                  properties:
                    name: string
                    birth_date: string
                relationships:
                  properties:
                    address:
                      properties:
                        meta:
                          type: object
          included:
            type: array
            items:
              properties:
                attributes:
                  properties:
                    a: string
                    b: string
    responses:
      415:
      406: