#%RAML 1.0
title: Infer Level
/levels:
  /{level}:
    put:
      body:
        application/json:
          type: number
          minimum: 0
          maximum: 100
          format: int
          example: 80
    get:
      responses:
        "200":
          body:
            application/json:
              type: number
              minimum: 0
              maximum: 100
              format: int
              example: 80
    description: Entity representing a level
