#%RAML 1.0
title: test title
uses:
  lib: file://shared/src/test/resources/references/lib/lib.raml
  lib2: file://shared/src/test/resources/references/lib/lib.raml
  lib3: file://shared/src/test/resources/references/lib/lib.raml