#%RAML 1.0
title: test title
types:
  person: lib.Person
  person2: lib2.Person
  person3: lib3.Person
uses:
  lib: file://shared/src/test/resources/references/lib/lib-declaration.raml
  lib2: file://shared/src/test/resources/references/lib/lib-declaration.raml
  lib3: file://shared/src/test/resources/references/lib/lib-declaration.raml
