#%RAML 1.0 Overlay
usage: Spanish localization
extends: file://amf-cli/shared/src/test/resources/upanddown/cycle/raml10/banking-api/api.raml
/books:
  description: La colección de libros de la biblioteca
