- optionalParametersForAuthorizationSearch:
   queryParameters:
      clientType:
        type: string
        description: Specifies the calling application (PEGA|PORTAL|ETC)
        required: false
        example: CCMS
