#%RAML 1.0
title: rmit-system-api-sams-lb

traits:
  hasError:
    responses:
      500:
        body:
          application/json:
            example:
              id : anId,
              payload : "A payload message for the 500 response"

/students:
  /email-addresses:
    is: [hasError]
    get:
      responses:
        500:
          body:
            application/json:
              example:
                provider: AWS,
                payload:
                  errorDescription: A giant error description
