#%RAML 1.0
title: aTitle
baseUri: https://aUri
/thresholdnotifications:
  get:
    displayName: aDisplayName
    responses:
      200:
/remotewarnings:
  get:
    displayName: aDisplayName
    responses:
      200: