#%RAML 1.0
version: "1.0"
title: American Flights API
/flights:
  get:
    responses:
      "200":
        body:
          application/json:
            example: example[1].raml
            type: any
