#%RAML 1.0
title: api title
types:
  User:
    properties:
      firstname:
        type: string
      lastname:
        type: string
      age:
        type: number
    type: object
/top:
  post:
    body:
      application/json:
        type: User
        examples:
          no-errors:
            firstname: tato
            lastname: bores
            age: 66
          errors:
            firstname: tato
            lastname: bores
            age: twenty
