#%RAML 1.0
types:
  Human:
    properties:
      name: string
      description: string
      age: integer
  Person:
    type: Human
    properties:
      omnipotent: boolean
      address:
        properties:
          street: string
          number: integer
title: test types
description: empty api only for test types