#%RAML 1.0
title: API

baseUri: /some/base/uri

/levelzero:
  /level-one:
    displayName: One display name
    description: and this description!
  /another-level-one:
    displayName: some other display name
/another-levelzero:
  displayName: Root name