#%RAML 1.0
title: API

baseUri: /some/{one}/uri

baseUriParameters:
  one:
    description: One base uri param
/levelzero/some{two}:
  uriParameters:
    two:
      required: false
  /level-one:
    displayName: One display name
    description: and this description!
    get:
      title: Some title
      queryParameters:
        param1:
          description: Some descr
        param2?:
          type: string
    post:
      title: Some title
      description: Some description
      headers:
        Header-One:
          required: false