#%RAML 1.0
title: API

baseUri: /some/uri

/levelzero:
  /level-one:
    displayName: One display name
    description: and this description!
    get:
      displayName: Some title

      body:
        application/json:

      responses:
        200:
          description: 200 descr
          headers:
            Time-Ago:
              type: integer
        404:
          description: Not found!
          body:
            application/json: string
            application/xml: string