#%RAML 1.0
title: test

types:
  test1: |
    {
                "items": [
                    {"type": "integer"},
                    {"$ref": "#/items/0"}
                ]
    }

/ep1:
  get:
    responses:
      200:
        body:
          application/json:
            type: test1
            example: [1, 2]

/ep2:
  get:
    responses:
      200:
        body:
          application/json:
            type: test1
            example: [1, "foo"]