#%RAML 1.0
title: test title
baseUri: api.example.com/path
description: test description
version: "1.1"
(amf-termsOfService): terms of service
(amf-contact):
  url: contactUrl
  name: contactName
  email: contactEmail
documentation:
  -
    (amf-url): externalDocsUrl
    content: externalDocsDescription
    title: Home documentation
(amf-license):
  url: licenseUrl
  name: licenseName
mediaType:
  - application/yaml
protocols:
  - http
  - https
