#%RAML 1.0
title: Sample API
version: v1
protocols:
  - https
baseUri: api.sample.com/
/media:
  displayName: Media
  get: {}
  /search:
    displayName: Media Search
    get: {}
  /tags:
    displayName: Tags
    get: {}
    /search:
      displayName: Tag Search
      get: {}
