#%RAML 1.0
title: Prediction
version: v1.2
baseUri: 'https://www.googleapis.com/prediction/v1.2'
protocols:
  - HTTPS
description: Lets you access a cloud hosted machine learning service that makes it easy to build smart apps
(oas-tags-definition):
  - name: hostedmodels
  - name: training
annotationTypes:
  oas-tags-definition:
    type: array
    items:
      properties:
        name: string
        description?: string
        externalDocs?:
          properties:
            url: string
            description?: string
    allowedTargets: API
  oas-x-apiClientRegistration: any
  oas-x-logo: any
  oas-x-origin: any
  oas-x-preferred: any
  oas-x-providerName: any
  oas-x-serviceName: any
  oas-tags:
    type: 'string[]'
    allowedTargets: Method
  oas-externalDocs:
    properties:
      description?: string
      url: string
    allowedTargets:
      - API
      - Method
      - TypeDeclaration
  oas-info:
    properties:
      termsOfService?: string
      contact?:
        properties:
          name?: string
          url?: string
          email?: string
      license?:
        properties:
          name?: string
          url?: string
    allowedTargets: API
  oas-body-name:
    type: string
    allowedTargets: TypeDeclaration
(oas-info):
  (oas-x-apiClientRegistration):
    url: 'https://console.developers.google.com'
  (oas-x-logo):
    url: 'https://api.apis.guru/v2/cache/logo/https_www.google.com_images_icons_feature_predictionapi-64.png'
  (oas-x-origin):
    format: google
    url: 'https://www.googleapis.com/discovery/v1/apis/prediction/v1.2/rest'
    version: v1
  (oas-x-preferred): false
  (oas-x-providerName): googleapis.com
  (oas-x-serviceName): prediction
  contact:
    name: Google
    url: 'https://google.com'
(oas-externalDocs):
  url: 'https://developers.google.com/prediction/docs/developer-guide'
securitySchemes:
  Oauth2:
    type: OAuth 2.0
    settings:
      authorizationUri: 'https://accounts.google.com/o/oauth2/auth'
      accessTokenUri: ''
      authorizationGrants:
        - implicit
      scopes:
        - 'https://www.googleapis.com/auth/devstorage.full_control'
        - 'https://www.googleapis.com/auth/devstorage.read_only'
        - 'https://www.googleapis.com/auth/devstorage.read_write'
        - 'https://www.googleapis.com/auth/prediction'
    description: Oauth 2.0 authentication
/training:
  displayName: training
  '/{data}':
    displayName: '{data}'
    /predict:
      displayName: predict
      post:
        displayName: prediction.predict
        description: Submit data and request a prediction
        body:
          application/json:
            type: Input
            (oas-body-name): body
        responses:
          '200':
            body:
              application/json:
                type: Output
            description: Successful response
        securedBy:
          - Oauth2:
              scopes:
                - 'https://www.googleapis.com/auth/prediction'
      is:
        - alt
        - fields
        - key
        - oauthToken
        - prettyPrint
        - quotaUser
        - userIp
    uriParameters:
      data:
        description: mybucket/mydata resource in Google Storage
        required: true
        type: string
    put:
      displayName: prediction.training.update
      description: Add new data to a trained model
      body:
        application/json:
          type: Update
          (oas-body-name): body
      responses:
        '200':
          body:
            application/json:
              type: Training
          description: Successful response
      securedBy:
        - Oauth2:
            scopes:
              - 'https://www.googleapis.com/auth/prediction'
      (oas-tags):
        - training
    is:
      - alt
      - fields
      - key
      - oauthToken
      - prettyPrint
      - quotaUser
      - userIp
    get:
      displayName: prediction.training.get
      description: Check training status of your model
      responses:
        '200':
          body:
            application/json:
              type: Training
          description: Successful response
      securedBy:
        - Oauth2:
            scopes:
              - 'https://www.googleapis.com/auth/prediction'
      (oas-tags):
        - training
    delete:
      displayName: prediction.training.delete
      description: Delete a trained model
      responses:
        '200':
          description: Successful response
      securedBy:
        - Oauth2:
            scopes:
              - 'https://www.googleapis.com/auth/prediction'
      (oas-tags):
        - training
  post:
    displayName: prediction.training.insert
    description: Begin training your model
    body:
      application/json:
        type: Training
        (oas-body-name): body
    responses:
      '200':
        body:
          application/json:
            type: Training
        description: Successful response
    queryParameters:
      data:
        description: mybucket/mydata resource in Google Storage
        type: string
    securedBy:
      - Oauth2:
          scopes:
            - 'https://www.googleapis.com/auth/prediction'
    (oas-tags):
      - training
  is:
    - alt
    - fields
    - key
    - oauthToken
    - prettyPrint
    - quotaUser
    - userIp
/hostedmodels:
  displayName: hostedmodels
  '/{hostedModelName}':
    displayName: '{hostedModelName}'
    /predict:
      displayName: predict
      post:
        displayName: prediction.hostedmodels.predict
        description: Submit input and request an output against a hosted model
        body:
          application/json:
            type: Input
            (oas-body-name): body
        responses:
          '200':
            body:
              application/json:
                type: Output
            description: Successful response
        securedBy:
          - Oauth2:
              scopes:
                - 'https://www.googleapis.com/auth/prediction'
        (oas-tags):
          - hostedmodels
      is:
        - alt
        - fields
        - key
        - oauthToken
        - prettyPrint
        - quotaUser
        - userIp
types:
  Input:
    properties:
      input:
        properties:
          csvInstance:
            items: {}
            type: array
            required: false
        type: object
        required: false
  Output:
    properties:
      id:
        type: string
        required: false
      kind:
        default: 'prediction#output'
        type: string
        required: false
      outputLabel:
        type: string
        required: false
      outputMulti:
        items:
          properties:
            label:
              type: string
              required: false
            score:
              format: double
              type: number
              required: false
          type: object
        type: array
        required: false
      outputValue:
        format: double
        type: number
        required: false
      selfLink:
        type: string
        required: false
  Training:
    properties:
      id:
        type: string
        required: false
      kind:
        default: 'prediction#training'
        type: string
        required: false
      modelInfo:
        properties:
          classificationAccuracy:
            format: double
            type: number
            required: false
          meanSquaredError:
            format: double
            type: number
            required: false
          modelType:
            type: string
            required: false
        type: object
        required: false
      selfLink:
        type: string
        required: false
      trainingStatus:
        type: string
        required: false
  Update:
    properties:
      classLabel:
        description: The true class label of this instance
        type: string
        required: false
      csvInstance:
        description: The input features for this instance
        items: {}
        type: array
        required: false
traits:
  alt:
    queryParameters:
      alt:
        type: string
        description: Data format for the response.
        default: json
        enum:
          - json
  fields:
    queryParameters:
      fields:
        type: string
        description: Selector specifying which fields to include in a partial response.
  key:
    queryParameters:
      key:
        type: string
        description: 'API key. Your API key identifies your project and provides you with API access, quota, and reports. Required unless you provide an OAuth 2.0 token.'
  oauthToken:
    queryParameters:
      oauth_token:
        type: string
        description: OAuth 2.0 token for the current user.
  prettyPrint:
    queryParameters:
      prettyPrint:
        type: boolean
        description: Returns response with indentations and line breaks.
        default: true
  quotaUser:
    queryParameters:
      quotaUser:
        type: string
        description: 'Available to use for quota purposes for server-side applications. Can be any arbitrary string assigned to a user, but should not exceed 40 characters. Overrides userIp if both are provided.'
  userIp:
    queryParameters:
      userIp:
        type: string
        description: IP address of the site where the request originates. Use this if you want to enforce per-user limits.
