#%RAML 1.0
title: API
/test:
  get:
    body:
      application/json:
        type:
          type:
            anyOf:
              -
                items:
                  type: object
                  x-amf-recursive: file://amf-client/shared/src/test/resources/production/recursive-union.raml#/web-api/end-points/%2Ftest/get/request/application%2Fjson/any/schema
              -
                items:
                  type:
                    type: object
                    x-amf-recursive: file://amf-client/shared/src/test/resources/production/recursive-union.raml#/web-api/end-points/%2Ftest/get/request/application%2Fjson/any/schema
