#%RAML 1.0
title: API
/test:
  get:
    body:
      application/json:
        anyOf:
          -
            items:
              type: object
              x-amf-recursive: file://amf-client/shared/src/test/resources/production/recursive-union.raml#/declarations/array/SomeUnion/union/default-union
          -
            items:
              type: object
              x-amf-recursive: file://amf-client/shared/src/test/resources/production/recursive-union.raml#/declarations/array/SomeUnion/union/default-union
