#%RAML 1.0
title: Example API
resourceTypes:
  resourceType1:
    get:
      responses:
        200:
          body:
            application/json:
              type: a
/resource:
  type: resourceType1