#%RAML 1.0
title: recursive shapes in when merging traits
version: 1.0


traits:
  conformance:
    responses:
      200:
        body:
          application/json:
            type: <<typeName>>
  externalTrait: !include external-trait.raml

resourceTypes:
  some-rt:
    description: A collection resource
    usage: Use this to describe a resource that lists items
    get:
      description: Retrieve all items
    post:
      description: Add an item
      responses:
        201:
          headers:
            Location:
  externalResourceType: !include external-rt.raml
