#%RAML 1.0
title: My API With Types
types:
  Person:
    properties:
      name:
        type: string
    type: object
  EmailOwner:
    properties:
      email:
        type: string
    type: object
  Employee:
    type:
      - Person
      - EmailOwner
    properties:
      id:
        type: string
