#%RAML 0.8
---
title: Ticketing API
baseUri: http://ticketing/api/{version}
version: v1.0
mediaType: application/json

/tickets:
  get:
    description: Gets the specified tickets by the filters
    queryParameters:
      createdAfter:
        displayName: createdAfter
        type: date
        description: The filter for tickets created after a specific date and time.
        example: Mon, 06 Nov 1994 08:49:37 GMT
        required: true
    responses:
      200:
        description: A ticket object
        body:
          application/json:
            example: Example