#%Vocabulary 1.0

base: "http://a.ml/vocabularies/http#"

usage: HTTP APIs vocabulary for AMF

uses:
  shapes: ./shapes.raml
  doc: ./aml_doc.raml

external:
  schema-org: "http://schema.org/"
  hydra: "http://www.w3.org/ns/hydra/core#"
  shacl: "http://www.w3.org/ns/shacl#"
  security: "http://a.ml/vocabularies/security#"

classTerms:

  doc.DocumentationItemFragment:
    displayName: Documentation Item Fragment
    description: Fragment encoding documentation about a Web API
    extends: doc.Fragment

  doc.DataTypeFragment:
    displayName: Data Type Fragment
    description: Fragment encoding information about a payload data shape
    extends: doc.Fragment

  doc.NamedExampleFragment:
    displayName:  Named Example Fragment
    description: Fragment encoding information about a named example for an API endpoint
    extends: doc.Fragment

  doc.ResourceTypeFragment:
    displayName: Resource Type Fragment
    description: Fragment encoding information about an EndPoint graph template
    extends: doc.Fragment

  doc.TraitFragment:
    displayName: Trait Fragment
    description: Fragment encoding information about an operation graph template
    extends: doc.Fragment

  doc.AnnotationTypeDeclarationFragment:
    displayName: Annotation Type Declaration Fragment
    description: Fragment encoding information about an API spec extension
    extends: doc.Fragment

  doc.SecuritySchemeFragment:
    displayName: Security Scheme Fragment
    description: Fragment encoding information about a Security Scheme
    extends: doc.Fragment

  doc.Extension:
    displayName: API Spec Extension
    description: |
      An extension broadens a RAML API definition by adding to, or modifying aspects of its behavior and other functionality.
      An extension can be useful in separating a core, broadly-available API from layers of functionality available to
      more restricted audiences, for creating variants of an API for somewhat different purposes, or for specifying instance-specific nodes of an API, such as its service endpoint (URL) without altering its pure interface definition document.
    extends: doc.DocumentExtension

  doc.Overlay:
    displayName: API Spec Overlay
    description: |
      An overlay adds or overrides nodes of a RAML API definition while preserving its behavioral, functional aspects.
      Certain nodes of a RAML API definition specify the behavior of an API: its resources, methods, parameters, bodies, responses, and so on.
      These nodes cannot be changed by applying an overlay. In contrast, other nodes, such as descriptions or annotations,
      address concerns beyond the functional interface, such as the human-oriented descriptive documentation in some language,
      or implementation or verification information for use in automated tools. These nodes can be changed by applying an overlay.
    extends: doc.DocumentExtension

  schema-org.WebAPI:
    displayName: Web API
    description: Top level element describing a HTTP API
    extends: doc.RootDomainElement
    properties:
      - host
      - scheme
      - basePath
      - schema-org.termsOfService
      - schema-org.version
      - schema-org.provider
      - schema-org.license
      - schema-org.documentation
      - endpoint

  schema-org.Organization:
    extends: doc.DomainElement
    description: |
      The service provider, service operator, or service performer; the goods producer.
      Another party (a seller) may offer those services or goods on behalf of the provider.
      A provider may also serve as the seller.

  License:
    extends: doc.DomainElement
    description: License for the API

  Documentation:
    extends: doc.DomainElement
    description: Documentation associated to the API, stored externally.

  EndPoint:
    extends: doc.DomainElement
    displayName: End Point
    description: EndPoint in the API holding a number of executable operations
    properties:
      - path
      - hydra.supportedOperation

  hydra.Operation:
    extends: doc.DomainElement
    description: Action that can be executed using a particular HTTP invocation
    properties:
      - hydra.method
      - guiSummary
      - scheme
      - accepts
      - contentType
      - hydra.returns
      - hydra.expects

  hydra.Request:
    extends: doc.DomainElement
    description: Request information for an operation

  hydra.Response:
    extends: doc.DomainElement
    description: Response information for an operation
    properties:
      - statusCode

  Parameter:
    extends: doc.DomainElement
    description: Piece of data required or returned by an Operation
    properties:
      - hydra.required
      - binding

  Payload:
    extends: doc.DomainElement
    description: Encoded payload for a particular media-type
    properties:
      - mediaType

  security.SecurityScheme:
    displayName: Security Scheme
    description: Authentication and access control mechanism defined in an API
    properties:
      - security.settings
      - security.type

  security.Settings:
    displayName: Security Settings
    description: Settings for a security scheme

  security.OAuth1Settings:
    displayName: OAuth 1.0 Security Settings
    description: Security settings for OAuth 1.0
    extends: security.Settings
    properties:
      - security.tokenCredentialsUri
      - security.signature

  security.OAuth2Settings:
    displayName: OAuth 2.0 Security Settings
    description: Security settings for OAuth 2.0
    extends: security.Settings
    properties:
      - security.accessTokenUri
      - security.accessGrant
      - security.flow
      - security.scope

  security.ApiKeySettings:
    displayName: API Key Security Settings
    description: Security settings for a generic API Key security scheme.
    properties:
      - security.name
      - security.in

propertyTerms:

  schema-org.name:
    displayName: name
    description: The name of an domain entity
    range: string

  schema-org.description:
    displayName: description
    description: The description of an domain entity
    range: string

  host:
    displayName: host
    description: Host for the API
    range: string

  scheme:
    displayName: scheme
    description: URI scheme for the API protocol
    range: string

  basePath:
    displayName: base path
    description: Base path for end-points in the API
    range: string

  accepts:
    displayName: accepts
    description: Media-types accepted in a API request
    range: string

  contentType:
    displayName: content type
    description: Media types returned by a API response
    range: string

  schema-org.termsOfService:
    displayName: terms of service
    description: Terms and conditions when using the API
    range: string

  schema-org.version:
    displayName: version
    description: Version of the api
    range: string

  schema-org.provider:
    displayName: provider
    description: The API provider
    range: schema-org.Organization

  schema-org.url:
    displayName: url
    description: URL for a resource associated to a domain entity
    range: uri

  schema-org.email:
    displayName: email
    description: Electronic email address
    range: string

  schema-org.license:
    displayName: license
    description: License for the API
    range: string

  schema-org.documentation:
    displayName: documentation
    description: Documentation associated to the API
    range: Documentation

  endpoint:
    displayName: end-points
    description: End points defined in the api
    range: EndPoint

  path:
    displayName: path
    description: Path template for an endpoint
    range: License

  hydra.supportedOperation:
    displayName: supported operations
    description: Operations supported by an endpoint
    range: hydra.Operation

  hydra.method:
    displayName: method
    description: HTTP method required to invoke the operation
    range: string

  hydra.expects:
    displayName: expects
    description: Request information required by the operation
    range: hydra.Request

  hydra.returns:
    displayName: returns
    description: Response data returned by the operation
    range: hydra.Response

  statusCode:
    description: HTTP status code returned by a response
    range: string

  parameter:
    description: Type of data required or returned by an operation
    range: Parameter

  payload:
    description: Payload for a Request/Response
    range: Payload

  hydra.required:
    description: I this parameter required?
    range: boolean

  paramBinding:
    description: Location of the parameter in the request or response
    range: string

  mediaType:
    description: Media type for a payload
    range: string

  security:
    description: security schemes applied to an element in the API spec

  guiSummary:
    description: Description that can be used to provide information about an element of the spec in a graphical user interface
    extends: schema-org.description

  schema:
    description: Schema for an API spec Domain Element
    extends: doc.schema
    range: shapes.AnyShape

  header:
    description: parameter passed as a header to an operation or returned by a response
    extends: parameter
    range: Parameter

  queryString:
    description: Parameters passed in the query string of an operation as a data shape
    range: shapes.AnyShape

  examples:
    description: Examples for a particular domain element
    range: doc.Example

  security.type:
    displayName: security scheme type
    description: Textual indication of the kind of security scheme used
    range: string

  security.settings:
    displayName: security settings
    description: Settings for a particular security scheme
    range: security.Settings

  security.requestTokenUri:
    displayName: request token URI
    description: URI to request an OAuth security token
    range: uri

  security.authorizationUri:
    displayName: authorization URI
    description: OAuth authorization URI
    range: uri

  security.tokenCredentialsUri:
    displayName: token credential URI
    description: OAUth 1.0 token credential URI
    range: uri

  security.signature:
    displayName: signature
    description: OAuth 1.0 signature
    range: string

  security.accessTokenUri:
    displayName: access token URI
    description: OAuth 2.0 access token URI
    range: uri

  security.accessGrant:
    displayName: access grant
    description: OAuth 2.0 access grant
    range: string

  security.flow:
    displayName: authentication flow
    description: OAuth 2.0 authentication flow
    range: string

  security.scope:
    displayName: security scope
    description: OAuth 2.0 security scope
    range: string

  security.name:
    displayName: API key token name
    description: name of the API Key header or parameter
    range: string

  security.in:
    displayName: API key token binding
    description: binding of the security token in an API key security scheme
    range: string