#%RAML 1.0 Vocabulary

base: "http://raml.org/vocabularies/document#"

version: "1.0"

usage: Document Model vocabulary for AMF. The Document Model defines the basic modular units where domain descriptions can be encoded.

classTerms:

  BaseUnit:
    displayName: Base Unit
    description: |
      Base class for every single document model unit. After parsing a document the parser generate parsing Units.
      Units encode the domain elements and can reference other units to re-use descriptions.
    properties:
      - references

  Document:
    displayName: Document
    description: |
      A Document is a parsing Unit that encodes a stand-alone DomainElement and can include references to other DomainElements that reference from the encoded DomainElement.
      Since it encodes a DomainElement, but also declares references, it behaves like a Fragment and a Module at the same time.
      The main difference is that the Document encoded DomainElement is stand-alone and that the references declared are supposed to be private not for re-use from other Units
    extends: [Fragment, Module]

  Module:
    displayName: Module
    description: |
      A Module is a parsing Unit that declares DomainElements that can be referenced from the DomainElements in other parsing Units.
      It main purpose is to expose the declared references so they can be re-used
    extends: BaseUnit
    properties:
      - declares

  Fragment:
    displayName: Fragment
    description: A Fragment is a parsing Unit that encodes a DomainElement
    extends: BaseUnit
    properties:
      - encodes

  DocumentExtension:
    displayName: Document Extension
    description: A Document that extends a target document, overwritting part of the information or overlaying additional information.
    extends: Document

  ExternalFragment:
    displayName: External Fragment
    description: A fragment with including raw information that cannot be semantically processed, the information is encoded as a raw opaque textual description.

  SourceMap:
    displayName: Source Map
    description: |
      SourceMaps include tags with syntax specific information obtained when parsing a particular specification syntax like RAML or OpenAPI.
      It can be used to re-generate the document from the RDF model with a similar syntax

  DomainElement:
    displayName: Domain Element
    description: Base class for any element describing a domain model. Domain Elements are encoded into fragments
    properties:
      - sources

  RootDomainElement:
    displayName: Root Domain Element
    description: Domain element that is the entrypoint for a domain description. Domain elements encoded in Documents must be RootDomainElements.
    extends: DomainElement

propertyTerms:

  references:
    displayName: references
    description: |
      The references relationship makes public that some DomainElement within this Unit includes a DomainElement within other unit. It can be used to track references between units at the document level.
    range: DomainElement

  encodes:
    displayName: encodes
    description: The encodes relationship links a parsing Unit with the DomainElement from a particular domain the unit contains.
    range: DomainElement

  declares:
    displayName: declares
    description: |
      The declares relationship exposes a DomainElement as a re-usable unit that can be referenced from other units.
      URIs for the declared DomainElement are considered to be stable and safe to reference from other DomainElements.
    range: DomainElement

  extends:
    displayName: extends
    description: |
      Entity that is going to be extended overlaying or adding additional information
      The type of the relationship provide the semantics about thow the referenced and referencer elements must be combined when generating the domain model from the document model.
    range: Document

  sources:
    displayName: source
    description: Indicates that this parsing Unit has SourceMaps
    range: SourceMap