#%RAML 0.8
title: blabla
version: v1
baseUri: https://api.asdasd.com
mediaType: application/json
schemas:
  - metrics: !include schemas/metricNames.json
traits:
  - metrics:
      description: Return a list of known metrics and their value names for the given resource.
      queryParameters:
        name:
          description: Filter metrics by name
        page:
          description: Pagination index
          type: integer
      responses:
        200:
          body:

/applications:
    get:
      is: [ metrics ]