#%RAML 0.8
title: Traits test
/param:
  get:
    queryParameters:
      element:
        description: some description
        type: integer
      another:
        description: this has some description, right?
        type: string
