#%RAML 0.8
protocols:
  - http
baseUri: mocksvc.mulesoft.com/mocks/a31eb1d1-8ba1-4948-ad76-90c06340c8e7
title: Portal Application Management Service API
version: 2
/prehook/api:
  post:
    headers:
      Authorization:
        example: Bearer y6MpdQ3=
        type: string
    responses:
      200:
        description: OK, the original request can go ahead
        body: {}
    description: Requests requiring authentication.
    body: {}
