#%RAML 1.0 DataType
# Used by SubmitReturn (Request), Device, Plan
    type: object
    properties:
      device:
        required: false
        description: Device attached to this connection
        type: Device