#%RAML 1.0
title: test
version: 1.0
mediaType: application/json
baseUri: falsedomain.com/apis
types:
  A:
    properties:
      a: string
      b: integer

annotationTypes:
  annot:
    type:
      properties:
        lala: string
  simple:
    type: string
  arrAnot:
    type: array
    items: string
  clearanceLevel:
      properties:
        level:
          enum: [ low, medium, high ]
          required: true
        signature:
          pattern: "\\d{3}-\\w{12}"
          required: true
/test:
  (arrAnot): ["a", "b"]
  (clearanceLevel):
      level: high
      signature: 230-ghtwvfrs1itr
  get:
    description: an operation
    responses:
      200:
        (simple): other annotation
        (annot):
          lala: lolo
        body:
          application/json:
            type: A
            properties:
              c: string
