#%RAML 0.8
title: Dropbox API
version: 1
baseUri: https://api.domain.com/{version}
securitySchemes:
    - invalid:
        type: OAuth 2.0
        settings:
          authorizationUri: https://www.domain.com/1/oauth2/authorize
          accessTokenUri: https://api.domain.com/1/oauth2/token
          authorizationGrants: [ code, token, password ]
    - valid:
        type: OAuth 2.0
        settings:
          authorizationUri: https://www.domain.com/1/oauth2/authorize
          accessTokenUri: https://api.domain.com/1/oauth2/token
          authorizationGrants: [ code, token, owner ]
/users:
  get:
    securedBy: [invalid, valid, null]