#%RAML 1.0
version: refactor
baseUri: https://mocksvc.mulesoft.com/mocks/226604b1-d88b-4e3b-8a5c-4c299e70db6c
title: experience layer API
/customers:
  delete:
    responses:
      200: {}
  put:
    responses:
      200: {}
  get:
    responses:
      200:
        body:
          application/json:
            additionalProperties: true
            properties:
              firstName:
                type: string
                required: true
              lastName:
                type: string
                required: true
  description: |
    an individual customer within the collection
    of customerss
