#%RAML 1.0 Library

usage: |
  data types specific to the experience layer customer api

types:

  Customer:
    properties:
      firstName:
        type: string
      lastName:
        type: string

  CustomerResponse:
    type: Customer