#%Vocabulary 1.0
base: http://a.ml/vocabularies/test4#
vocabulary: test4
classTerms:
  D:
propertyTerms:
  c:
    displayName: property c
    description: c
    extends:
      - a
      - b
    range: string
  a:
    displayName: property a
    description: description
    range: uri
  b:
    displayName: property b
    description: b
    extends: a
    range: any
  d:
    displayName: property d
    description: d
    range: D
