#%RAML 1.0
title: invalid required override
types:
  Type1:
    properties:
      p1:
        type: string
      p2:
        type: string
  Type2:
    type: Type1
    properties:
      p2?:
        type: string
