#%RAML 1.0 Library
types:
  ObjectType:
    type: object
    properties:
      objProp1:
        type: string
        required: false
      objProp2:
        type: number
        required: false
usage: Data types and annotation types
