package amf.brokergroup.internal.convert

import amf.shapes.internal.convert.ShapesBaseClientConverter

trait BrokerGroupBaseClientConverter extends BrokerGroupBaseConverter with ShapesBaseClientConverter
