#%RAML 1.0 Overlay
extends: file://amf-client/shared/src/test/resources/org/raml/parser/overlays/annotations/master.raml
(another-scalar): overlay
/home:
  (object):
    lat: -34.6
    long: -58.4
annotationTypes:
  another-scalar:
    type: string
