#%RAML 1.0 Library
types:

  RestrictedObject:
    type: object
    additionalProperties: false

  User: Identifier

  Identifier:
    type: RestrictedObject
    properties:
      identifier:
        type: string