#%RAML 1.0

title: reduced air canada case mod

types:
  T1:
    type: T2
    properties:
      t1prop1:
        type: T3
  T2:
    type: object
    properties:
      t2prop1:
        type: string
  T3:
    type: object
    properties:
      t3prop1:
        type: string