#%RAML 1.0
title: test
types:
  A:
    type: array
    items: B
    examples:
      valid:
        - b: hey
          c:
            c: ho
        - b: lets
          c:
            c: go
            a:
              - b: test
      invalid:
        - b: 1
          c:
            c: 1
        - b: 2
          c:
            c: 3
            a:
             - b: 4
  B:
    properties:
      b: string
      c?: C
    examples:
      valid:
        b: hey
        c:
          c: ho
          a:
            - b: hey
            - b: ho
      invalid:
        b: 2
        c:
          c: 3
          a:
            - b: 4
  C:
    properties:
      c: string
      a?: A
    examples:
      valid:
        c: hey
        a:
          - b: hey
          - b: ho
            c:
              c: lets go
      invalid:
        c: 1
        a:
          - b: 2
          - b: 3
            c:
              c: 4
