#%RAML 1.0
title: api
version: 1.0
resourceTypes:
  rt1:
    get:
      is: [ <<trait1>>: {<<param>>: <<value>>}]
traits:
  myTrait:
    <<key>>:
/e1:
  type:
    rt1:
      trait1: myTrait
      param: key
      value: description
/e2:
  type:
      rt1:
        trait1: myTrait
        param: key
        value: iAmNotATraitProperty