#%RAML 1.0 Library
title: some title
types:
  t: string
securitySchemes:
  ss:
    type: Basic Authentication
usage: Some usage
resourceTypes:
  rt:
    description: the resource type
traits:
  ts:
    description: the trait
annotationTypes:
  ann: string