#%RAML 1.0
version: v1
title: conterparty

types:
  Conterparty: !include conterparty.raml

/conterparty:
  get:
    responses:
      200:
        body:
          application/json:
            type: Conterparty
  /{ID}:
    get:
      responses:
        200:
          body:
            application/json:
              type: Conterparty