#%RAML 1.0 Extension
extends: file://amf-client/shared/src/test/resources/org/raml/parser/extensions/simple-properties/examples/master.raml
types:
  User:
    examples:
      pepo:
        name: pipo
        age: 77
      cacho:
        name: cacho
        age: 55
    type: object
