#%RAML 1.0 Library

usage: Common traits for the HTTP API

traits:
  pageable: !include pageable.raml
  sortable: !include sortable.raml
  contentCacheable: !include content-cacheable.raml
  partial: !include partial.raml
  