#%RAML 1.0 DocumentationItem
title: SPI Viewer API Head Line
content: |
  - The SPI Viewer API is an application that retrieves instrumentation data from the SPI application and provides them to the engineers in the plants.