#%RAML 1.0 DocumentationItem
title: SPI Viewer API Description
content: |
  - **SmartPlant Instrumentation** or **SPI** is an application introduced by Intergraph and it was formerly known as **INtools**. The software acts as a single instrumentation source that is used in the Engineering Projects within ExxonMobil. It helps in accessing and updating the instruments used for different tasks and ensures that the consistency is maintained in the project.
  
  - Today on ExxonMobil, when technicians have to perform maintenance, they have ready-made work orders in their system. The work order has to contain all information they needed for the job. Some of the information is kept in SPI inside the specification sheet, and to access it, the technician has to:
  
    - Log on to the Citrix server.
    - Launch  SPI application.
    - Search  for the instrument tag and generate specification sheet. 

  - Unfortunately, SPI is not the most user-friendly application and the technician spends too much time to retrieve the required data.

  - The SPI API Viewer is an application programming interface that facilitates the delivery of instrumentation data to the end user. It connects directly to the SPI database through MuleSoft tool and retrieves the information from the specification sheet, according to the plant, area, unit and component being searched.

  - With the SPI API Viewer, the developer will be able to extract the instrumentation information from SPI and provide it in a web application.
 