#%RAML 1.0 Trait
description: This trait represents API behavior for a 404 response in the Promotions API.


responses:
  404:
    body:
      application/json:
        type: ApiStandards.ErrorResponse