#%RAML 1.0 NamedExample
value: 
  region: uswest1
  csr: -----BEGIN CERTIFICATE REQUEST-----\nMIIDzDCCAragAwIBAgIUOd0ukLcjH43TfTHFG9qE0FtlMVgwCwYJKoZIhvcNAQEL\n...\numkqeYeO30g1uYvDuWLXVA==\n-----END CERTIFICATE REQUEST-----\n
  type: RemoteRuntime
  agentInfo:
    muleVersion: 3.8.1
    agentVersion: 2.7

  