#%RAML 1.0
title: Test Union
/someEndpoint:
  post:
    body:
      application/json:
        anyOf:
          -
            type: object
            additionalProperties: true
            properties:
              a:
                type: string
                required: true
              b:
                type: integer
                required: true
          -
            type: object
            additionalProperties: true
            properties:
              c:
                type: number
                required: true
              d:
                type: string
                required: true
