#%RAML 1.0
title: My API With Types
types:
  SomeType:
    type: object
    additionalProperties: true
    properties:
      some:
        type: string
        required: true
  OtherType:
    type: object
    additionalProperties: true
    properties:
      other:
        type: string
        required: true
  AnotherType:
    type: object
    additionalProperties: true
    properties:
      another:
        type: boolean
        required: true
  UnionType:
    anyOf:
      -
        type: object
        additionalProperties: true
        properties:
          some:
            type: string
            required: true
          another:
            type: boolean
            required: true
      -
        type: object
        additionalProperties: true
        properties:
          other:
            type: string
            required: true
          another:
            type: boolean
            required: true
/someEndpoint:
  post:
    body:
      application/json:
        anyOf:
          -
            type: object
            additionalProperties: true
            properties:
              some:
                type: string
                required: true
              another:
                type: boolean
                required: true
          -
            type: object
            additionalProperties: true
            properties:
              other:
                type: string
                required: true
              another:
                type: boolean
                required: true
