#%RAML 1.0
title: New API

types:
  SomeType:
    type: object
    properties:
      a: string
      b: integer
  OtherType:
    type: SomeType?


/someEndpoint:
  post:
    body:
      application/json:
        type: OtherType