#%RAML 1.0
title: New API
types:
  SomeType:
    description: some description
    type: string | nil
/someEndpoint:
  post:
    body:
      application/json:
        description: some description
        type: string | nil
