#%RAML 1.0
title: New API
types:
  UnionType:
    type: SomeType | integer
  SomeType:
    type: object
    additionalProperties: true
    properties:
      a:
        type: UnionType
        required: false
      b:
        type: integer
        required: true
/someEndpoint:
  post:
    body:
      application/json:
        type: SomeType | integer
