#%RAML 1.0
title: Pets API

types:
  Pet:
    type: object
    discriminator: type
    discriminatorValue: true
    properties:
      type: integer
  Pet2:
    type: object
    discriminator: type
    discriminatorValue: true # valid
    properties:
      type: boolean
