#%RAML 1.0
title: api
description: this is a description
types:
  Parent:
    description: this is a description
    type: object
    properties:
      type:
        required: true
        example: parent-example
        description: this is a description
        type: ChildType
  ChildType:
    example: child-example
    description: this is a description
    type: string
