#%RAML 1.0
title: simple object
types:
  root:
    properties:
      name:
        type: string
      friends: Friend[]
    additionalProperties: false
  Friend:
    properties:
      name:
        type: string
    type: object
/res:
  get:
    body:
      application/xml:
        type: root
        example:
          value: <root> <name>robert</name> <my-custom-xml>with-custom-value</my-custom-xml> </root>
