queryParameters: 
  all: 
    description: True to show notifications marked as read.
    type: boolean
  participating: 
    description: |
      True to show only notifications in which the user is directly participating
      or mentioned.
    type: boolean
