#%RAML 1.0 Trait
queryParameters: 
  fromDate:
    description: from Date
    type: string
    example: 2016-06-06 19:58:45
    required: true
    pattern: ^\d\d\d\d-(0?[1-9]|1[0-2])-(0?[1-9]|[12][0-9]|3[01]) (0[0-9]|1[0-9]|2[0-3]):([0-9]|[0-5][0-9]):([0-9]|[0-5][0-9])$
  
  toDate:
    description: to Date
    type: string
    example: 2016-06-06 19:59:00
    required: true
    pattern: ^\d\d\d\d-(0?[1-9]|1[0-2])-(0?[1-9]|[12][0-9]|3[01]) (0[0-9]|1[0-9]|2[0-3]):([0-9]|[0-5][0-9]):([0-9]|[0-5][0-9])$
  
  countryCode:
    description: Universal ISO Country Code
    type: string
    maxLength: 3
    example: THA
    required: true
    
  appType:
    description: Type of POS application
    enum: [EPOS, VIKRANT]
    type: string
    maxLength: 20
    example: EPOS
    required: false
  