#%RAML 1.0
title: Basic servers
baseUri: https://{username}.gigantic-server.com:{port}/{basePath}
(serverDescription): The production API server
baseUriParameters:
  username:
    description: this value is assigned by the service provider, in this example `gigantic-server.com`
    default: demo
  port:
    default: 8443
    enum:
      - 8443
      - 443
  basePath:
    default: v2
version: 0.1
