#%RAML 1.0
title: Amazon S3 REST API
baseUri: https://{basic}.amazon.{withPattern}.com/{object}
baseUriParameters:
  basic:
    description: The name of the bucket
  withPattern:
    description: The name of the bucket
    pattern: "[0-9|-]+"
  object:
    properties:
      base:
        type: string
      path:
        type: string
version: "1"
