#%RAML 1.0
title: API
version: 1.0

/endpoint:
  get:
    responses:
      200:
        body:
          application/json:
            type: object
            properties:
              name:
                type: string
                required: yes #should be 'true'
              lastName: string


            example: !include example.json