#%RAML 1.0
title: asd
version: 12
types:
  a:
    type: object
    properties:
      b: string
      c: string
      d: string
  ar:
    type: array
    items:
      type: a
    example: [b: "hello world", c: "hello world", d: "hello world"]