#%RAML 1.0 DocumentationItem
title: Customer
content: |
  Retrieves and manipulates customers.  In particular:
  - Retrieve all customers
  - Add a new customer
  - Delete a customer
  - Update a customer
  - Retrieve the details of a customer