#%RAML 1.0
baseUri: https://mocksvc.qax.mulesoft.com/mocks/39429d61-eacb-42ab-ac0a-a46779c49a1e #
title: notification service api
version: 1.0
types:
  substitution:
    type: object
    properties:
      key:
        type: string
        required: false
      value:
        type: string
        required: true
  recipientslist:
    type: object
    properties:
      substitution:
        type: substitution
        required: false
      email:
        type: string
        required: true
        displayName: "Email Address"
        pattern: ^[_a-z0-9-]+(\.[_a-z0-9-]+)*@[a-z0-9-]+(\.[a-z0-9-]+)*(\.[a-z]{2,4})$
      type:
        type: string
        displayName: "Email Type"
        enum: [ "TO","CC","BCC" ]
  Notification:
   properties:
    recipients:
      type: recipientslist[]
      required: true
      displayName: Recipients
      minItems: 1
    substitutionlist:
      required: false
      type: array
      items: substitution
    another:
      required: true
      type: array
      items: integer
    other:
      required: false
      type: string[]

/notifications/emails:
  post:
    body:
      application/json:
        type: Notification
        example: |
          {
            "another": [
               1,
               2
            ],
            "recipients": [
              {
                  "email": "test@test.com",
                  "type": "TO"
              }
            ]
          }
    responses:
      200:
        body:
          application/json:
            example: |
              {
              "status":"success"
              }