#%RAML 1.0
title: declared type

types:
  Person:
    properties:
      name: string
      lastName: string

/endpoint:
  get:
    body:
      application/json:
        type: Person
        example:
          name: 5
          lastName: 6
  post:
      body:
        application/json:
          type: Person
          example:
            name: 5
            lastName: 6
