#%RAML 1.0
title: Some API

types:
  OtherCustomType:
    type: number
    minimum: 2.4
    maximum: 5.3
    examples:
      bad1: 2
      bad2: 2.0
      bad3: 2.3
      bad4: 5.4
      bad5: 6.0
      bad6: 6
