#%RAML 1.0
title: Some API

types:
  OtherCustomType:
    type: number
    minimum: 2.5
    maximum: 5.3
    examples:
      good1: 3
      good2: 3.0
      good3: 2.5
      good4: 5
      good5: 5.0
      good6: 5.3
