#%RAML 1.0

title: Twilio API
version: 2010-04-01
baseUri: https://api.com

types:
  SomeType:
    type: string
    examples:
      validInt1: 1
      validInt2: +14158675309
      validBoolean: true
      validNumber: 3.5
      validDate: 2002-12-10
