#%RAML 1.0
title: asyncCompletion_process
version: 1.0
baseUri: https://mocksvc.mulesoft.com/mocks/f390ebfc-8884-4b22-a593-62c2131ff1bc/asyncStatus
description: handles async completion logistics

types:
  OtherType:
    properties:
      theString: integer
    example:
      theString: 3