#%RAML 1.0 Library
resourceTypes:
  resource:
    get:
      body:
        application/json:
          type: <<typeParam>>

traits:
  response:
    body:
      application/json:
        type: <<typeParam>>

