#%RAML 1.0
title: Device Fraud Orchestration Service
version: v1

types:
  closedShapeType:
    type: object
    additionalProperties: false
    properties:
      payment:
        type: string

  openShape:
    type: object
    properties:
      order:
        type: string

  unionShape:
    type: closedShapeType | openShape


/events:
  post:
    body:
      application/json:
        type: unionShape