#%RAML 1.0 NamedExample
title: Area Example
value:
  areaId: 1672829
  name: Gas Conditioning Plant
  plantId: 1
  units: 
    - #item 1
      unitId: 1672830
      name: gc GCP
      areaId: 1672829
      plantId: 1