#%RAML 1.0 NamedExample
title: Component Example

value:
  componentId: 2177658 
  name:  gcTW   -1446 
  componentService: GC921B WASTE HTR STACK TEMP 
  specificationSheet:
      specificationSheetId: 1
      name: Component 1
      componentId: 1
    #GENERAL
      type: None
      tagNumber: csPI -3877
      service: CD501 PURGE AIR
      PID: 214-10647
      location: None
      areaClassification: None
      hazAreaCert: None
      certificationNumber: None
      poNumber: None
      itemNumber: 0
      lineNumber: 50-15P-1-50310
    #PROCESS CONDITIONS
      fluidName: None
      fluidPhase: None
      operPressure: None
      operTemperature: 0
      pulsation: 0
      designPressure: 0
      designTemperature: 0
      corrosiveCompounds: None
    #GAUGE
      manufacturer: None
      model: None
      gaugeType: PRESSURE GAUGE
      calibrationRange: 0
      figureInterval: None
      minorGraduation: None
      dialSize: 0
      dialColor: None
      mounting: None
      caseMaterial: None
      ringConstruction: None
      ringMaterial: None
      blowOutProtection: None
      lensMaterial: None
      elementType: None
      elementMaterial: None
      socketMaterial: None
      movementMaterial: None
      processConnectionSize: None
      processConnectionLocation: None
      nominalAccuracy: None
      overrangeProtection: None
      liquidFilled: None
      enclosureProtection: None
      complyNACEMR0175Standard: None
      remarks: None
    #DIAPHRAGM SEAL
      diaphragmSealType: None
      diaphragmSealProcessConnection: None
      diaphragmMaterial: None
      bottomHousingMaterial: None
      fillFluid: None
      capillaryLength: None
      capillaryMaterial: None
      flushingConnection: None
      topHousingMaterial: None
      connectionToInstrument: None
    #GAUGE SAVER
      diaphragmSealModelNumber: 0
      gaugeSaverBodyTrimMaterial: None
      processXGaugeConnection: None
      gaugeValveModelNumber: 0
    #SIPHON
      siphonType: None
      siphonMaterial: None
      valveXGaugeConnection: None
      siphonModelNumber: 0
    #MANIFOLD
      manifoldType: None
      manifoldBodyTrimMaterial: None
      manifoldProcessConnection: None
      modelNumber: 0
    #OPTIONS
      snubber: None
      optionsMaterial: None
      snubberModelNumber: 0

      notes: None