#%RAML 1.0 NamedExample
title: Plant Example

value:
  plantId: 1
  name: Longford
  city: South Gippsland
  state: Victoria
  country: Australia
  areas:
    - #item 1
      areaId: 1672829
      plantId: 1
      name: Gas Conditioning Plant