#%RAML 1.0 NamedExample
title: Unit Example

value:
  unitId: 1672830
  name: gc GCP
  plantId: 1
  areaId: 1672829
  components:
    - #item 1
      componentId: 2177658 
      name: gcTW   -1446 
      componentService: GC921B WASTE HTR STACK TEMP 