#%RAML 1.0 Trait
    responses:
      200:
        body:
          application/json:
            type: object
            properties:
              total: number
              <<pagedCollectionName>>:  <<collectionType>>[]
            example: <<collectionExample>>