#%RAML 1.0 Trait
    responses:
      406:
        description: !include ../../patterns/faults/documentation/406-description
        body:
          application/json:
            type: !include ../../types/platformfault.raml
            example: !include ../../patterns/faults/406.json