#%RAML 1.0 Trait
    responses:
      429:
        description: !include ../../patterns/faults/documentation/429-description
        body:
          application/json:
            type: !include ../../types/platformfault.raml
            example: !include ../../patterns/faults/429.json