#%RAML 1.0
title: test
description: testDescription
baseUri: http://api.example.com/path
protocols:
  - http
  - https
mediaType: application/yaml
version: 1.1
(amf-termsOfService): terminos
(amf-contact):
    url: urlContacto
    name: nombreContacto
    email: mailContacto
(amf-license):
    url: urlLicense
    name: nameLicense
documentation:
  - (amf-url): urlExternalDocs
    content: descriptionExternalDocs