#%RAML 1.0
types:
  Person:
    properties:
      name: string
      description: string
      age: integer
      address:
        properties:
          street: string
          number: integer
          document:
            type: object
          lastName:
            type: string
title: test title
description: test description
mediaType:
  - application/yaml
version: 1.1
(amf-termsOfService): terms of service
protocols:
  - http
  - https
/level-zero:
  displayName: One display name
  description: and this description!
  get:
    displayName: Some title
    queryParameters:
      param1:
        description: Some descr
        type: object
        properties:
          name: string
          lastName: string
          address:
            properties:
              city: string
              postal: integer
      param2?:
        type: string
      param3:
        description: typeless
    headers:
      Header-One:
        required: false
        type: string
        xml:
          attribute: true
          prefix: pref
          name: Xml-name
          namespace: xsd
      header-two:
        type: object
        properties:
          number: integer
    body:
      application/raml: string
      application/json:
        type: object
        properties:
          howmuch: integer
    responses:
      200:
        body:
          application/json:
            type: object
            properties:
              invented: string
          application/xml: string
      404:
        body: integer

/scalar_array:
  get:
    displayName: scalar_array
    body:
      application/json:
        type: array
        displayName: scalar_array
        minItems: 3
        maxItems: 10
        uniqueItems: true
        items:
          type: string

/object_array:
  get:
    displayName: object_array
    body:
      application/json:
        displayName: object_array
        type: array
        items:
          type: object

baseUri: api.example.com/path