#%RAML 1.0
traits:
  master:
    description: Master description
  slave:
    description: Slave description
/master:
  get:
    description: Master description
title: overlay
description: some overlaid description
