#%RAML 1.0 Vocabulary

base: "http://mulesoft.com/vocabularies/muleconfig#"

dialect: ConfigurationProperties

version: 1.0

usage: This vocabulary defines the vision of how configuration values can be injected/customized in a mule artifact (application, domain, policy, etc). Specific features will be targeted to an specific runtime release.

external:
  schema-org: "http://schema.org/"
  raml-doc: "http://raml.org/vocabularies/doc#"

classTerms:

  MuleConfig:
    displayName: Mule Configuration
    description: Set of properties for a Mule application
    extends: raml-doc.RootDomainElement
    properties:
      - schema-org.name
      - schema-org.description
      - timeout
    syntax:
      displayName: schema-org.name
      description: schema-org.description
      timeouts: timeout

  Timeouts:
    displayName: Timeouts Configuration
    description: Different types of timeouts for a Mule application
    extends: raml-doc.DomainElement
    properties:
      - http-request-timeout
      - http-listener-timeout
    syntax:
      httpRequestTimeout:
        term: http-request-timeout
        mandatory: true
      httpListenerTimeout:
        term: http-listener-timeout
        default: 100

propertyTerms:

  timeout:
    displayName: timeout
    description: Timeouts associated to this configuration
    range: Timeouts

  http-request-timeout:
    displayName: HTTP External Requests Timeout
    description: The timeout to use for HTTP requests made to external services
    range: integer

  http-listener-timeout:
    displayName: HTTP client timeout
    description: The timeout to use by HTTP clients
    range: integer
