#%RAML 1.0 Dialect

dialect: Validation Profile
version: 1.0

usage: Dialect to describe validations over RAML documents
uses:
  dlib: dialect_lib.raml
external:
  h: http://hello.org/#
nodeMappings:

  functionConstraintNode: dlib.functionConstraintNode
  propertyConstraintNode: dlib.propertyConstraintNode
  functionValidationNode: dlib.functionValidationNode
  shapeValidationNode: dlib.shapeValidationNode
  queryValidationNode:
     !extends : !include queryNode.raml
     mapping:
       hello:
         propertyTerm: h.name
         range: string
  profileNode: dlib.profileNode


raml:
  fragments:
    encodes:
      Validation: queryValidationNode

  module:
    declares:
      validations: queryValidationNode

  document:
    encodes: profileNode