#%RAML 1.0 Dialect

dialect: Validation Profile
version: 1.0

usage: Dialect to describe validations over RAML documents


external:
  schema-org: "http://schema.org/"
  shacl: "http://www.w3.org/ns/shacl#"
  validation: "http://raml.org/vocabularies/amf-validation#"
nodeMappings:

  functionConstraintNode:
    classTerm: shacl.JSConstraint
    mapping:
      message:
        propertyTerm: shacl.message
        mandatory: true
        range: string
      code:
        propertyTerm: validation.jsCode
        range: string
        pattern: '^function\(.+\)\s*\{.+\}$'
      libraries:
        propertyTerm: shacl.jsLibrary
        range: string
        allowMultiple: true
      functionName:
        propertyTerm: shacl.jsFunctionName
        range: string

  propertyConstraintNode:
    classTerm: shacl.PropertyShape
    mapping:
      message:
        propertyTerm: shacl.message
        mandatory: true
        range: string
      name:
        propertyTerm: validation.ramlPropertyId
        mandatory: true
        range: string
      pattern:
        propertyTerm: shacl.pattern
        range: string
      maxCount:
        propertyTerm: shacl.maxCount
        range: number
      minCount:
        propertyTerm: shacl.minCount
        range: number
      minExclusive:
        propertyTerm: shacl.minExclusive
        range: number
      maxExclusive:
        propertyTerm: shacl.maxExclusive
        range: number
      minInclusive:
        propertyTerm: shacl.minInclusive
        range: number
      maxInclusive:
        propertyTerm: shacl.maxInclusive
        range: number
      in:
        propertyTerm: shacl.in
        allowMultiple: true
        range: string

  shapeValidationNode: !include shapeValidationNode.raml
  profileNode: !include profileNode.raml


raml:

  module:
    declares:
      validations: shapeValidationNode

  fragments:
    encodes:
      Validation: shapeValidationNode


  document:
      encodes: profileNode
