#%Dialect 1.0

dialect: Configuration
version: 0.3


external:
  cfg: http://a.ml/vocabularies/cfg#

documents:
  root:
    encodes: ConfigurationNode

nodeMappings:

  ConfigurationNode:
    classTerm: cfg.Configuration
    mapping:
      assets:
        propertyTerm: cfg.configuredAsset
        allowMultiple: true
        typeDiscriminatorName: assetType
        typeDiscriminator:
          VDPTable: VDPAssetNode
          CSMSecret: CSMAssetNode
        range:
          - VDPAssetNode
          - CSMAssetNode

  VDPAssetNode:
    classTerm: cfg.VDPAsset
    mapping:
      file:
        propertyTerm: cfg.fileName
        range: string
        mandatory: false
      groupId:
        propertyTerm: cfg.gavGroup
        range: string
        mandatory: false
      artifactId:
        propertyTerm: cfg.gavArtifact
        range: string
        mandatory: false
      version:
        propertyTerm: cfg.version
        range: string
        mandatory: false
      classifier:
        propertyTerm: cfg.classifier
        range: string
        mandatory: false
      packaging:
        propertyTerm: cfg.packaging
        range: string
        mandatory: true

  CSMAssetNode:
    classTerm: cfg.CSMAsset
    mapping:
      file:
        propertyTerm: cfg.fileName
        range: string
        mandatory: false
      type:
        propertyTerm: cfg.type
        range: string
        mandatory: false
      version:
        propertyTerm: cfg.version
        range: string
        mandatory: false
      secretGroup:
        propertyTerm: cfg.secretGroup
        range: string
        mandatory: false
      secretType:
        propertyTerm: cfg.secretType
        range: string
        mandatory: false
      secretId:
        propertyTerm: cfg.secretId
        range: string
        mandatory: false
      packaging:
        propertyTerm: cfg.packaging
        range: string
        mandatory: false