#%RAML 1.0
title: My API With Types
types:
  Person:
    properties:
      name:
        type: string
    type: object
  EmailOwner:
    properties:
      address:
        type: string
    type: object
  Employee:
    type:
      - Person
      - EmailOwner
    properties:
      id:
        type: string
  Warrior:
    minProperties: 3
    maxProperties: 5
    properties:
      name:
        type: string
      age:
        type: number
    type: object
  Mage:
    minProperties: 1
    maxProperties: 2
    properties:
      name:
        type: string
      age:
        type: number
      power:
        type: string
    type: object
