#%RAML 1.0 Library

usage: Data shapes for the HTTP API

types:
  MonetaryAmountData:
    properties:
      value: number
      currency: string

  DurationData:
    properties:
      value: string

  RepaymentSpecificationData:
    properties:
      down_payment: MonetaryAmountData
      payment_frequency: number
      number_payments: integer
      payment_amount: MonetaryAmountData
      early_payment_penalty: MonetaryAmountData

  AddressData:
    properties:
      address_country: string
      address_locality: string
      address_region: string
      postal_code: string
      street_address: string

  NewCustomerData:
    type: AddressData
    properties:
      lei: string
      tax_id: string
      email: string
      telephone: string

  NewOrganizationData:
    type: NewCustomerData
    properties:
      name: string
      vat_id: string

  NewPersonData:
    type: NewCustomerData
    properties:
      title?:
        type: string
        enum: [mr, mrs, ms, dr]
      given_name: string
      family_name: string
      gender:
        type: string
        enum: [female, male]
      vat_id?:
      birth_date: date-only


  CustomerData:
    discriminator: type
    properties:
      type: string
      lei: string
      tax_id: string
      email: string
      address: AddressData

  OrganizationData:
    discriminatorValue: Organization
    type: CustomerData
    properties:
      id: string
      name: string
      vat_id: string


  PersonData:
    discriminatorValue: Person
    type: CustomerData
    properties:
      id: string
      title?:
        type: string
        enum: [mr, mrs, ms, dr]
      given_name: string
      family_name: string
      gender:
        type: string
        enum: [female, male]
      vat_id?: string
      birth_date: date-only
      death_date?: date-only


  CustomerPatchData:
    properties:
      lei?: string
      tax_id?: string
      email?: string
      title?:
        type: string
        enum: [mr, mrs, ms, dr]
      name?: string
      family_name?: string
      gender?:
        type: string
        enum: [female, male]
      vat_id?:
      birth_date?: date-only
      death_date?: date-only
      address_country?: string
      address_locality?: string
      address_region?: string
      postal_code?: string
      street_address?: string


  NewBankAccountRequestData:
    properties:
      accountType:
        type: string
        enum: [ standard, saver ]

  BankAccountData:
    properties:
      id: string
      account_number: string
      accountType:
        type: string
        enum: [ standard, saver ]
      amount: MonetaryAmountData
      lei: string
      fees_and_comissions: string
      review_state:
        type: string
        enum: [ requested, cancelled, opened, closed ]
      interest_rate: number
      annual_interest_rate: number
      minimum_inflow: MonetaryAmountData
      overdraft_limit: MonetaryAmountData

  NewLoanRequestData:
    properties:
      category: string
      amount: MonetaryAmountData
      term: DurationData
      interest_rate: number
      down_payment: MonetaryAmountData
      payment_amount: MonetaryAmountData
      payment_frequency: number
      review_state:
        type: string
        enum:
          - requested
          - underwriting
          - rejected
          - accepted
          - repaying
          - failed
          - closed

  LoanData:
    properties:
      id: string
      account_number: string
      accountType:
        type: string
        enum: [ standard, saver ]
      amount: MonetaryAmountData
      lei: string
      fees_and_comissions: string
      review_state:
        type: string
        enum:
          - requested
          - cancelled
          - underwriting
          - accepted
          - opened
          - failed
          - closed
      interest_rate: number
      annual_interest_rate: number
      minimum_inflow: MonetaryAmountData
      overdraft_limit: MonetaryAmountData
      grace_period: DurationData

  NewDebitCardRequestData:
    properties:
      cash_back: boolean
      contactless: boolean

  DebitCardData:
    properties:
      id: string
      lei: string
      fees_and_comissions:
      review_state:
        type: string
        enum:
          - requested
          - cancelled
          - opened
          - closed
      cash_back: boolean
      contactless: boolean
      floor_limit: MonetaryAmountData

  NewCreditCardRequestData:
    properties:
      cash_back: boolean
      contactless: boolean
      interest_rate: number
      payment_amount: MonetaryAmountData
      payment_frequency: number
      review_state:
        type: string
        enum:
          - requested
          - cancelled
          - underwriting
          - accepted
          - opened
          - failed
          - closed

  CreditCardData:
    properties:
      id: string
      amount: MonetaryAmountData
      lei: string
      cash_back: boolean
      contactless: boolean
      floor_limit: MonetaryAmountData
      fees_and_comissions:
      review_state:
        type: string
        enum:
          - requested
          - cancelled
          - underwriting
          - accepted
          - opened
          - failed
          - closed
      interest_rate: number
      annual_interest_rate: number
      minimum_inflow: MonetaryAmountData
      overdraft_limit: MonetaryAmountData
      grace_period: DurationData
