#%RAML 1.0
/servers:
  (lib2.TestAnnotationType): Some other lib
  (lib.TestAnnotationType): TestAnnotationType2
  (lib.AnotherAnnotationType):
    firstProp: firstProp2
    secondProp: 101
title: Overlay 2
uses:
  lib: lib.raml
  lib3: lib.raml
  lib2: lib.raml
