#%RAML 1.0
title: Tato Bores
mediaType:
  - application/json
  - text/xml
/ok0:
  post:
    body:
      example: bores
      type: any
    responses:
      200:
        body:
          example: tato
          type: any
      400:
        body:
          text/plain:
            example: coqui
            type: any
      401:
        body:
          text/csv:
      402:
        body:
          type: any
      403: {}
