#%RAML 1.0 NamedExample
value:
  customerID: 8f19c230-vs57-429d
  firstName: Max
  lastName: Mule
  displayName: Max the Mule
  address: 
    addressLine1: 123 Street
    addressLine2: Apt.#3D
    city: San Francisco
    state: California
    zipCode: '94110'
    country: United States
  phone: 415-000-0000
  email: max@mulesoft.com
  ssn: 123-456-7890
  dateOfBirth: 1988-07-01