#%RAML 1.0
title:  test
types:
    A:
      type: object
      properties:
        data?: string
      examples:
#                      6PerPageDocuments: !include examples/documents/get-response-example.raml