#%RAML 1.0
baseUri: uri

title: some title
version: 1.0
mediaType: application/json
description: some description

types:
  someType:
    type: !include schema/application-request.json
    example: !include examples/CreateApplicationRequest.json

 

