#%RAML 1.0
title: the title

/countries/{countryid}/stores/{storeid}:
  uriParameters:
    countryid:
      type: integer
      example: 310792
    storeid:
      type: string
      example: some example