#%RAML 1.0
title: Aesop Federated Profile System
version: 0.6.0
/something:
  get:
    body:
      "*/*":
        type: object
        additionalProperties: true
        properties:
          currency:
            type: string
            required: false
          value:
            type: number
            required: false
