#%RAML 1.0
title: Cross Reference API
version: v1

/xref:
  /upload:
    post:
      body:
        binary/octet-stream:
        multipart/form-data:
          properties:
            file:
              description: The file to be uploaded
              required: true
              type: file
