#%RAML 1.0
title: Minimal Body Conflict API
version: v1

/loans:
  post:
    body:
      application/x-www-form-urlencoded:
      application/json:
    responses:
      201:
        body:
          application/json:
