#%RAML 1.0
title: sample raml
version: v1

/depot:
  post:
    body:
      multipart/form-data:
        properties:
          aFile:
            type: file
            fileTypes: [ 'application/xml' ]
