#%RAML 1.0
title: "Some title"
version: "1.0"
protocols:
- "HTTP"
mediaType:
- "*/*"

/pdfmarkup/v1/documents/prepareForPrint:
  post:
    body:
      application/vnd.adobe.xfdf:
        type: file
    responses:
      200:
        body:
          application/json:
            type: object
