#%RAML 1.0
title: employee
version: v1

securitySchemes:
  oauth_2_0:
    type: OAuth 2.0
    settings:
      authorizationUri: http://something
      accessTokenUri: http://something
      authorizationGrants: client_credentials