#%RAML 1.0
title: Simple Array Type with Example
types:
  Email:
    type: object
    properties:
      subject:
        type: string
      body:
        type: string
  Emails:
    minItems: 1
    uniqueItems: true
    example:
      -
        subject: My Email 1
        body: This is the text for email 1.
      -
        subject: My Email 2
        body: This is the text for email 2.
    items: Email
