#%RAML 1.0
title: Some API

types:

  array-type:
    type: array
    minItems: -1
    maxItems: -1

  string-type:
    type: string
    minLength: -1
    maxLength: -1

  file-type:
    type: file
    maxLength: -1
    minLength: -1

