#%RAML 1.0
title: test
types:
  A:
    items:
      properties:
        a: string
        b: string
    enum:
      -
        - a: aa
          b: bb
        - a: ee
          b: tt
      -
        - a: qq
          b: pp
        - a: ii
          b: ..
    examples:
      invalid1:
        - a: aa
          b: bb
      invalid2:
        - a: pp
          b: dd
        - a: ee
          b: t
