#%RAML 1.0
title: test
types:
  A:
    properties:
      value1: string
      value2: string
    enum:
      - value1: aa
        value2: bb
      - value1: cc
        value2: dd
    example:
      value1: aa
      value2: bb