#%RAML 1.0
title: SFDC-sAPI
version: v1
baseUri: http://alcwc-sfdc-sapi.cloudhub.io/
/attendees:
  get:
    responses:
      "200":
        body:
          application/json:
            description: collection of type attendee
            type: array
