#%RAML 1.0 Library
usage: |
  provides a set of resusable data types that describe concepts
  related to quantities and measurements
types:
  QuantityType:
    type: string
    enum:
      - DISCRETE
      - CONTINUOUS
  Quantity:
    discriminator: quantityType
    properties:
      quantityType:
        type: string
        enum:
          - DISCRETE
          - CONTINUOUS
      amount:
        type: number
        minimum: 0
      unit:
        type: string
        default: EA
  DiscreteQuantity:
    discriminator: quantityType
    discriminatorValue: DISCRETE
    properties:
      quantityType:
        type: string
        enum:
          - DISCRETE
          - CONTINUOUS
      unit:
        type: string
        default: EA
      amount:
        minimum: 0
        type: integer
