#%RAML 1.0
title: New API
types:
  Person:
    properties:
      1:
        type: string
      true:
        type: number
      0.1:
        type: number
      nil:
        type: number
      null:
        type: number


