#%RAML 1.0
title: cpl-test
version: 1.0

/wildcards:
  post:
    body:
      application/x-www-form-urlencoded:
        properties:
          /^element-\d+$/:
            type: integer
        example:
          element-2: 34

/wildcards2:
  post:
    body:
      application/x-www-form-urlencoded:
        properties:
          /^element-\d+$/:
            type: integer
        example:
          valid-unknown-property: "does not match with pattern property"

/wildcards3:
  post:
    body:
      application/x-www-form-urlencoded:
        properties:
          /^element-\d+$/:
            type: integer
        example:
          element-3: "test"
