#%RAML 1.0
title: test title
description: test description
baseUri: api.example.com/path
securitySchemes:
  oauth_2_0:
    displayName: OAuth2
    description: oauth 2.0
    type: OAuth 2.0
    settings:
      authorizationUri: https://www.dropbox.com/1/oauth2/authorize
      accessTokenUri: https://api.dropbox.com/1/oauth2/token
      authorizationGrants:
        - authorization_code
resourceTypes:
  searchableCollection:
    get:
      queryParameters:
        <<queryParamName>>:
          description: Return <<resourcePathName>> that have their <<queryParamName>> matching the given value
traits:
  secured:
    description: blabla
  parameterized:
    queryParameters:
      <<tokenName>>:
        description: A valid <<tokenName>> is required
  descr:
    description: Some requests require authentication.
/top:
  type:
    searchableCollection:
      queryParamName: title
  get:
    protocols:
      - HTTPS
    is:
      - secured
    securedBy:
      - oauth_2_0
  post:
    is:
      -
        parameterized:
          tokenName: access_token
  is:
    - descr
  securedBy:
    - oauth_2_0
protocols:
  - HTTP
