#%RAML 1.0 Overlay
extends: file://amf-client/shared/src/test/resources/org/raml/parser/overlays/types-add/master.raml
types:
  scalar:
    examples:
      first: overlaid
      third: terzo
  location:
    example:
      lat: -34.6
      long: -58.4
  another-scalar:
    type: string
