#%RAML 1.0
title: Duplicate examples
types:
  errorType:
    type: object
    properties:
      code: integer
      message: string

/a:
  get:
    responses:
      404:
        body:
          application/json:
            type: errorType
            examples:
              404-a:
                code: 404
                message: This is a 404 error.
              500-a:
                code: 500
                message: This is a 500 error.
      500:
        body:
          application/json:
            type: errorType

/b:
  get:
    responses:
      404:
        body:
          application/json:
            type: errorType
            examples:
              404-b:
                code: 404
                message: This is a 404 error.
              500-b:
                code: 500
                message: This is a 500 error.
      500:
        body:
          application/json:
            type: errorType
