#%RAML 1.0
title: Invalid min/maxItems facet
types:
  Email:
    minItems: -6
    maxItems: 0
    type: array
    items:
      type: string
  Name:
    minItems: 0
    maxItems: 7
    type: array
    items:
      type: string
