#%RAML 1.0 Overlay
extends: main.raml

types:
    scalar:
        examples:
            first: overlaid
            third: terzo

    location:
        type: any
        example:
            lat: -34.6
            long: -58.4

    another-scalar:
      type: string
