#%RAML 1.0
title: Including parent resources
/blabla:
  get:
    responses:
      "400":
        body:
          application/json:
            type: object
            displayName: Platform Fault Datatype
            additionalProperties: true
            properties:
              message:
                type: string
                required: true
