#%RAML 1.0 DataType
type: object
properties: 
  accountID: string
  accountType: 
    enum: 
      - Checking 
      - Savings 
      - Overdraft Savings 
      - Credit Card
  accountNumber: string
  accountOwner: 
    type: array
    items: !include AccountOwner.raml
  accountBalance: !include Money.raml
  IBAN:
    type: string
    pattern: ^[A-Z]{2,2}[0-9]{2,2}[a-zA-Z0-9]{1,30}$
  bank: !include Bank.raml
  interestRate?:
    type: number
    format: double
  createdAt: datetime
  modifiedAt?: datetime
example: !include ../examples/AccountExample.raml 