#%RAML 1.0 DataType
type: object
properties:
  errors:
    type: array
    items:
      type: object
      properties:
        code:
          type: string
          example: "500"
        detail:
          type: string
          example: "Error sending email"
        id:
          type: string
          example: "26dfdwf-223j3rrg-7657"