#%RAML 1.0 Library

types:
  document:
    type: object
    properties:
      id: string
      process: string
      creationDate: datetime
      budgerHolderID: string
      content:
        type: file
        fileTypes: ['image/jpeg', 'image/png']
        minLength: 10
    example:
      id: "1"
      process: "PGB"
      creationDate: "2016-01-04T12:48:19+00:00"
      budgerHolderID: "1234"
      content: "hafgiuhaiurghiuahgvindijnadgjhvkdajhfgvjkasfbvkjdanfkvjhsfajgh89uy9hiuh"