#%RAML 1.0
title: Discriminator
types:
  Person:
    properties:
      name:
        type: string
    type: object
  Employee:
    type: Person
    properties:
      employeeId:
        type: string
  User:
    type: Person
    properties:
      userId:
        type: string
  UserOrEmplo:
    type: User | Employee
    discriminator: isClever
