#%RAML 1.0
title: FHIR API
version: 1.0
#baseUri: http://vadp-condition-v1.0.cloudhub.io/api
baseUri: https://mocksvc.mulesoft.com/mocks/bc0dc070-252a-4b54-a02c-7f119c39bf6a/apg
types: 

  base64Binary:
    type: string

  unsignedInt:
    type: integer
    minimum: 0

  decimal:
    type: number
    description: |
      A JSON number, except that exponents are not allowed or xs:decimal, except that decimals may not use exponents, and leading 0 digits are not allowed

  id:
    type: string
    #pattern: [A-Za-z0-9\-\.]{1,64}
    description: |
      Any combination of upper or lower case ASCII letters ('A'..'Z', and 'a'..'z', numerals ('0'..'9'), '-' and '.', with a length limit of 64 characters. (This might be an integer, an un-prefixed OID, UUID or any other identifier pattern that meets these constraints.)

  uri:
    type: string
    #pattern: /^([a-z0-9+.-]+):(?://(?:((?:[a-z0-9-._~!$&'()*+,;=:]|%[0-9A-F]{2})*)@)?((?:[a-z0-9-._~!$&'()*+,;=]|%[0-9A-F]{2})*)(?::(\d*))?(/(?:[a-z0-9-._~!$&'()*+,;=:@/]|%[0-9A-F]{2})*)?|(/?(?:[a-z0-9-._~!$&'()*+,;=:@]|%[0-9A-F]{2})+(?:[a-z0-9-._~!$&'()*+,;=:@/]|%[0-9A-F]{2})*)?)(?:\?((?:[a-z0-9-._~!$&'()*+,;=:/?@]|%[0-9A-F]{2})*))?(?:#((?:[a-z0-9-._~!$&'()*+,;=:/?@]|%[0-9A-F]{2})*))?$/i/

  instant:
    type: string


  code:
    type: string
    #pattern: [^\s]+([\s]+[^\s]+)*
    description: |
      Indicates that the value is taken from a set of controlled strings defined elsewhere (see Using codes for further discussion). Technically, a code is restricted to a string which has at least one character and no leading or trailing whitespace, and where there is no whitespace other than single spaces in the contents

  xhtml:
    type: string

  date:
    type: string
    pattern: -?[0-9]{4}(-(0[1-9]|1[0-2])(-(0[0-9]|[1-2][0-9]|3[0-1]))?)?
    example: 1970-08-07

  dateTime:
    type: string
    pattern: -?[0-9]{4}(-(0[1-9]|1[0-2])(-(0[0-9]|[1-2][0-9]|3[0-1])(T([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9](\.[0-9]+)?(Z|(\+|-)((0[0-9]|1[0-3]):[0-5][0-9]|14:00)))?)?)?


  time:
    type: string
    pattern: ([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9](\.[0-9]+)?

  gender:
    enum: [male, female, other, unknown]

  markdown:
    type: string
    description: A string that may contain markdown syntax for optional processing by a markdown presentation engine

  ObservationRelationshipType:
    type: code
    enum: [has-member, derived-from, sequel-to, replaces, qualified-by, interfered-by]

  UnitOfTime:
    description: A unit of time (UCUM)
    type: code
    enum: [s, min, h, d, wk, mo, a]

  EncounterState:
    type: code
    enum: [planned, arrived, in-progress, onleave, finished, cancelled]

  ObservationStatus:
    type: code
    enum: [registered, preliminary, final, ammended, cancelled, entered-in-error, unknown]

  ObservationCode:
    type: code
    description: https://www.hl7.org/fhir/valueset-observation-codes.html

  Extension:
    properties:
      url: uri
      /^value(Integer|Decimal|DateTime|Date|Instant|String|Uri|Boolean|Code|Markdown|Base64Binary|Coding|CodeableConcept|Attachment|Identifier|Quantity|Range|Period|Ratio|HumanName|Address|ContactPoint|Timing|Signature|Reference)$/: integer | decimal | dateTime | date | instant | string | uri | boolean | code | markdown | base64Binary | Coding | CodeableConcept | Attachment | Identifier | Quantity | Range | Period | Ratio | HumanName | Address | ContactPoint | Timing | Signature | Reference

  Element:
    properties:
      id?: id
      extension?: Extension[]

  Duration:
    type: Quantity
    description: a length of time

  Signature:
    properties:
      type: Coding[]
      when: instant
      /^who(Uri|Reference)$/: uri | Reference
      contentType: code
      blob: base64Binary

  Timing:
    type: Element
    properties:
      event?: dateTime[]
      repeat?:
        type: Element
        properties:
          /^bounds(Duration|Range|Period)$/?: Duration | Range | Period
          count?: integer
          duration?: decimal
          durationMax?: decimal
          durationUnits?: UnitOfTime
          frequency?: integer
          frequencyMax?: integer
          period?: decimal
          periodMax?: decimal
          periodUnits?: UnitOfTime
          when?:
            type: code
            enum: [HS, WAKE, C, CM, CD, CV, AC, ACM, ACD, ACV, PC, PCM, PCD, PCV]
      code?: CodeableConcept

  Ratio:
    type: Element
    properties:
      numerator?: Quantity
      denominator?: Quantity

  Coding:
    properties:
      system?: uri
      version?: string
      code?: code
      display?: string
      userSelected?: boolean

  Meta:
    type: Element
    properties:
      versionId?: id
      lastUpdated?: instant
      profile?: uri
      security?: Coding[]
      tag?: Coding[]

  Narrative:
    properties:
      status: code
      div: xhtml

  CodeableConcept:
    type: Element
    properties:
      coding?: Coding[]
      text?: string

  SampledData:
    description: A series of measurements taken by a device
    type: Element
    properties:
      origin: SimpleQuantity
      period: decimal
      factor?: decimal
      lowerLimit?: decimal
      upperLimit?: decimal
      dimensions: positiveInt
      data: string

  Period:
    type: Element
    properties:
      start?: datetime
      end?: datetime

  Reference:
    type: Element
    properties:
      reference?: string
      display?: string

  Identifier:
    properties:
      use?: code
      type?: CodeableConcept
      system?: uri
      value?: string
      period?: Period
      assigner?: Reference

  Range:
    type: Element
    properties:
      low?: integer
      high?: integer

  Quantity:
    type: Element
    properties:
      value?: decimal
      comparator?:
        type: code
        enum: ['<', '<=', '>=', '>']
      unit?: string
      system?: uri
      code?: code

  SimpleQuantity: Quantity

  Age: Quantity

  positiveInt:
    type: integer
    minimum: 0

  HumanName:
    type: Element
    properties:
      use?:
        type: code
        enum: [usual, official ,temp, nickname, anonymous, old, maiden]
      text?:
      family?: string[]
      given?: string[]
      prefix?: string[]
      suffix?: string[]
      period?: Period

  ContactPoint:
    type: Element
    properties:
      system?:
        enum: [phone,fax,email,pager,other]
      value?:
      use?:
      rank?:
        type: positiveInt
      period?: Period

  BackboneElement:
    type: Element
    properties:
      modifierExtension?: Extension

  Address:
    type: Element
    properties:
      use?:
        type: code
        enum: [home, work, temp, old]
      type?:
        type: code
        enum: [postal, physical, both]
      text?:
      line?: string[]
      city?:
      district?:
      state?:
      postalCode?:
      country?:
      period?: Period

  Attachment:
    type: Element
    properties:
      contentType?:
        type: code
        description: Mime type of the content, with charset etc.
      language?:
        type: code
        description: Human language of the content (BCP-47)
      data?: base64Binary
      url?: uri
      size?: unsignedInt
      hash?: base64Binary
      title?: string
      creation?: dateTime

  Annotation:
    type: Element
    properties:
      /^author(Reference|String)$/?: Reference | string
      time?: dateTime
      text?: string

  Resource:
    properties:
      id?: id
      meta?: Meta
      implicitRules?: uri
      language?: code

  DomainResource:
    type: Resource
    properties:
      # where is resourceType defined in the spec?
      resourceType: string
      text:
        type: Narrative
      contained?: Resource[]
      extension?: Extension[]
      modifierExtension?: Extension[]

  Condition:
    type: DomainResource
    properties:
      identifier?: Identifier[]
      patient: Reference
      encounter?: Reference
      asserter?: Reference
      dateRecorded?: date-only
      code: CodeableConcept
      category?: CodeableConcept
      clinicalStatus?: code
      verificationStatus: code
      severity?: CodeableConcept
      /^onset(DateTime|Period|Range|String)$/?: datetime | Age | Period | Range | string
      /^abatement(DateTime|Quantity|Boolean|Range|String)$/?: datetime | Age | boolean | Range | string
      stage?:
        type: BackboneElement
        properties:
          summary?: CodeableConcept
          asessment?: Reference
      evidence?:
        type: BackboneElement
        properties:
          code?: CodeableConcept
          detail?: any
      bodySite?: CodeableConcept
      notes?:
    additionalProperties: false

  AllergyIntolerance:
    type: DomainResource
    properties:
      identifier?: Identifier[]
      onset?: dateTime
      recordedDate?: dateTime
      recorder?: Reference
      patient: Reference
      reporter?: Reference
      substance: CodeableConcept
      status?:
        type: code
        enum: [active, unconfirmed, confirmed, inactive, resolved, refuted, entered-in-error]
      criticality?:
        type: code
        enum: [CRITL, CRITH, CRITU]
      type?:
        type: code
        enum: [allergy, intolerance]
      category?:
        type: code
        enum: [food, medication, environment, other]
      lastOccurence?: dateTime
      note?: Annotation
      reaction?:
        type: array
        items:
          type: BackboneElement
          properties:
            substance?: CodeableConcept
            certainty?:
              type: code
              enum: [unlikely, likely, confirmed]
            manifestation:
              type: array
              minItems: 1
              items:
                type: CodeableConcept
            description?: string
            onset?: dateTime
            severity?:
              type: code
              enum: [mild, moderate, severe]
            exposureRoute?: CodeableConcept
            note?: Annotation

  Device:
    description: An instance of a manufactured te that is used in the provision of healthcare
    type: DomainResource
    properties:
      identifier?: Identifier[]
      type: CodeableConcept
      note?: Annotation[]
      status?:
        type: code
        enum: [available, not-available, enetered-in-error]
      manufacturer?: string
      model?: string
      version?: string
      manufactureDate?: dateTime
      expiry?: dateTime
      udi?: string
      lotNumber?: string
      owner?: Reference
      location?: Reference
      patient?: Reference
      contact?: ContactPoint[]
      url?: uri

  Appointment:
    description: |
      A booking of a healthcare event among patient(s), practitioner(s), related person(s) and/or device(s) for a specific date/time. This may result in one or more Encounter(s)
      Only proposed or cancelled appointments can be missing start/end dates
      Either start and end are specified, or neither
    type: DomainResource
    properties:
      identifier?: Identifier[]
      status:
        type: code
        enum: [proposed, pending, booked, arrived, fulfilled, cancelled, noshow]
      type?: CodeableConcept
      reason?: CodeableConcept
      priority?: unsignedInt
      description?: string
      start?: instant
      end?: instant
      minutesDuration?: positiveInt
      slot?: Reference[]
      comment?: string
      participant:
        type: array
        minItems: 1
        items:
          type: BackboneElement
          properties:
            type?: CodeableConcept
            actor?: Reference
            required?:
              type: code
              enum: [required, optional, information-only]
            status:
              type: code
              enum: [accepted, declined, tentative, needs-action]

  Slot:
    description: |
      A slot of time on a schedule that may be available for booking appointments
    type: DomainResource
    properties:
      identifier?: Identifier[]
      type?: CodeableConcept
      schedule: Reference
      freeBusyType:
        type: code
        enum: [busy, free, busy-unavailable, busy-tentative]
      start: instant
      end: instant
      overbooked?: boolean
      comment?: string

  Schedule:
    description: |
      A container for slot(s) of time that may be available for booking appointments
    type: DomainResource
    properties:
      identifier?: Identifier[]
      type?: CodeableConcept[]
      actor: Reference
      planningHorizon?: Period
      comment?: string

  Patient:
    description: Information about an individual or animal receiving health care services
    type: DomainResource
    properties:
      identifier?: Identifier[]
      active?:
        type: boolean
        description: Whether this patient's record is in active use
      name?: HumanName[]
      telecom?: ContactPoint[]
      gender?: gender
      birthDate?: date
      /^deceased(Boolean|DateTime)$/?: boolean | dateTime
      address?: Address[]
      maritalStatus?: CodeableConcept
      /^multipleBirth(Boolean|Integer)$/?: boolean | integer
      photo?: Attachment[]
      contact?:
        description: |
          A contact party (e.g. guardian, partner, friend) for the patient
          SHALL at least contain a contact's details or a reference to an organization
        type: array
        items:
          type: BackboneElement
          properties:
            relationship?: CodeableConcept[]
            name?: HumanName
            telecom?: ContactPoint[]
            address?: Address
            gender?: gender
            organization?: Reference
            period?:
              description: |
                The period during which this contact person or organization is valid to be contacted relating to this patient
              type: Period
      animal?:
        description: This patient is known to be an animal (non-human)
        type: BackboneElement
        properties:
          species: CodeableConcept
          breed?: CodeableConcept
          genderStatus?: CodeableConcept
      communication?:
        description: |
          A list of Languages which may be used to communicate with the patient about his or her health
        type: array
        items:
          type: BackboneElement
          properties:
            language: CodeableConcept
            preferred?: boolean
      careProvider?: Reference[]
      managingOrganization?:
        description: Organization that is the custodian of the patient record
        type: Reference
      link?:
        description: Link to another patient resource that concerns the same actual person
        type: BackboneElement
        properties:
          other: Reference
          type:
            type: code
            enum: [replace, refer, seealso]

  Practitioner:
    description:
    type: DomainResource
    properties:
      identifier?: Identifier[]
      active?:
        description: Whether this practitioner's record is in active use
        type: boolean
      name?: HumanName[]
      telecom?: ContactPoint[]
      address?: Address[]
      gender?: gender
      birthDate?: date
      photo?: Attachment[]
      practitionerRole?:
        description: |
          Roles/organizations the practitioner is associated with
        type: array
        items:
          type: BackboneElement
          properties:
            managingOrganization?: Reference
            role?: CodeableConcept
            specialty?: CodeableConcept[]
            period?:
              description: |
                The period during which the practitioner is authorized to perform in these role(s)
              type: Period
            location?: Reference[]
            healthcareService?: Reference[]
      qualification?:
        description: |
          Qualifications obtained by training and certification
        type: array
        items:
          type: BackboneElement
          properties:
            identifier?: Identifier[]
            code: CodeableConcept
            period?:
              description: |
                Period during which the qualification is valid
              type: Period
            issuer?: Reference
      communication?: CodeableConcept[]

  Medication:
    type: DomainResource
    properties:
      code?: CodeableConcept
      isBrand?: boolean
      manufacturer?: Reference
      product?:
        type: BackboneElement
        properties:
          form?: CodeableConcept
          ingredient?:
            type: array
            items:
              type: BackboneElement
              properties:
                item: Reference
                amount?: Ratio
          batch?:
            type: array
            items:
              type: BackboneElement
              properties:
                lotNumber?: string
                expirationDate?: dateTime
      package?:
        type: BackboneElement
        properties:
          container?: CodeableConcept
          content?:
            type: BackboneElement
            properties:
              item: Reference
              amount?: SimpleQuantity

  Encounter:
    type: DomainResource
    properties:
      identifier?: Identifier[]
      status: EncounterState
      statusHistory?:
        type: array
        items:
          type: BackboneElement
          properties:
            status: EncounterState
            period: Period
      class:
        type: code
        enum: [inpatient, outpatient, ambulatory, emergency]
      type?: CodeableConcept[]
      priority?: CodeableConcept
      patient?: Reference
      episodeOfCare?: Reference[]
      incomingReferral?: Reference[]
      participant?:
        type: array
        items:
          type: BackboneElement
          properties:
            type?: CodeableConcept
            period?: Period
            individual?: Reference
      appointment?: Reference
      period?: Period
      length?: Duration
      reason?: CodeableConcept[]
      indication?: Reference[]
      hospitalization?:
        type: BackboneElement
        properties:
          preAdmissionIdentifier?: Identifier
          origin?: Reference
          admitSource?: CodeableConcept
          admittingDiagnosis?: Reference[]
          reAdmission?: CodeableConcept
          dietPreference?: CodeableConcept[]
          specialCourtesy?: CodeableConcept[]
          specialArrangement?: CodeableConcept[]
          destination?: Reference
          dischargeDisposition?: CodeableConcept
          dischargeDiagnosis?: Reference[]
      location?:
        type: array
        items:
          type: BackboneElement
          properties:
            location: Reference
            status?:
              type: code
              enum: [planned, active, reserved, completed]
            period?: Period
      serviceProvider?: Reference
      partOf?: Reference

  Observation:
    type: DomainResource
    properties:
      identifier?: Identifier[]
      status: ObservationStatus
      category?: CodeableConcept
      code: CodeableConcept
      subject?: Reference
      encounter?: Reference
      /^effective(DateTime|Period)$/?: dateTime | Period
      issued?: instant
      performer?: Reference[]
      /^value(Quantity|CodeableConcept|String|Range|Ratio|SampledData|Attachment|Time|DateTime|Period)$/?: Quantity | CodeableConcept | string | Range | Ratio | SampledData | Attachment |  time | dateTime | Period
      dataAbsentReason?: CodeableConcept
      interpretation?: CodeableConcept
      comments?: string
      bodySite?: CodeableConcept
      method?: CodeableConcept
      specimen?: Reference
      device?: Reference
      referenceRange?:
        type: array
        items:
          type: BackboneElement
          properties:
            low?: SimpleQuantity
            high?: SimpleQuantity
            meaning?: CodeableConcept
            age?: Range
            text?: string
      related?:
        type: array
        items:
          type: BackboneElement
          properties:
            type?: ObservationRelationshipType
            target: Reference
      component?:
        type: array
        items:
          type: BackboneElement
          properties:
            code: CodeableConcept
            /^value(Quantity|CodeableConcept|String|Range|Ratio|SampledData|Attachment|Time|DateTime|Period)$/?: Quantity | CodeableConcept | string | Range | Ratio | SampledData | Attachment | time | dateTime | Period
            dataAbsentReason?: CodeableConcept
            referenceRange?:
              type: array
              items:
                type: BackboneElement
                properties:
                  low?: SimpleQuantity
                  high?: SimpleQuantity
                  meaning?: CodeableConcept
                  age?: Range
                  text?: string
  MedicationOrder:
    type: DomainResource
    properties:
      identifier?: Identifier[]
      dateWritten?: dateTime
      status?:
        type: code
        enum: [active, on-hold, completed, entered-in-error, stopped, draft]
      dateEnded?: dateTime
      reasonEnded?: CodeableConcept
      patient?: Reference
      prescriber?: Reference
      encounter?: Reference
      /^reason(CodeableConcept|Reference)$/?: CodeableConcept | Reference
      note?: string
      /^medication(CodeableConcept|String)$/: CodeableConcept | string
      dosageInstruction?:
        type: array
        items:
          type: BackboneElement
          properties:
            text?:
            additionalInstructions?: CodeableConcept
            timing?: Timing
            /^asNeeded(Boolean|CodeableConcept)$/?: boolean | CodeableConcept
            /^site(CodeableConcept|Reference)$/?: CodeableConcept | Reference
            route?: CodeableConcept
            method?: CodeableConcept
            /^dose(Range|Quantity)$/?: Range | Quantity
            /^rate(Ratio|Range)$/?: Ratio | Range
            maxDosePerPeriod?: Ratio
      dispenseRequest?:
        type: BackboneElement
        properties:
          /^medication(CodeableConcept|Reference)$/: CodeableConcept | Reference
          validityPeriod?: Period
          numberOfRepeatsAllowed?: positiveInt
          quantity?: SimpleQuantity
          expectedSupplyDuration?: Duration
      substitution?:
        type: BackboneElement
        properties:
          type?: CodeableConcept
          reason?: CodeableConcept
      priorPrescription?: Reference

  Bundle:
    type: Resource
    properties:
      type:
        type: code
        enum: [document, message, transaction,  transaction-response, batch, batch-response,  history, searchset, collection]
      total?: unsignedInt
      link?:
        type: array
        items:
          type: BackboneElement
          properties:
            relation: string
            url: uri
      entry:
        type: array
        items:
          type: BackboneElement
          properties:
            link?:
              type: array
              items:
                type: BackboneElement
                properties:
                  relation: string
                  url: uri
            fullUrl?: uri
            resource: Resource
            search?:
              type: BackboneElement
              properties:
                mode?:
                  type: code
                  enum: [match, include, outcome]
                score?: decimal
            request?:
              type: BackboneElement
              properties:
                method:
                  type: code
                  enum: [GET, PUT, POST, DELETE]
                url: uri
                ifNoneMatch?: string
                ifModifiedSince?: instant
                ifMatch: string
                ifNoneExist: string
            response?:
              type: BackboneElement
              properties:
                status: string
                location?: uri
                etag?: string
                lastModified?: instant
      signature?: Signature

  Conformance:
    type: DomainResource
    properties:
      url?: uri
      version?:
      name?:
      status?:
        type: code
        enum: [draft, active, retired]
      experimental?: boolean
      publisher?:
      contact?:
        type: array
        items:
          type: BackboneElement
          properties:
            name?:
            telecom?: ContactPoint[]
      date: dateTime
      description?:
      requirements?:
      copyright?:
      kind:
        type: code
        enum: [instance, capability, requirements]
      software?:
        type: BackboneElement
        properties:
          name:
          version?:
          releaseDate?: dateTime
      implementation?:
        type: BackboneElement
        properties:
          description:
          url?: uri
      fhirVersion: id
      acceptUnknown:
        type: code
        enum: [no, extensions, elements, both ]
      format:
        type: array
        items:
          type: code
          enum: [xml, json, application/xml, application/json]
      profile?: Reference[]
      rest?:
        type: array
        items:
          type: BackboneElement
          properties:
            mode:
              type: code
              enum: [client, server]
            documentation?:
            security?:
              type: BackboneElement
              properties:
                cors?: boolean
                service?: CodeableConcept[]
                description?:
                certificate?:
                  type: array
                  items:
                    type: BackboneElement
                    properties:
                      type?: code
                      blob?: base64Binary
            resource:
              type: array
              items:
                type: BackboneElement
                properties:
                  type:
                    type: code
                    enum: [] # Resource Type list TODO:
                  profile?: Reference
                  interaction:
                    type: array
                    items:
                      type: BackboneElement
                      properties:
                        code:
                          type: code
                          enum: [read, vread, update, delete, history-instance, validate, history-type, create, search-type]
                        documentation?:
                  versioning?:
                    type: code
                    enum: [no-version, versioned, versioned-update]
                  readHistory?: boolean
                  updateCreate?: boolean
                  conditionalCreate?: boolean
                  conditionalUpdate?: boolean
                  coditionalDelete?:
                    type: code
                    enum: [not-supported, single, multiple]
                  searchInclude?:
                  searchRevInclude?:
                  searchParam?:
                    type: array
                    items:
                      type: BackboneElement
                      properties:
                        name:
                        definition?:
                        type:
                          type: code
                          enum: [number, date, string, token, reference, composite, quantity, uri]
                        documentation?:
                        target?:
                          type: array
                          items:
                            type: code
                            enum: [missing, exact, contains, not, text, in, not-in, below, above, type]
                        chain?: string[]
            interaction?:
              type: array
              items:
                type: BackboneElement
                properties:
                  code:
                    type: code
                    enum: [transaction, search-system, history-system]
                  documentation?:
            transactionMode?:
              type: code
              enum: [not-supported, batch, transaction, both]
            searchParam?:
              type: array
              items:
                type: BackboneElement
                properties:
                  name:
                  definition?:
                  type:
                    type: code
                    enum: [number, date, string, token, reference, composite, quantity, uri]
                  documentation?:
                  target?:
                    type: array
                    items:
                      type: code
                      enum: [missing, exact, contains, not, text, in, not-in, below, above, type]
                  chain?: string[]
            operation?:
              type: array
              items:
                type: BackboneElement
                properties:
                  name:
                  definition:
            compartment?: uri[]
      messaging?:
        type: array
        items:
          type: BackboneElement
          properties:
            endpoint?:
              type: array
              items:
                type: BackboneElement
                properties:
                  protocol: Coding
                  address: uri
            reliableCache?: unsignedInt
            documentation: string
            event:
              type: array
              items:
                type: BackboneElement
                properties:
                  code: Coding
                  category?:
                    type: code
                    enum: [Consequence, Currency, Notification]
                  mode:
                    type: code
                    enum: [sender, receiver]
                  focus:
                    type: code
                    enum: [] #TODO: Resource Type
                  request: Reference
                  response: Reference
                  documentation?:
      document?:
        type: array
        items:
          type: BackboneElement
          properties:
            mode:
              type: code
              enum: [producer, consumer]
            docuemntation?:
            profile:


mediaType: [application/xml+fhir, application/json+fhir]

traits:

  vread:
    queryParameters:
      _format:
        required: false
        enum: [application/json, application/xml]
    responses:
      200:
        headers:
          ETag:
          Last-Modified: instant
        body:
          application/json:
            type: <<resourceName>>

  read:
    queryParameters:
      _format:
        required: false
        enum: [application/json, application/xml]
      _summary:
        required: false
        enum: ['true', 'false', text, data]
    headers:
      If-Modified-Since:
        type: instant
        required: false
      If-None-Match:
        required: false
    responses:
      304:
        description: Not Modified

  update:
    responses:
      200:
        description: Updated
      201:
        description: Created
        headers:
          Location:
            example: http://xxx/condidition/123/_history/1
          Last-Modified: datetime
          ETag:
            example: '1.0'
      422:
        description: |
          Unprocessable Entity - the proposed resource violated applicable FHIR profiles or server business rules

  delete:
    responses:
      204:
        description: Deleted

  create:
    responses:
      201:
        description: Created
        headers:
          Location:
            example: http://xxx/Condidition/123/_history/1
          Last-Modified: datetime
          ETag:
            example: '1.0'

  search:
    queryParameters:
      _content:
        required: false
      _id:
        required: false
      _lastUpdated:
        required: false
      _profile:
        required: false
      _query:
        required: false
      _security:
        required: false
      _tag:
        required: false
      _text:
        required: false
    responses:
      200:
        body:
          application/json:
            type: Bundle

  conformance:
    responses:
      200:
        body:
          application/json:
            type: Conformance
          application/xml:
            type: Conformance

  history:
    responses:
      200:
        body:
          application/json:
            type: Bundle





resourceTypes:

  fhirResourceType:
    post:
      is: [create]
      headers:
        If-None-Exist:
          required: false
          description: name=value selective criteria
      body:
        application/json:
          type: <<resourcePathName>>
      responses:
        200:
          description: No match, resource created.
        412:
          description: Precondition Failed error indicating the client's criteria were not selective enough.
    get:
      is: [search]
    put:
      description: Conditional update. Query params for selective name=value pair criteria
      is: [update]
      queryParameters:
      responses:
        412:
          description: |
            Precondition Failed error indicating the client's criteria were not selective enough
    delete:
      is: [delete]
      queryParameters:
      responses:
        404:
          description: Not found
        412:
          description: Precondition Failed error indicating the client's criteria were not selective enough.

  fhirResource:
    get:
      is: [read]
      responses:
        200:
          body:
            application/json:
              type: <<resourcePathName>>
    put:
      is: [update]
      body:
        application/json:
          type: <<resourcePathName>>
    delete:
      is: [delete]

  fhirCompartment:
    get:
      is: [search]

  fhirSearch:
    post:
      body:
        application/x-www-form-urlencoded:
          properties:
            _content:
              required: false
            _id:
              required: false
            _lastUpdated:
              required: false
            _profile:
              required: false
            _query:
              required: false
            _security:
              required: false
            _tag:
              required: false
            _text:
              required: false
      responses:
        200:
          body:
            application/json:
              type: Bundle
    get:
      is: [search]

  fhirVersionedResource:
    get:
      is: [vread: { resourceName: <<resourceName>> }]

  fhirHistory:
    get:
      is: [history]






/:
  get:
    is: [search]
    queryParameters:
      _format:
        required: false
        enum: [application/json, application/xml]
  options:
    is: [conformance]
    queryParameters:
      _format:
        required: false
        enum: [application/json, application/xml]

  /_history:
    type: fhirHistory

/metadata:
  get:
    is: [conformance]
    queryParameters:
    responses:
      200:
        headers:
          ETag:
            example: condition
        body:
          application/json:
            type: Conformance

/AllergyIntolerance:
  type: fhirResourceType
  /_history:
    type: fhirHistory
  /{id}:
    type: fhirResource
    /_history:
      type: fhirHistory
      /{vid}:
        type: { fhirVersionedResource: { resourceName: AllergyIntolerance } }
  /_search:
    type: fhirSearch

/Appointment:
  type: fhirResourceType
  /_history:
    type: fhirHistory
  /{id}:
    type: fhirResource
    /_history:
      type: fhirHistory
      /{vid}:
        type: { fhirVersionedResource: { resourceName: Appointment } }
  /_search:
    type: fhirSearch

/Condition:
  type: fhirResourceType
  /_history:
    type: fhirHistory
  /{id}:
    type: fhirResource

    /_history:
      type: fhirHistory
      /{vid}:
        type: { fhirVersionedResource: { resourceName: Condition } }
  /_search:
    type: fhirSearch

/Device:
  type: fhirResourceType
  /_history:
    type: fhirHistory
  /{id}:
    type: fhirResource
    /_history:
      type: fhirHistory
      /{vid}:
        type: { fhirVersionedResource: { resourceName: Device } }
  /_search:
    type: fhirSearch

/Encounter:
  type: fhirResourceType
  /_history:
    type: fhirHistory
  /{id}:
    type: fhirResource
    /_history:
      type: fhirHistory
      /{vid}:
        type: { fhirVersionedResource: { resourceName: Encounter } }
  /_search:
    type: fhirSearch

/Medication:
  type: fhirResourceType
  /_history:
    type: fhirHistory
  /{id}:
    type: fhirResource
    /_history:
      type: fhirHistory
      /{vid}:
        type: { fhirVersionedResource: { resourceName: Medication } }
  /_search:
    type: fhirSearch

/MedicationOrder:
  type: fhirResourceType
  /_history:
    type: fhirHistory
  /{id}:
    type: fhirResource
    /_history:
      type: fhirHistory
      /{vid}:
        type: { fhirVersionedResource: { resourceName: MedicationOrder } }
  /_search:
    type: fhirSearch

/Observation:
  type: fhirResourceType
  /_history:
    type: fhirHistory
  /{id}:
    type: fhirResource
    /_history:
      type: fhirHistory
      /{vid}:
        type: { fhirVersionedResource: { resourceName: Observation } }
  /_search:
    type: fhirSearch

/Patient:
  type: fhirResourceType
  /_history:
    type: fhirHistory
  /{id}:
    type: fhirResource
    /_history:
      type: fhirHistory
      /{vid}:
        type: { fhirVersionedResource: { resourceName: Patient } }
    /Condition:
      type: fhirCompartment
    /Observation:
      type: fhirCompartment
    /MedicationOrder:
      type: fhirCompartment
    /Appointment:
      type: fhirCompartment
    /AllergyIntolerance:
      type: fhirCompartment
  /_search:
    type: fhirSearch

/Practitioner:
  type: fhirResourceType
  /_history:
    type: fhirHistory
  /{id}:
    type: fhirResource
    /_history:
      type: fhirHistory
      /{vid}:
        type: { fhirVersionedResource: { resourceName: Practitioner } }
    /Schedule:
      type: fhirCompartment
    /Appointment:
      type: fhirCompartment
  /_search:
    type: fhirSearch

/Schedule:
  type: fhirResourceType
  /_history:
    type: fhirHistory
  /{id}:
    type: fhirResource
    /_history:
      type: fhirHistory
      /{vid}:
        type: { fhirVersionedResource: { resourceName: Schedule } }
  /_search:
    type: fhirSearch

/Slot:
  type: fhirResourceType
  /_history:
    type: fhirHistory
  /{id}:
    type: fhirResource
    /_history:
      type: fhirHistory
      /{vid}:
        type: { fhirVersionedResource: { resourceName: Slot } }
  /_search:
    type: fhirSearch
