#%RAML 1.0 Trait
usage: Apply this trait to a GET method that supports pagination.
queryParameters: 
  offset?: 
    type: integer
    default: 10
    minimum: 0
    description: The `offset` parameter specifies the first entry to return from a collection.
  limit?: 
    type: integer
    default: 50
    minimum: 1
    description: The `limit` parameter restricts the number of entries returned.
  page?:
    type: integer
    default: 1
    minimum: 1
    description: The `page` parameter specifies the page of results to return.