#%RAML 1.0 Library

types:
  A:
    type: object
    properties:
      a:
        type: string
      b:
        type: integer
        required: false

  B:
    type: A
    properties:
      c:
        type: string

  C:
    type: object
    properties:
      a:
        type: string
        minLength: 5
      b:
        type: string
        maxLength: 5
      c:
        type: number
        minimum: 10
      d:
        type: number
        maximum: 10

  D:
    type: object
    properties:
      a:
        type: A
      c:
         type: integer

  E:
    type: string

  F:
    type: array
    items: integer

  G1:
    type: object
    properties:
      a:
        type: string
  G2:
    type: object
    properties:
      a:
        type: integer
  G: G1 | G2

  H:
    type: object
    properties:
      a: string
    additionalProperties: false

  AddressData:
    properties:
      address_country:
      address_locality?:
      address_region?:
      postal_code:
      street_address?:

  CustomerData:
    discriminator: type
    properties:
      type:
      lei:
      tax_id:
      email:
      address: AddressData

  PersonData:
    discriminatorValue: Person
    type: CustomerData
    properties:
      id:
      title?:
        type: string
#        enum: [mr, mrs, ms, dr]
      given_name:
      family_name:
      gender:
        type: string
#        enum: [female, male]
      vat_id?:
      birth_date: date-only
      death_date?: date-only