#%RAML 1.0
title: Example of Optional Properties
resourceTypes:
  コーポレートリソース:
    post?:
      description: <<投稿に関するテキスト>>に関する情報
      headers:
        X-Chargeback:
          required: true
/servers:
  type:
    コーポレートリソース:
      投稿に関するテキスト: post method # post defined which will force to define the TextAboutPost parameter
  get:
  post: # will require the X-Chargeback header
/queues:
  type: コーポレートリソース
  get:
  # will not have a post method defined which means the TextAboutPost parameter is
  # not required; same for the X-Chargeback header