#%RAML 1.0
title: test

protocols: [ HTTPS ]
types:
  Connection: !include types/Connection.raml
  Device: !include types/Device.raml

/catalog:
  post:
    body:
      application/json:
        type: object
        properties:
          x:
            required: true
            type: Device
          y:
            required: true
            type: string
        example: !include examples/example.json