#%RAML 1.0
title: test API
annotationTypes:
  a:
    type: string
types:
  MyType:
    (a): stringvalue1
    properties:
      p1:
        (a): stringValue2
/resource:
  get:
    body:
      application/json:
        (a): stringValue5
        properties:
          p2:
            (a): stringValue6
    (a): stringValue4
  (a): stringValue3
