#%Mule Agent Configuration 0.1

transports:
  websocket.transport:
    security:
      keyStorePassword: exampleNs/123 # {namespaceId}/{secretId}
      keyStoreAlias: agent
      keyStoreAliasPassword: exampleNs/124 # {namespaceId}/{secretId}

services:
  mule.agent.jmx.publisher.service: !include reusable-jmx-publisher.raml
