#%RAML 1.0 Library
types:
  Thing:
    items:
      additionalProperties: true
      properties:
        name:
          type: string
          required: true
        date:
          type: string
          required: true
        destination:
          enum:
            - SFO
            - LAX
            - CLE
          type: string
          required: true
