#%RAML 1.0 Library
types:
  Thing:
    type: array
    items:
      description: "The team is the basic unit "
      type: object
      additionalProperties: true
      properties:
        homeCity:
          description: Name of the city to which this team belongs
          type: string
          required: true
        id:
          description: A three-letter code that identifies the team id
          type: string
          minLength: 3
          maxLength: 3
          required: true
        name:
          description: Name of the team
          type: string
          required: true
        stadium:
          description: Name of the stadium
          type: string
          required: false
