#%RAML 1.0 Library
types:
  Thing:
    type: object
    additionalProperties: true
    properties:
      a:
        type: string
        required: true
      b:
        type: object
        additionalProperties: true
        properties:
          c:
            type: object
            additionalProperties: true
            properties:
              d:
                type: string
                required: true
            required: false
        required: true
