#%RAML 1.0 Library
types:
  A:
    items:
      properties:
        a:
          type: string | integer
        b:
          type: any
  B:
    items:
      properties:
        a:
          type: string | integer
        b:
          type: any
  C:
    items:
      properties:
        a:
          type: string | integer
        b:
          type: any
        c:
          type: number
