#%RAML 1.0 Library
types:
  Phone:
    properties:
      manufacturer:
        type: string
      numberOfSIMCards:
        type: number
      kind:
        type: string
  Device:
    properties:
      manufacturer:
        type: string
      numberOfUSBPorts:
        type: number
      kind:
        type: string
  Main:
    anyOf:
      -
        properties:
          manufacturer:
            type: string
          numberOfSIMCards:
            type: number
          kind:
            type: string
          phone:
            properties:
              manufacturer:
                type: string
              numberOfSIMCards:
                type: number
              kind:
                type: string
          device:
            anyOf:
              -
                properties:
                  manufacturer:
                    type: string
                  numberOfSIMCards:
                    type: number
                  kind:
                    type: string
              -
                properties:
                  manufacturer:
                    type: string
                  numberOfUSBPorts:
                    type: number
                  kind:
                    type: string
      -
        properties:
          manufacturer:
            type: string
          numberOfUSBPorts:
            type: number
          kind:
            type: string
          phone:
            properties:
              manufacturer:
                type: string
              numberOfSIMCards:
                type: number
              kind:
                type: string
          device:
            anyOf:
              -
                properties:
                  manufacturer:
                    type: string
                  numberOfSIMCards:
                    type: number
                  kind:
                    type: string
              -
                properties:
                  manufacturer:
                    type: string
                  numberOfUSBPorts:
                    type: number
                  kind:
                    type: string
