#%RAML 1.0 Library
types:
  A:
    type: string
  B:
    type: integer
  C:
    type: number
  D:
    properties:
      a:
        type: string
      b:
        type: integer
  E:
    properties:
      a:
        type: string
      c:
        type: number
  F:
    properties:
      a:
        type: string
      b:
        type: integer
      c:
        type: number
  G:
    anyOf:
      -
        properties:
          a:
            type: string
          b:
            type: integer
      -
        properties:
          a:
            type: string
          c:
            type: number
