#%RAML 1.0 Library
types:
  CatWithCity:
    properties:
      city:
        type: string
  CatWithAddress:
    properties:
      address:
        type: string
  Cat:
    properties:
      city:
        type: string
      address:
        type: string
      age:
        type: string | number
