#%RAML 1.0 Library
types:
  A:
    additionalProperties: true
    properties:
      a:
        type: string
        required: true
  B:
    additionalProperties: true
    properties:
      b:
        type: integer
        required: true
  C:
    additionalProperties: true
    properties:
      c:
        type: any
        required: true
  D:
    type: object
    additionalProperties: true
    properties:
      a:
        type: string
        required: true
      b:
        type: integer
        required: true
      c:
        type: any
        required: true
