#%RAML 1.0 Library
types:
  A:
    properties:
      a:
        type: string
  B:
    properties:
      b:
        type: integer
  C:
    properties:
      c:
        type: any
  D:
    properties:
      a:
        type: string
      b:
        type: integer
      c:
        type: any
