#%RAML 1.0 Library
types:
  AnimalWithAddress:
    properties:
      address:
        type: string
  Cat:
    properties:
      address:
        type: string
      age:
        type: integer | number
