#%RAML 1.0 Library
types:
  A:
    additionalProperties: true
    properties:
      b:
        type: number
        required: true
  B:
    type: object
    additionalProperties: true
    properties:
      b:
        type: string
        required: true
