#%RAML 1.0 DataType
additionalProperties: true
properties:
  name1?:
    type: string
    required: true
  name2:
    type: string
    required: false
  name3?:
    type: string
    required: false
  name4?:
    type: string
    required: false
