#%RAML 1.0 DataType
anyOf:
  -
    type: object
    additionalProperties: true
    properties:
      a:
        type: string
        required: true
  -
    type: object
    additionalProperties: true
    properties:
      b:
        type: string
        required: true
  -
    type: object
    additionalProperties: true
    properties:
      c:
        type: string
        required: true
  -
    type: object
    additionalProperties: true
    properties:
      d:
        type: string
        required: true
