#%RAML 1.0 DataType
anyOf:
  -
    anyOf:
      -
        type: object
        properties:
          a:
            type: string
      -
        type: object
        properties:
          b:
            type: string
  -
    anyOf:
      -
        type: object
        properties:
          c:
            type: string
      -
        type: object
        properties:
          d:
            type: string
