#%RAML 1.0
title: Api
version: 1.0
securitySchemes:
  auth:
    type: OAuth 2.0
    settings:
      authorizationUri: ""
      accessTokenUri: ""
      authorizationGrants:
        - implicit
      scopes: []
