#%Dialect 1.0
dialect: TestInstance
version: 1.5
nodeMappings:
  RootNode:
    classTerm: tmp.Test
    mapping:
      a:
        propertyTerm: tmp.a
        range: string
        in: [alpha, beta, アルファ, ベータ]
documents:
  root:
    encodes: RootNode