#%Dialect 1.0
dialect: TestInstance
version: 1.4
nodeMappings:
  ルートノード:
    classTerm: 臨時.ルートノード
    mapping:
      b2:
        propertyTerm: 臨時.b2
        range: string
        mandatory: true
        pattern: ^[\u30a0-\u30ff]+$
documents:
  root:
    encodes: ルートノード
external:
  臨時: http://test.com/臨時#