#%RAML 1.0
version: v1
title: test
protocols:
  - HTTP
  - HTTPS
/games:
  description: Retrieves type of game entities.
  get:
    headers:
      X-Integration-Id:
        description: Represents the integrator identification.
        type: string
        required: false
      X-Origin-Id:
        description: Source identification.
        type: string
        required: false
      X-No-Cache:
        description: Define if it is cacheable
        type: boolean
        required: false
        default: true
      X-Origin-Request-Id:
        description: Consumer request identification.
        type: string
        required: false
      X-Reset-Cache:
        description: Set whether to reset the cache
        type: boolean
        required: false
        default: false
      X-Channel-Id:
        description: Channel identification.
        type: string
        required: false
    displayName: all games
    body: {}
    responses:
      "200":
        headers:
          X-Integration-Id:
            description: Represents the integrator identification.
            type: string
            required: false
          X-Origin-Id:
            description: Source identification.
            type: string
            required: false
          X-Origin-Request-Id:
            description: Consumer request identification.
            type: string
            required: false
          X-Channel-Id:
            description: Channel identification.
            type: string
            required: false
        body: {}
      "500":
        headers:
          X-Integration-Id:
            description: Represents the integrator identification.
            type: string
            required: false
          X-Origin-Id:
            description: Source identification.
            type: string
            required: false
          X-Origin-Request-Id:
            description: Consumer request identification.
            type: string
            required: false
          X-Channel-Id:
            description: Channel identification.
            type: string
            required: false
        body: {}
