#%RAML 0.8
title: Proximity2
/testmapping:
  is:
  get:
    description: makes a test call to the load balancer rules and returns a response with the rule number which will be applied to the input.
    queryParameters:
      url:
        description: URL to test
        type: string
        required: true
    is: