#%RAML 0.8

# An API's methods may support custom header values in responses. The custom, non-standard HTTP headers MUST be
# specified by the headers property.
# The headers property is a map in which the key is the name of the header, and the value is itself a map
# specifying the header attributes, according to the Named Parameters section.
# This example shows a 503 error response that includes a custom header.

title: title
/media/popular:
  displayName: Most Popular Media
  get:
    description: |
      Get a list of what media is most popular at the moment.
    responses:
      503:
        description: |
          The service is currently unavailable or you exceeded the maximum requests
          per hour allowed to your application.
        headers:
          X-waiting-period:
            description: |
              The number of seconds to wait before you can attempt to make a request again.
            type: integer
            required: true
            minimum: 1
            maximum: 3600
            example: 34