#%RAML 0.8
title: test
version: "1"
/:
  post:
    body:
      application/x-www-form-urlencoded:
        formParameters:
          AccessKey:
            type: string
            required: false
          acl:
            type: string
            required: false
          file:
            -
              type: string
              description: Text content. The text content must be the last field in the form.
            -
              type: file
              description: File to upload. The file must be the last field in the form.
