#%RAML 1.0
title: OKAA
version: 0.2
baseUri: https://okaa.bva-auctions.com/
/test:
  get:
    responses:
      200:
        body:
          application/json:
            description: Comment describing your JSON Schema
            type: object
            additionalProperties: true
            properties:
              a1:
                description: Comment describing your JSON Schema
                type: object
                required: false
                additionalProperties: true
                properties:
                  b:
                    type: string
                    required: false
              a2:
                type: array
                required: false
                items:
                  type: string
