#%Eng Demos 0.1

title: Application Modeling Framework 1.0 Engineering Demo
about: |
  This is a short demo to show the work we have been doing
  on the Application Modeling Framework.
  It will try to be a hands-on demo with a practical approach
date: 2017-11-03

product:
  code: AMF
  version: 1.0.0
  description: Something we had to build because we can
  resources:
    - https://github.com/mulesoft/amf
    - https://github.com/mulesoft-labs/amf-eng-demos

speakers:

  Pedro:
    age: 33
    email: pedro.colunga@mulesoft.com

  Antonio:
    age: 35
    email: antonio.garrote@mulesoft.com