#%ABOUT 0.1
name: ABOUT-amf
description: AMF related content to support the ABOUT tooling
homepage: https://github.com/mulesoft-labs/ABOUT
logo: https://user-images.githubusercontent.com/1119553/34323079-3fc331c0-e7ee-11e7-8882-c14750a52f74.png
copyrightHolder: MuleSoft
developmentStatus: wip
repository: https://github.com/mulesoft-labs/ABOUT-amf
keywords:
  - about
  - metadata
  - github
  - repository
licenses:
  -
    name: Apache-2.0
    url: https://spdx.org/licenses/Apache-2.0.html
contributors:
  -
    email: vromero@mulesoft.com
    givenName: Victor Romero
    roles:
      - author
      - developer
