#%Dialect 1.0
dialect: ABOUT
version: "0.1"
documents:
  library:
    declares:
      licenses: LicenseNode
      contributors: ContributorNode
  fragments:
    encodes:
      Contributor: ContributorNode
      License: LicenseNode
  root:
    encodes: ProjectNode
nodeMappings:
  ProjectNode:
    classTerm: about.SoftwareProject
    mapping:
      name:
        propertyTerm: schema-org.name
        range: string
        mandatory: true
      description:
        propertyTerm: schema-org.description
        range: string
        mandatory: false
      homepage:
        propertyTerm: about.homepage
        range: uri
        mandatory: false
      logo:
        propertyTerm: schema-org.logo
        range: uri
        mandatory: false
      copyrightHolder:
        propertyTerm: schema-org.copyrightHolder
        range: string
        mandatory: false
      developmentStatus:
        propertyTerm: about.developmentStatus
        range: string
        mandatory: true
      repository:
        propertyTerm: schema-org.codeRepository
        range: uri
        mandatory: true
      keywords:
        propertyTerm: about.keyword
        range: string
        allowMultiple: true
      discussion:
        propertyTerm: about.discussionChannel
        range: DiscussionChannelNode
        mandatory: false
        allowMultiple: true
      continuousIntegration:
        propertyTerm: about.continuousIntegration
        range: ContinuousIntegrationNode
        mandatory: false
        allowMultiple: true
      projectManagement:
        propertyTerm: about.projectManagementTool
        range: ProjectManagementNode
        mandatory: false
        allowMultiple: true
      licenses:
        propertyTerm: about.license
        range: LicenseNode
        mandatory: false
        allowMultiple: true
      contributors:
        propertyTerm: about.contributor
        range: ContributorNode
        mandatory: false
        allowMultiple: true
      partOf:
        propertyTerm: about.partOf
        range: uri
        mandatory: false
        allowMultiple: true
      hasPart:
        propertyTerm: about.hasPart
        range: uri
        mandatory: false
        allowMultiple: true
      sameAs:
        propertyTerm: about.sameAs
        range: uri
        mandatory: false
        allowMultiple: true
      forkedFrom:
        propertyTerm: about.forkedFrom
        range: uri
        mandatory: false
  DiscussionChannelNode:
    classTerm: about.DiscussionChannel
    mapping:
      name:
        propertyTerm: about.discussionChannelName
        range: string
        mandatory: false
      url:
        propertyTerm: about.discussionChannelUrl
        range: uri
        mandatory: false
      description:
        propertyTerm: schema-org.description
        range: string
        mandatory: false
      type:
        propertyTerm: about.discussionChannelType
        range: string
        mandatory: false
  ContinuousIntegrationNode:
    classTerm: about.ContinuousIntegration
    mapping:
      name:
        propertyTerm: about.serviceName
        range: string
        mandatory: false
      url:
        propertyTerm: about.serviceUrl
        range: uri
        mandatory: false
      description:
        propertyTerm: schema-org.description
        range: string
        mandatory: false
      type:
        propertyTerm: about.serviceType
        range: string
        mandatory: false
      systemUrl:
        propertyTerm: about.serviceSystemUrl
        range: uri
        mandatory: false
  ProjectManagementNode:
    classTerm: about.ProjectManagement
    mapping:
      name:
        propertyTerm: about.serviceName
        range: string
        mandatory: false
      url:
        propertyTerm: about.serviceUrl
        range: uri
        mandatory: false
      description:
        propertyTerm: schema-org.description
        range: string
        mandatory: false
      type:
        propertyTerm: about.serviceType
        range: string
        mandatory: false
      systemUrl:
        propertyTerm: about.serviceSystemUrl
        range: uri
        mandatory: false
  LicenseNode:
    classTerm: about.License
    mapping:
      name:
        propertyTerm: about.licenseName
        range: string
        mandatory: false
      url:
        propertyTerm: about.licenseType
        range: uri
        mandatory: false
  ContributorNode:
    classTerm: about.Contributor
    mapping:
      givenName:
        propertyTerm: schema-org.giveName
        range: string
        mandatory: false
      middleName:
        propertyTerm: schema-org.middleName
        range: string
        mandatory: false
      familyName:
        propertyTerm: schema-org.familyName
        range: string
        mandatory: false
      email:
        propertyTerm: schema-org.email
        range: string
        mandatory: false
      repositoryUser:
        propertyTerm: schema-org.name
        range: string
        mandatory: false
      roles:
        propertyTerm: about.role
        range: string
        mandatory: false
        allowMultiple: true
uses:
  about: ABOUT-vocabulary.raml
external:
  schema-org: http://schema.org/
