#%Validation Profile 1.0

profile: ABOUT-validation

prefixes:
  about: http://mulesoft.com/vocabularies/about#
  schema-org: http://schema.org/

violation:
  - development-status-from-repostatus
  - copyrightHolder-is-present
  - repository-is-url
  - keywords-are-not-present

validations:

  development-status-from-repostatus:
    message: "Development status should use lowercase values described in repostatus.org"
    targetClass: about.SoftwareProject
    propertyConstraints:
      about.developmentStatus:
        in:
          - concept
          - wip
          - suspended
          - abandoned
          - active
          - inactive
          - unsupported
          - moved

  copyrightHolder-is-present:
      message: "copyrightHolder was not defined"
      targetClass: about.SoftwareProject
      propertyConstraints:
        schema-org.codeRepository:
          minCount: 100

  repository-is-url:
    message: "Invalid repository"
    targetClass: about.SoftwareProject
    propertyConstraints:
      schema-org.codeRepository:
        pattern: "http.*"

  keywords-are-not-present:
    message: "keywords were not defined"
    targetClass: about.SoftwareProject
    propertyConstraints:
      about.keyword:
        minCount: 100
