#%RAML 1.0
title: TraitsResolution
/endpoint:
  put:
    queryParameters:
      put-b-alpha:
        type: string
        required: false
      put-c-alpha:
        type: string
      put-d:
        type: string
      put-e:
        type: string
      put-g-head:
        type: string
    description: Trait 'b'
  head:
    queryParameters:
      head-b-alpha:
        type: string
        required: false
      head-c-alpha:
        type: string
      head-d:
        type: string
      head-e:
        type: string
      head-g-head:
        type: string
    description: Trait 'b'
  get:
    queryParameters:
      get-a-beta?:
        type: string
      get-b-beta:
        type: string
        required: false
      get-b-alpha:
        type: string
        required: false
      get-c-alpha:
        type: string
      get-d:
        type: string
      get-e:
        type: string
      get-f:
        type: string
      get-g-head:
        type: string
    description: Trait 'a'
  post:
    queryParameters:
      post-a-beta?:
        type: string
      post-b-beta:
        type: string
        required: false
      post-b-alpha:
        type: string
        required: false
      post-c-alpha:
        type: string
      post-d:
        type: string
      post-e:
        type: string
      post-g-head:
        type: string
    description: Trait 'a'
