#%RAML 1.0
title: Example API
version: v1
/Users:
  post:
    responses:
      "200":
        body:
          application/json:
            properties:
              name:
                type: string
              lastName:
                type: string
  get:
    queryParameters:
      get:
        description: A get-token pair is required
        example: get=h8duh3uhhu38
    description: Some requests require authentication
    body: {}
    responses:
      "200":
        body:
          application/json:
            items:
              properties:
                name:
                  type: string
                lastName:
                  type: string
