#%RAML 1.0
title: test
version: 1.0
baseUri: aa-bbb.com/apis

types:
  FinancialInstitution:
    type: object
    properties:
      c: string
      d: string
      e: string
  Bank:
    type: FinancialInstitution
    properties:
      a: string
      b: string
/customers:
  displayName: Customer Resource
  /corporate:
    post:
      description: Customer data created correctly for an Organization
      body:
        application/json:
          type: Bank
          properties:
            l: string