#%RAML 1.0
title: apiEnum
/installer:
  get:
    queryParameters:
      platform:
        enum:
          - win
          - mac
          - unix
        description: override the description
        example: unix
