#%RAML 1.0
title: apiEnum

traits:
  withQueryParameters:
    queryParameters:
      platform:
        enum:
          - win
          - mac
        description: a list
        example: win

/installer:
  get:
    is: [ withQueryParameters ]
    queryParameters:
      platform: #the actual enum is [ mac, unix, win ]
        enum:
          - mac
          - unix
        description: override the description
        example: unix