#%RAML 1.0

title: test
version: 1.0

baseUri: aaa-bbb.com/apis

uses:
  shapes: ./types/shapes.raml
  traits: ./traits/traits.raml

types:
  CustomerMemberResponse: shapes.OrganizationData | shapes.PersonData

/customers:
  displayName: Customer Resource
  /corporate:
    post:
      body:
        type: shapes.NewOrganizationData
  /commercial:
    post:
      body:
        type: shapes.NewPersonData

  /{customer_id}:
    uriParameters:
      customer_id: string
    get:
      responses:
        200:
          body:
            application/json:
              type: CustomerMemberResponse
    patch:
      responses:
        200:
          body:
            application/json:
              type: shapes.CustomerPatchData
    delete:
    /accounts:
      get:
        is: [ traits.pageable, traits.sortable ]
        responses:
          200:
            body:
              application/json:
                type: shapes.BankAccountData[]
      post:
        body:
          application/json:
            type: shapes.NewBankAccountRequestData
      /{account_id}:
        uriParameters:
          account_id: string
        get:
          responses:
            200:
              body:
                application/json:
                  type: shapes.BankAccountData
        delete:
    /loans:
      get:
        is: [ traits.pageable, traits.sortable ]
        responses:
          200:
            body:
              application/json:
                type: shapes.LoanData[]
      post:
        body:
          application/json:
            type: shapes.NewLoanRequestData