#%RAML 1.0
title: test
version: "1.0"
baseUri: aaa-bbb.com/apis
/customers:
  displayName: Customer Resource
  /corporate:
    post:
      body:
        properties:
          address_country:
            type: string
          address_locality:
            type: string
          address_region:
            type: string
          postal_code:
            type: string
          street_address:
            type: string
          lei:
            type: string
          tax_id:
            type: string
          email:
            type: string
          telephone:
            type: string
          name:
            type: string
          vat_id:
            type: string
  /commercial:
    post:
      body:
        properties:
          address_country:
            type: string
          address_locality:
            type: string
          address_region:
            type: string
          postal_code:
            type: string
          street_address:
            type: string
          lei:
            type: string
          tax_id:
            type: string
          email:
            type: string
          telephone:
            type: string
          title?:
            type: string
            enum:
              - mr
              - mrs
              - ms
              - dr
          given_name:
            type: string
          family_name:
            type: string
          gender:
            type: string
            enum:
              - female
              - male
          vat_id?:
            type: string
          birth_date:
            type: date-only
  /{customer_id}:
    uriParameters:
      customer_id:
        type: string
    get:
      responses:
        "200":
          body:
            application/json:
              anyOf:
                -
                  discriminator: type
                  discriminatorValue: Organization
                  properties:
                    type:
                      type: string
                    lei:
                      type: string
                    tax_id:
                      type: string
                    email:
                      type: string
                    address:
                      properties:
                        address_country:
                          type: string
                        address_locality:
                          type: string
                        address_region:
                          type: string
                        postal_code:
                          type: string
                        street_address:
                          type: string
                    id:
                      type: string
                    name:
                      type: string
                    vat_id:
                      type: string
                -
                  discriminator: type
                  discriminatorValue: Person
                  properties:
                    type:
                      type: string
                    lei:
                      type: string
                    tax_id:
                      type: string
                    email:
                      type: string
                    address:
                      properties:
                        address_country:
                          type: string
                        address_locality:
                          type: string
                        address_region:
                          type: string
                        postal_code:
                          type: string
                        street_address:
                          type: string
                    id:
                      type: string
                    title?:
                      type: string
                      enum:
                        - mr
                        - mrs
                        - ms
                        - dr
                    given_name:
                      type: string
                    family_name:
                      type: string
                    gender:
                      type: string
                      enum:
                        - female
                        - male
                    vat_id?:
                      type: string
                    birth_date:
                      type: date-only
                    death_date?:
                      type: date-only
    patch:
      responses:
        "200":
          body:
            application/json:
              properties:
                lei?:
                  type: string
                tax_id?:
                  type: string
                email?:
                  type: string
                title?:
                  type: string
                  enum:
                    - mr
                    - mrs
                    - ms
                    - dr
                name?:
                  type: string
                family_name?:
                  type: string
                gender?:
                  type: string
                  enum:
                    - female
                    - male
                vat_id?:
                  type: string
                birth_date?:
                  type: date-only
                death_date?:
                  type: date-only
                address_country?:
                  type: string
                address_locality?:
                  type: string
                address_region?:
                  type: string
                postal_code?:
                  type: string
                street_address?:
                  type: string
    delete: {}
    /accounts:
      get:
        queryParameters:
          offset?:
            type: integer
            default: 10
            minimum: 0
            description: The `offset` parameter specifies the first entry to return from a collection.
          sort?:
            type: string
            example: name,-age
          limit?:
            type: integer
            default: 50
            minimum: 1
            description: The `limit` parameter restricts the number of entries returned.
          page?:
            type: integer
            default: 1
            minimum: 1
            description: The `page` parameter specifies the page of results to return.
        responses:
          "200":
            body:
              application/json:
                items:
                  properties:
                    id:
                      type: string
                    account_number:
                      type: string
                    accountType:
                      type: string
                      enum:
                        - standard
                        - saver
                    amount:
                      properties:
                        value:
                          type: number
                        currency:
                          type: string
                    lei:
                      type: string
                    fees_and_comissions:
                      type: string
                    review_state:
                      type: string
                      enum:
                        - requested
                        - cancelled
                        - opened
                        - closed
                    interest_rate:
                      type: number
                    annual_interest_rate:
                      type: number
                    minimum_inflow:
                      properties:
                        value:
                          type: number
                        currency:
                          type: string
                    overdraft_limit:
                      properties:
                        value:
                          type: number
                        currency:
                          type: string
      post:
        body:
          application/json:
            properties:
              accountType:
                type: string
                enum:
                  - standard
                  - saver
      /{account_id}:
        uriParameters:
          account_id:
            type: string
        get:
          responses:
            "200":
              body:
                application/json:
                  properties:
                    id:
                      type: string
                    account_number:
                      type: string
                    accountType:
                      type: string
                      enum:
                        - standard
                        - saver
                    amount:
                      properties:
                        value:
                          type: number
                        currency:
                          type: string
                    lei:
                      type: string
                    fees_and_comissions:
                      type: string
                    review_state:
                      type: string
                      enum:
                        - requested
                        - cancelled
                        - opened
                        - closed
                    interest_rate:
                      type: number
                    annual_interest_rate:
                      type: number
                    minimum_inflow:
                      properties:
                        value:
                          type: number
                        currency:
                          type: string
                    overdraft_limit:
                      properties:
                        value:
                          type: number
                        currency:
                          type: string
        delete: {}
    /loans:
      get:
        queryParameters:
          offset?:
            type: integer
            default: 10
            minimum: 0
            description: The `offset` parameter specifies the first entry to return from a collection.
          sort?:
            type: string
            example: name,-age
          limit?:
            type: integer
            default: 50
            minimum: 1
            description: The `limit` parameter restricts the number of entries returned.
          page?:
            type: integer
            default: 1
            minimum: 1
            description: The `page` parameter specifies the page of results to return.
        responses:
          "200":
            body:
              application/json:
                items:
                  properties:
                    id:
                      type: string
                    account_number:
                      type: string
                    accountType:
                      type: string
                      enum:
                        - standard
                        - saver
                    amount:
                      properties:
                        value:
                          type: number
                        currency:
                          type: string
                    lei:
                      type: string
                    fees_and_comissions:
                      type: string
                    review_state:
                      type: string
                      enum:
                        - requested
                        - cancelled
                        - underwriting
                        - accepted
                        - opened
                        - failed
                        - closed
                    interest_rate:
                      type: number
                    annual_interest_rate:
                      type: number
                    minimum_inflow:
                      properties:
                        value:
                          type: number
                        currency:
                          type: string
                    overdraft_limit:
                      properties:
                        value:
                          type: number
                        currency:
                          type: string
                    grace_period:
                      properties:
                        value:
                          type: string
      post:
        body:
          application/json:
            properties:
              category:
                type: string
              amount:
                properties:
                  value:
                    type: number
                  currency:
                    type: string
              term:
                properties:
                  value:
                    type: string
              interest_rate:
                type: number
              down_payment:
                properties:
                  value:
                    type: number
                  currency:
                    type: string
              payment_amount:
                properties:
                  value:
                    type: number
                  currency:
                    type: string
              payment_frequency:
                type: number
              review_state:
                type: string
                enum:
                  - requested
                  - underwriting
                  - rejected
                  - accepted
                  - repaying
                  - failed
                  - closed
