#%RAML 1.0
title: Example with headers
/users:
  get:
    headers:
      aHeader:
        type: object
        properties:
          a:
            type: string
          b:
            type: integer
        example:
          a: someText
          b: 12
        description: some description
