#%RAML 1.0
---
title: Jukebox API
baseUri: http://jukebox.api.com
version: v1

types:
  song: !include jukebox-include-song.schema

resourceTypes:
  collection:
    get:
      responses:
        200:
          body:
            application/json:
              type: song
              example: |
                <<exampleItem>>

/songs:
  type:
    collection:
      exampleItem: !include jukebox-include-song.sample
  get: