#%RAML 1.0
title: API body demo
version: v1
baseUri: http://api.domain.com/

types:
  XmlRefSchema:
    description: This type has included xsd schema
    type: !include person.xsd
    example: !include person.xml
