#%RAML 1.0
title: Some API
/anEndpoint:
  get:
    responses:
      200:
        body:
          application/json:
            type: !include ../schemas/simple.json#/definitions/Person/properties/name
