#%RAML 1.0 Overlay
extends: acme-bank-api.raml

documentation:
  - title: Visión de conjunto
    content: Contenido in Spanish...
  - title: Clientes
    content: Contenido in Spanish...
  - title: Next
    content: content...

/customers:
  displayName: Clientes