#%RAML 1.0
title: test-api
description: big example test api
version: v1
baseUri: https://test-api.com

/lines:
  get:
    responses:
      200:
        body: 
          application/json:
           example: !include /examples-min.json
