#%RAML 1.0
title: datetime-only api

types:
  megaType:
    properties:
      datetime-only-1:
        type: datetime-only
        example: 2018-12-31T00:00:10.1
      datetime-only-2:
        type: datetime-only
        example: 2018-12-31T00:00:10.12
      datetime-only-3:
        type: datetime-only
        example: 2018-12-31T00:00:10.132
      datetime-only-4:
        type: datetime-only
        example: 2018-12-31T00:00:10