#%Validation Profile 1.0

description: example validation profile

profile: Test

extends: OpenAPI

warning: amf-parser.mandatory-api-version

violation:
  - jscode1

validations:

  jscode1:
    message: Example js
    targetClass: apiContract.EndPoint
    functionConstraint:
      code: |
        function(resource) {
          return testValidation(resource);
        }
      libraries: file:///tmp/validations.js
