package amf.plugins.document.apicontract.parser.spec.domain

import amf.core.client.scala.model.domain.AmfArray
import amf.core.internal.annotations.TrackedElement
import amf.core.internal.parser.YMapOps
import amf.core.internal.parser.domain.{Annotations, ScalarNode}
import amf.plugins.document.apicontract.contexts.parser.oas.OasWebApiContext
import amf.plugins.document.apicontract.parser.WebApiShapeParserContextAdapter
import amf.plugins.document.apicontract.parser.spec.common.{AnnotationParser, SpecParserOps}
import amf.plugins.document.apicontract.parser.spec.declaration.OasTypeParser
import amf.plugins.domain.apicontract.metamodel.PayloadModel
import amf.plugins.domain.apicontract.models.Payload
import amf.plugins.domain.shapes.metamodel.ExampleModel
import amf.plugins.domain.shapes.models.ExampleTracking.tracking
import org.yaml.model.{YMap, YMapEntry}

import scala.collection.mutable

case class OasContentsParser(entry: YMapEntry, producer: Option[String] => Payload)(implicit ctx: OasWebApiContext) {
  def parse(): List[Payload] = {
    val payloads = mutable.ListBuffer[Payload]()
    entry.value
      .as[YMap]
      .entries
      .foreach { entry =>
        payloads += OasContentParser(entry, producer)(ctx).parse()
      }
    payloads.toList
  }
}

case class OasContentParser(entry: YMapEntry, producer: Option[String] => Payload)(implicit ctx: OasWebApiContext)
    extends SpecParserOps {

  private def buildPayloadWithMediaType(): Payload = {
    val mediaTypeNode         = ScalarNode(entry.key)
    val mediaTypeText: String = getMediaType(mediaTypeNode)

    val payload = producer(Some(mediaTypeText)).add(Annotations(entry))
    payload.set(PayloadModel.MediaType, mediaTypeNode.string(), Annotations(entry.key))
  }

  private def getMediaType(mediaTypeNode: ScalarNode) =
    mediaTypeNode.text().toString

  def parse(): Payload = {
    val map     = entry.value.as[YMap]
    val payload = buildPayloadWithMediaType()

    ctx.closedShape(payload.id, map, "content")

    // schema
    map.key(
      "schema",
      entry => {
        OasTypeParser(entry, shape => shape.withName("schema").adopted(payload.id))(
          WebApiShapeParserContextAdapter(ctx))
          .parse()
          .map { s =>
            ctx.autoGeneratedAnnotation(s)
            payload.set(PayloadModel.Schema, tracking(s, payload.id), Annotations(entry))
          }
      }
    )

    OasExamplesParser(map, payload)(WebApiShapeParserContextAdapter(ctx)).parse()
    payload.examples.foreach { ex =>
      payload.mediaType.option().foreach(mt => ex.set(ExampleModel.MediaType, mt, Annotations.synthesized()))
      ex.annotations += TrackedElement(payload.id)
    }

    // encoding
    map.key(
      "encoding",
      entry => {
        val encodings = OasEncodingParser(entry.value.as[YMap], payload.withEncoding).parse()
        payload.fields.set(payload.id,
                           PayloadModel.Encoding,
                           AmfArray(encodings, Annotations(entry.value)),
                           Annotations(entry))
      }
    )

    AnnotationParser(payload, map)(WebApiShapeParserContextAdapter(ctx)).parse()

    ctx.closedShape(payload.id, map, "content")

    payload
  }

}
