#%RAML 1.0
title: Nitro
version: 1.0.0
baseUri: 'http://programmes.api.com/nitro/api'
mediaType:
  - application/json
  - application/xml
protocols:
  - HTTP
  - HTTPS
types:
  sometype:
    type:
      - othertype
      - someothertype
  othertype:
    properties:
      href:
        type: string
      result_type:
        type: string
  someothertype:
    properties:
      deprecated:
        type: boolean
      deprecated_since:
        pattern: '^[0-9]{4}-[0-9]{2}-[0-9]{2}.*$'
        type: string
      replaced_by:
        type: string