#%RAML 1.0 Library

types:

  SuperType:
    properties:
      unionProp?:
        type: date-only | nil

  BaseType:
    type: SuperType
    properties:
      unionProp?:
        type: date-only | nil

