#%RAML 1.0
title: api
schemas:
  mySchema: |
    {
      "$schema": "http://json-schema.org/draft-04/schema#",
      "title": "My schema",
      "description": "My description",
      "type": "object",
      "properties": {
        "myProperty": {
          "type": [
            "string",
            "null"
          ],
          "default": null
        }
      }
    }
