#%RAML 1.0 NamedExample

header: !include header-success.raml
data:
  pagination: !include pagination.raml
  customers:
    -
      id: 1
      name: Customer Name 1
    -
      id: 2
      name: Customer Name 2