#%RAML 1.0 Library
# This is the file /libraries/securitySchemes.raml
usage: 
securitySchemes: 
  basicAuth:
    type: Basic Authentication
    description: |
      Each request must contain the headers necessary for basic authentication.
    describedBy: 
      headers: 
        Authorization:
          description: |
            Used to send the Base64 encoded "username:password" or 
            "client ID: client secret" credentials
          type: string
      responses: 
        401:
          description: |
            Unauthorized. Either the provided username and password
            combination is invalid, or the user is not allowed to
            access the content provided by the requested URL.
          body: 
            application/json:
              example: |
                {
                  "message": "Either the provided credentials are invalid, or the user is not allowed to access the content provided by the requested URL"
                  "code": "1001 <example code. Replace with your own error code>"
                }
  
  oAuth_2_0:
    type: OAuth 2.0
    description: 
    describedBy: 
      headers:
        Authorization:
          description: |
            Used to send a valid OAuth 2 access token. Do not use
            with the "access_token" query string parameter.
          type: string
      queryParameters:
        access_token:
          description: |
            Used to send a valid OAuth 2 access token. Do not use with
            the "Authorization" header.
          type: string
      
    settings: 
      authorizationUri: http://anypoint.mulesoft.com/api/v1/authorize
      accessTokenUri: http://anypoint.mulesoft.com/api/v1/authorize
      # customize the authorization grants depending on need
      authorizationGrants: [authorization_code,implicit,client_credentials]