#%RAML 1.0 DataType

description: Root batchnumbers create output resource
type: object
properties:
  clientid:
    type: string
    example: "ec84c9329234s"
  interface:
    type: string
    example: "JDE_123_INBOUND"
  batchnumber:
    type: string
    example: "00001"
  locked:
    type: boolean
    example: false