#%RAML 1.0 SecurityScheme
type: x-{other}
describedBy: 
  headers: 
    client_id:
    client_secret:
  responses: 
    401:
      body: 
        application/json:
          example:
            message: Unauthorized access