#%RAML 1.0
title: master
protocols:
  - http
baseUri: api.com/master
annotationTypes:
  User:
    type: object
    additionalProperties: true
    properties:
      age:
        required: false
        type: integer
      name:
        required: true
        type: string
(User):
  name: mike
  height: 178
