#%Mule Agent Configuration 0.1

websockets:
  test:
    ref: websocket.transport
    security:
      keyStorePassword: fefe
      keyStoreAlias: agent
      keyStoreAliasPassword: password

transports:
  websocket.transport: test
#      security:
#        keyStorePassword: fefe
#        keyStoreAlias: agent
#        keyStoreAliasPassword: password

#services:
#  api.manager.service:
#    rate.limiting: !include


#
#
#  rest.agent.transport:
#    port: 8888
