#%RAML 1.0 DataType

type: object
description: LocalContributor Model
properties:
  id:
    type: string
    example: "42472"
  href:
    type: string
    example: https://svcsqa.harpercollins.com/GlobalIdentifiers/v1/LocalAuthors/HCUS/42472
  authorCountry:
    type: string
    example: USA
  authorFirstName:
    type: string
    example: Veronica
  authorLastName:
    type: string
    example: Bartles
  authorNameFull:
    type: string
    example: Veronica Bartles
  authorState:
    type: string
    example: PA
  description:
    type: string
    example: "This is a description"  
  dateLastUpdated:
    type: string
    example: 11/24/2015 10:24:11 AM
  globalAuthorID:
    type: string
    example: "880000030958"
  mapped:
    type: boolean
    example: false
  modifiedBy:
    type: string
    example: PIX Auto Update
  owningEntity:
    type: string
    example: HCUS