#%RAML 1.0 DataType

description: Root GlobalContributor resource
type: object
properties:
  id:
    type: string
    example: "880000030958"
    required: false
  name:
    type: string
    example: none
    required: false
  owningEntity:
    type: string
    required: false
  globalWorkId:
    type: string
    example: "20801"
    required: false