#%RAML 1.0

title: ACME Banking HTTP API
version: 1.0

baseUri: acme-banking.com/apis

uses:
  shapes: ./types/shapes.raml
  traits: ./traits/traits.raml

types:
  CustomerMemberResponse: shapes.OrganizationData | shapes.PersonData

/customers:
  displayName: Customer Resource
  /corporate:
    post:
      description: Customer data created correctly for an Organization
      body:
        type: shapes.NewOrganizationData
  /commercial:
    post:
      description: Customer data created correctly for a Person
      body:
        type: shapes.NewPersonData

  /{customer_id}:
    uriParameters:
      customer_id: string
    get:
      description: Returns Customer data
      responses:
        200:
          body:
            application/json:
              type: CustomerMemberResponse
    patch:
      description: Updates Customer data
      responses:
        200:
          body:
            application/json:
              type: shapes.CustomerPatchData
    delete:
      description: Removes a Customer from the system
    /accounts:
      get:
        is: [ traits.pageable, traits.sortable ]
        description: Returns a collection accounts
        responses:
          200:
            body:
              application/json:
                type: shapes.BankAccountData[]
      post:
        description: Requests the creation of a new BankAccount
        body:
          application/json:
            type: shapes.NewBankAccountRequestData
      /{account_id}:
        uriParameters:
          account_id: string
        get:
          description: Returns BankAccount data
          responses:
            200:
              body:
                application/json:
                  type: shapes.BankAccountData
        delete:
          description: Removes a BankAccount from the system
    /loans:
      get:
        is: [ traits.pageable, traits.sortable ]
        description: Returns a collection accounts
        responses:
          200:
            body:
              application/json:
                type: shapes.LoanData[]
      post:
        description: Requests the creation of a new Loan
        body:
          application/json:
            type: shapes.NewLoanRequestData
        responses:
          201:
            body:
                type: string