#%RAML 1.0
title: Escape Test
protocols:
  - http
baseUri: localhost/escape
/v1:
  /{uri%Par$am}:
    uriParameters:
      uri%Par$am:
        type: string
        description: A URI param with problematic characters.
    post:
      headers:
        head#$%$#er1:
          type: string
        he@a$d@er^^@2#:
          type: integer
      queryParameters:
        queryParam<1>:
          type: string
          required: true
          description: queryParam<1> description.
        queryParam??2:
          type: string
          required: false
        quer%yPar^^am3:
          type: string
          required: false
      body:
        application/json:
          type: object
          properties:
            ip:
            type:
              type: string
      responses:
        "200":
          body:
            application/json:
              type: any
              example:
                success: true
