#%RAML 1.0
title: Escape Test
baseUri: localhost/escape
protocols:
  - http
/v1:
  /{uri%Par$am}:
    post:
      queryParameters:
        queryParam<1>:
          description: queryParam<1> description.
          required: true
          type: string
        queryParam??2:
          required: false
          type: string
        quer%yPar^^am3:
          required: false
          type: string
      headers:
        head#$%$#er1:
          type: string
        he@a$d@er^^@2#:
          type: integer
      body:
        application/json:
          type: object
          properties:
            ip:
            type:
              type: string
      responses:
        "200":
          body:
            application/json:
              type: any
              example:
                success: true
    uriParameters:
      uri%Par$am:
        description: A URI param with problematic characters.
        type: string
