#%RAML 1.0 Extension
extends: master.raml
title: overlay
description: some overlaid description

traits:
  secondary:
    description: secondary description
# THIS IS THE PROBLEM!!!!
/master:
  get:
    is: [secondary]
