#%RAML 1.0 Extension
extends: main.raml
title: overlay
description: some overlaid description

traits:
  secondary:
    description: secondary description
# THIS IS THE PROBLEM!!!!
/main:
  get:
    is: [secondary]
