#%RAML 1.0 Extension
extends: file://amf-client/shared/src/test/resources/org/raml/parser/extensions/simple-properties/example/master.raml
types:
  User:
    example:
      name: pipo
    type: object
