#%RAML 1.0
title: My API With Types
types:
  Person:
    discriminator: kind
    properties:
      kind:
        type: string
      name:
        type: string
    type: object
  Employee:
    type: Person
    properties:
      employeeId:
        type: string
  User:
    type: Person
    properties:
      userId:
        type: string
