#%RAML 1.0 NamedExample
name: Michelle Ruiz
email: mruiz0@qq.com
phone: 1-(951)768-8479
billingAddress:
  line:
    - Eastlawn 42
  city: Riverside
  state: California
  postalCode: "92513"
  country: USA
shippingAddress:
  line:
    - South
    - "07"
  city: Houston
  state: Texas
  postalCode: "77045"
  country: USA
