#%RAML 1.0
title: opm-sys

description: The intent of this API is to provide a consistent/standardized mechanism to activate Resources. It includes the model definition as well as all available operations.
version: v1
baseUri: https://esb.lla.com/opm-sys/v1

traits:
    CommonError:
        responses:

          503:
            description: |
              Service Unavailable - temporary maintenance of service, try again later. The implication is that this is a temporary condition which will be alleviated after some delay. If known, the length of the delay will be indicated in a Retry-After header. If no Retry-After is given, the client SHOULD handle the response as it would for a 500 response. Note: The existence of the 503 status code does not imply that a server will use it when becoming overloaded. Servers may simply refuse the connection.
            headers:
              Retry-After:
                description: Instructs the client to try again later. Value could be a specified period of time (in seconds) or a HTTP-date.
                type: integer | string
                required: false
                example: "120"
/{businessId}:

    patch:
      description: This operation allows partial updates of a resource entity.
      displayName: resourceById
      is : [CommonError]