#%RAML 0.8
title: API
mediaType: application/atom+xml
schemas:
  - atom: !include schemas/atom.xsd
resourceTypes:
  - emailed:
      get?:
        responses:
          200:
            body:
              application/atom+xml:
                schema: atom
      post?:
        responses:
          201:
            body:
              application/atom+xml:
                schema: atom

/contacts:
  type: emailed
  get:
    responses:
      200: 
        body: 
          application/atom+xml:
            example: !include examples/contact.xml
  post: 
    responses:
      201: 
        body:
          application/atom+xml: 
            example: !include examples/contact.xml