#%RAML 0.8
title: API
version: 1.0

traits:
  - myTrait:
      responses:
        500:
          body:
            application/json:
              schema: !include schema.json

resourceTypes:
  - myRt:
      post:
        responses:
          500:
            body:
              application/json:
                schema: !include schema.json


/endpointA:
  post:
    is: [myTrait]
    responses:
      500:
        body:
          application/json:
            schema: !include schema.json

/endpointB:
  type: myRt
  post:
    responses:
      500:
        body:
          application/json:
            schema: !include schema.json
