properties:
  name:
    type: string
get:
  queryParameters:
    <<queryParamName>>:
      description: Return <<resourcePathName>> that have their <<queryParamName>> matching the given value
    <<fallbackParamName>>:
      description: If no values match the value given for <<queryParamName>>, use <<fallbackParamName>> instead