#%RAML 1.0
version: refactor
title: experience
/customers:
  get:
    responses:
      "200":
        body:
          application/json:
            properties:
              firstName:
                type: string
              lastName:
                type: string
  put:
    responses:
      "200": {}
  delete:
    responses:
      "200": {}
  description: |
    an individual customer within the collection
    of customers
