#%RAML 1.0
version: refactor
title: experience

uses:

  common: common-types.raml
  customer: customer-types.raml
  collection: collections.raml


/customers:
    type:
      collection.collectionMember:
        collectionMemberResponseType: customer.CustomerResponse
        collectionMemberPrototypeType: customer.Customer
    get:
      responses:
        200: