#%RAML 1.0 SecurityScheme

type: OAuth 2.0
describedBy:
  headers:
    Authorization:
      description: |
         the first description
      type: string
  queryParameters:
    access_token:
      description: |
         simple description
      type: string
  responses:
    401:
      description: |
          a description
    403:
      description: |
          another description
settings:
  authorizationUri: https://www.false.com/1/oauth2/authorize
  accessTokenUri: https://api.false.com/1/oauth2/token
  authorizationGrants: [ authorization_code, implicit, 'urn:ietf:params:oauth:grant-type:false2-false' ]
  scopes: [ "ADMINISTRATOR" ]