#%RAML 1.0 Library

types:
  A:
    type: union
    anyOf:
      - type: array
        items:
          type: object
          additionalProperties: true
          properties:
            a:
              required: true
              type: string
            b:
              required: true
              type: nil
      - type: array
        items:
          type: object
          additionalProperties: true
          properties:
            a:
              required: true
              type: integer
            b:
              required: true
              type: nil
