#%RAML 1.0 Library

types:
  Phone:
    properties:
      manufacturer: string
      numberOfSIMCards: number
      kind: string
  Device:
    properties:
      manufacturer: string
      numberOfUSBPorts: number
      kind: string

  Main:
    properties:
      phone: Phone
      device: Phone | Device
    type: Phone | Device