#%RAML 1.0 DataType
type: union
anyOf:
  - properties:
      a:
        type: string
    type: object
  - properties:
      b:
        type: string
    type: object
  - properties:
      c:
        type: string
    type: object
  - properties:
      d:
        type: string
    type: object