#%RAML 1.0 Trait
headers:
  client_id:
    type: string
    description: client Id provided by API Manager
    required: true
  client_secret:
    type: string
    required: true
    description: The Client secret key provided by the API Manager
responses:
  401:
    description: Unauthorized or invalid client application credentials
  500:
    description: Bad response from authorization server