#%RAML 1.0 Library
types:
  AnimalWithAddress:
    type: object
    additionalProperties: true
    properties:
      address:
        required: true
        type: string
  Cat:
    type: union
    anyOf:
      -
        type: object
        additionalProperties: true
        properties:
          address:
            required: true
            type: string
          age:
            required: true
            type: integer
      -
        type: object
        additionalProperties: true
        properties:
          address:
            required: true
            type: string
          age:
            required: true
            type: number
