#%RAML 1.0 DataType
type: union
anyOf:
  -
    type: object
    additionalProperties: true
    properties:
      a:
        type: string
        required: true
      b:
        type: string
        required: true
  -
    type: object
    additionalProperties: true
    properties:
      a:
        type: string
        required: true
      b:
        type: integer
        required: true
