#%RAML 1.0 Library

resourceTypes: 
  collection:
    get?:
      responses: 
        200:
          body:
            application/json:
              example: |
                <<exampleCollectionResponse>>
