#%RAML 1.0
title: API
types:
  SimpleType1:
    properties:
      property1:
        type: string
      property2:
        type: string
  SimpleType2:
    properties:
      property1:
        type: number
      property2:
        type: number
  SimpleUnion:
    type: SimpleType1 | SimpleType2
  TypeWithUnionProps:
    properties:
      unionArray: SimpleUnion[]
    example:
      unionArray:
        -
          property1: 1
          property2: 2
        -
          property1: 1
          property2: 2
    type: object
