#%RAML 1.0
title: hello
mediaType: application/json
types:
  MyType:
    properties:
      x:
        type: string
/hello:
  get: {}
  post:
    responses:
      202:
        body:
          application/json:
            properties:
              key:
                properties:
                  x:
                    type: string
                example:
                  x: lala
                type: object
            type: object
