#%RAML 1.0 ResourceType
uses:
  traitsLibrary: ../libraries/TraitsLibrary.raml
get?:
  is: 
    - traitsLibrary.hasGetResResponse
  description: Retrieve a specific <<resourcePathName | !singularize>>
  displayName: Get <<resourcePathName | !singularize>> by <<resourcePathName | !singularize>> ID
patch?:
  description: Update specific data of <<resourcePathName | !singularize>> 
  displayName: Update <<resourcePathName | !singularize>> by <<resourcePathName | !singularize>> ID
  body:
  responses: 
    204:
    404:
      body:
        application/json:
          type: !include ../dataTypes/CustomErrorMessage.raml
delete?:
  responses: 
    204:
    404:
      body:
        application/json:
          type: !include ../dataTypes/CustomErrorMessage.raml
put?:
  description: Update all data in <<resourcePathName | !singularize>> 
  displayName: Update <<resourcePathName | !singularize>> by <<resourcePathName | !singularize>> ID
  body:
    application/json:
      type: <<resourcePathName | !singularize | !uppercamelcase>>
  responses:
    204:
    404:
      body:
        application/json:
          type: !include ../dataTypes/CustomErrorMessage.raml