#%RAML 1.0
title: My API With Types
types:
  Initial_comments:
    minProperties: 2
    properties:
      comment_id?:
        type: number
      initial_comments?:
        type: string
    example:
      initial_comments: mm
    type: object
