#%RAML 1.0
title: My API With Types
types:
  Dog:
    properties:
      bite:
        type: string
    type: object
  Cat:
    properties:
      claw:
        type: string
    type: object
  Parrot:
    properties:
      feathers:
        type: string
    type: object
  HasHome:
    properties:
      livesInside:
        type: boolean
    type: object
  IsOnFarm:
    properties:
      livesOutside:
        type: boolean
    type: object
  HomeAnimal:
    type:
      - HasHome | IsOnFarm
      - Dog | Cat | Parrot
    properties:
      discriminator:
        type: string
