#%RAML 1.0
version: v1
title: test
protocols:
  - HTTP
  - HTTPS
/games:
  description: Retrieves type of game entities.
  get:
    headers:
      X-No-Cache:
        description: Define if it is cacheable
        required: false
        type: boolean
        default: true
      X-Reset-Cache:
        description: Set whether to reset the cache
        required: false
        type: boolean
        default: false
      X-Integration-Id:
        description: Represents the integrator identification.
        required: false
        type: string
      X-Origin-Id:
        description: Source identification.
        required: false
        type: string
      X-Origin-Request-Id:
        description: Consumer request identification.
        required: false
        type: string
      X-Channel-Id:
        description: Channel identification.
        required: false
        type: string
    displayName: all games
    body: {}
    responses:
      200:
        headers:
          X-Integration-Id:
            description: Represents the integrator identification.
            required: false
            type: string
          X-Origin-Id:
            description: Source identification.
            required: false
            type: string
          X-Origin-Request-Id:
            description: Consumer request identification.
            required: false
            type: string
          X-Channel-Id:
            description: Channel identification.
            required: false
            type: string
        body: {}
      500:
        headers:
          X-Integration-Id:
            description: Represents the integrator identification.
            required: false
            type: string
          X-Origin-Id:
            description: Source identification.
            required: false
            type: string
          X-Origin-Request-Id:
            description: Consumer request identification.
            required: false
            type: string
          X-Channel-Id:
            description: Channel identification.
            required: false
            type: string
        body: {}
