#%RAML 1.0
version: v1
title: test
protocols:
  - HTTP
  - HTTPS
/games:
  description: Retrieves type of game entities.
  get:
    headers:
      X-No-Cache:
        description: Define if it is cacheable
        required: false
        type: boolean
        default: true
      X-Reset-Cache:
        description: Set whether to reset the cache
        required: false
        type: boolean
        default: false
    displayName: all games
    body: {}
