#%RAML 1.0
title: ZEncoder API
baseUri: https://app.zencoder.com/api
documentation:
 - title: ホーム
   content: |
     _Zencoder API_ドキュメントへようこそ。 _Zencoder API_
     アプリケーションをエンコードサービスに接続できます
     Webインターフェースを経由せずにビデオをエンコードします。君は
     また、[統合ライブラリ]（https://app.zencoder.com/docs/faq/basics/libraries）
