#%RAML 1.0
title: エンドツーエンドのテスト日本サポート
documentation:
  - title: 法的通知
    content: |
      # 契約の一般条件：
      **ユーザー条件**
      _ユーザーは以下を引き受け、コミットします。_
      1. 違法な目的または効果のために、サイトまたはサイトを通じて提供されるサービスを使用しないでください。
      2. サイトで見つかったデータを破壊、変更、または損傷しないでください。
      **外部リンク**
      このWebサイトは、次のような他の自社およびサードパーティのWebサイトへのリンクを提供します。
      - ブログ
      - 道具
      - 資源

types:
  File:
    type: file
    fileTypes:
      - "*/*"
      - 画像/png
      - 画像/jpeg
      - 画像/gif
  ユーザーID:
    type: string
    example: ジョン.ドウ
  ユーザーアカウント:
    type: string
    enum:
      - 個人的な
      - 会社
      - グルパル
    example: 個人的な
  ユーザー:
    properties:
      画像:
        type: File[]
      メンバーシップ:
        type: ユーザー | ユーザーアカウント
    example:
      value:
        画像:
          - ファイル名
        メンバーシップ: 個人的な
securitySchemes:
  基本的な:
    description: このAPIは基本認証をサポートしています。
    type: OAuth 1.0
    settings:
      requestTokenUri: https://api.dropbox.com/1/oauth/request_token
      authorizationUri: https://www.dropbox.com/1/oauth/authorize
      tokenCredentialsUri: https://www.dropbox.com/1/oauth/authorize
securedBy:
  - 基本的な
/ユーザー:
  post:
    headers:
      asd:
        example: 無記名 f7f7bffc-01af-4d40
        type: string
    body:
      application/json:
        type: ユーザー
/ユーザー/{ユーザーID}:
  get:
    responses:
      201:
        body:
          application/json:
            type: ユーザー
  uriParameters:
    ユーザーID?:
      default: ジョン.ドウ
      type: ユーザーID
      example: ジョン.ドウ