#%RAML 1.0
title: test title
description: test description
version: "1.1"
(amf-termsOfService): terms of service
/level-zero:
  displayName: One display name
  description: and this description!
  get:
    displayName: Some title
    queryParameters:
      param1:
        description: Some descr
        properties:
          name:
            type: string
          lastName:
            type: string
          address:
            properties:
              city:
                type: string
              street:
                type: string
              number:
                type: integer
              postal:
                type: integer
            (amf-dependencies):
              city:
                - postal
              street:
                - number
                - postal
                - city
              number:
                - street
    body:
      application/raml:
        properties:
          credit_card:
            type: integer
          city:
            type: string
          street:
            type: string
          number:
            type: integer
          postal:
            type: integer
        (amf-dependencies):
          credit_card:
            - city
            - postal
          street:
            - number
            - postal
            - city
          number:
            - street
baseUri: api.example.com/path
mediaType:
  - application/yaml
protocols:
  - http
  - https
