#%RAML 1.0 DataType
type: object
properties: 
  customerID: string
  prefix?: string
  firstName: string
  lastName: string
  suffix?: string
  displayName: string
  address: !include Address.raml
  phone: string
  email: string
  ssn: string
  dateOfBirth: date-only