#%RAML 1.0 ResourceType

uses:
    spiViewerLib: ../library/spiViewerLibrary.raml

get:
  is: [spiViewerLib.hasAcceptHeader,spiViewerLib.cacheable-trait]
  description: Retrieve a list of <<resourcePathName | !singularize>> 
  displayName: Get <<resourcePathName | !singularize>>
  responses: 
    200:
      body:
        application/json:
          type: <<customDataType>>[]  
        application/xml:
          type: <<customDataType>>[]
    404:
      body:
        application/json:
          type: <<customErrorType>>
        application/xml:
          type: <<customErrorType>>
    500:
      body:
        application/json:
          type: <<customErrorType>>
        application/xml:
          type: <<customErrorType>>