#%RAML 1.0 Trait

responses: 
  415:
    body:
      application/json:
        type: !include ../dataTypes/error-message.raml
        example: |
          { "message" : "Not Supported  Content-Type"}
  429:
    headers:
      Retry-After:
        type: number
        examples:
          after-seconds: 120
    body:
      application/json:
        type: !include ../dataTypes/error-message.raml
        example: |
          {"message" : "Too Many Request" }