#%RAML 1.0 Trait

queryParameters: 
  sort:
    description: Sorting field and direction to use to retrieve the results.
    required: false
    type: string
  cursor: 
    description: Cursor from which we will retrieve the results.
    type: string