#%RAML 1.0 Trait

queryParameters: 
  sort:
    description: Sorting field and direction to use to retrieve the results.
    type: string
  offset: 
    description: Offset used to retrieve the results.
    type: integer
  limit: 
    description: Maximum records to retrieve.
    type: integer