#%RAML 1.0
title: Illustrate query parameter variations
/locations:
  get:
    queryString:
      type:
        -
          type: nil
        - lat-long | loc
types:
  schema:
    properties:
      lat:
        type: number
      "null":
        type: number
