#%RAML 1.0
title: Illustrate query parameter variations
types:
  lat-long:
    properties:
      lat:
        type: number
      long:
        type: number
  loc:
    properties:
      location:
        type: nil
  paging:
    properties:
      start:
        type: number
      page-size:
        type: number
/locations:
  get:
    queryString:
      type:
        - paging
        - lat-long | loc
