#%RAML 1.0
types:
  Person:
    properties:
      name: string
      description: string
      age: integer
      address:
        properties:
          street: string
          number: integer
title: test types
description: empty api only for test types