#%RAML 1.0
title: API

baseUri: /some/base/uri

/levelzero:
  /level-one:
    displayName: One display name
    description: and this description!
    get:
      displayName: Some title
      description: Some description
      (deprecated): true
      (summary): This is a summary
      (externalDocs):
        url: urlExternalDocs
        description: descriptionExternalDocs
      protocols:
        - http
        - https
    post:
      displayName: Some title
      description: Some description
      (externalDocs):
        url: urlExternalDocs
        description: descriptionExternalDocs
      protocols:
        - http
        - https