#%EventedAPIDialect 0.1

uses:
  transports: Libraries/EventTransportLibrary.raml
  bankingEvents: Libraries/BankingEventLIbrary.raml


# Declarations

subjects:
  subject123:
    eventPattern: pub-sub

channels:
  ch123:
    channelID: 1
    subjects:
      - subject123

producers:
  producer1:
    producerID: 1
    applicationID: app123
    userID: me
    producerChannel: ch123
    producerSubject: subject123

consumers:
  consumer1:
    consumerID: 1
    applicationID: app123
    userID: me
    consumerChannel: ch123
    consumerSubject: subject123

# The main encoded element

apiPersona: All
eventProducer: consumer1
eventConsumer: producer1
