#%RAML 1.0
title: some title
/sample:
  post:
    body:
      application/json:
        type: object

types:
  long-98:
    type: number
    maximum: 9999999999999998
  long-99:
    type: number
    maximum: 9999999999999999
  long00:
    type: number
    maximum: 10000000000000000
  long01:
    type: number
    maximum: 10000000000000001
  long02:
    type: number
    maximum: 10000000000000002
  long03:
    type: number
    maximum: 10000000000000003
