#%RAML 1.0 Vocabulary

vocabulary: amc
base: http://mulesoft.com/vocabularies/amc#

usage: The common vocabulary to define AMC configurations

external:
  schema-org: http://schema.org/

classTerms:

  Secret:
    displayName: Secret Class
    description: Reference to a Secret that is store in the Customer Secret Vault
    extends: schema-org.accessCode
    range: string

  Asset:
    displayName: Secret Class
    description: Reference to a Secret that is store in the Customer Secret Vault
    extends: schema-org.accessCode
    range: string