#%RAML 1.0
title: test
types:
  jsonSchema:
    type: object
    properties:
      street:
        type: string
      number:
        type: number
      location:
        type: object
        properties:
          state:
            type: string
          country:
            type: string
