#%RAML 1.0
title: my api
version: 1.0
resourceTypes:
  rt1:
    <<method>>:
/inferredNull:
  type:
    rt1:
      method:
/emptyString:
  type:
    rt1:
      method: "   "
/explicitNull:
  type:
    rt1:
      method: null