#%RAML 1.0
title: Example of request bodies
mediaType: application/json
/users:
  put:
    body:
      application/json:
        properties: 55
  post:
    body:
      application/json:
        properties: asd

  get:
    body:
      application/json:
        properties:



