#%RAML 0.8
title: Sales Order
version: 0.1
schemas:
  - salesOrder: |
      {
              "type": "object",
              "$schema": "http://json-schema.org/draft-04/schema#",
              "title": "Sales Order",
              "description": "An Inchcape Sales Order",
              "properties": {
                "channel": {
                  "deiscription": "",
                  "type": "string",
                  "maxLength":
                }
              }
            }