#%RAML 1.0

title: test

types:
  BaseObject:
    type: object
    properties:
      items:
        type: array
        items: any

  CustomObjectList:
    type: BaseObject
    properties:
      items:
        type: array
        items: object[]
