#%RAML 1.0
title: Covéa Partners Experience API
types:
  Update: updateClaimWithDamageRequest
  updateClaimWithDamageRequest:
    properties:
      operation:
         description: Available path operations
         type: string