#%RAML 1.0
title: API
version: 1.0
types:
  RootType:
    xml:
      name: RootType
    properties:
      Property1:
        type: string
        xml:
          attribute: true
          name: Property1
