#%RAML 1.0
title: An example file demonstrating the usage of the commerce cloud standards library

types:
  SomeType:
    type: object
    properties:
      someProp: boolean
      "someProp":
          type: string

