#%RAML 1.0
title: Invoice API
mediaType: application/json

types:
  IsOnFarm:
    type: object
    properties:
      farmName: string
  HasHome:
    type: object
    properties:
      homeAddress: string
  Cat:
    type: object
    properties:
      name: string
      color: string
  Dog:
    type: object
    properties:
      name: string
      fangs: string
  Parrot:
    type: object
    properties:
      talks: boolean
      words: [string]
  HomeAnimal: [ HasHome | IsOnFarm ,  Dog | Cat | Parrot ]
