#%RAML 1.0
title: New API
baseUri: test.com
mediaType:
  - application/json
version: "1.0"
protocols:
  - HTTP
securitySchemes:
  basic:
    type: Basic Authentication
securedBy: [ basic ]
/ping:
  get:
    responses:
      200:
        description: ""