#%RAML 1.0
types:
  StringType:
    type: string
  ByteType:
    type: string
    (format): byte
  BinaryType:
    type: string
    (format): binary
  PasswordType:
    type: string
    (format): password
  IntegerType:
    type: integer
  NumberType:
    type: number
  BooleanType:
    type: boolean
  DateTimeType:
    type: datetime
  DateTimeOnlyType:
    type: datetime-only
  TimeOnlyType:
    type: time-only
  DateOnlyType:
    type: date-only
  ObjectType:
    type: object
title: test title