#%RAML 1.0
title: test title
types:
  StringType:
    type: string
  AnyType:
    type: any
  IntegerType:
    type: integer
  DateTimeOnlyType:
    type: datetime
  TimeOnlyType:
    type: time-only
    format: time-only
  Nulltype:
    type: nil
  FileType:
    type: file
    maxLength: 307200
    fileTypes:
      - image/jpeg
      - image/png
  BinaryType:
    type: string
    (format): binary
  DateTimeType:
    type: datetime
  DateOnlyType:
    type: date-only
    format: date-only
  BooleanType:
    type: boolean
  ObjectType:
    type: object
  ByteType:
    type: string
    (format): byte
  NumberType:
    type: number
  PasswordType:
    type: string
    format: password