#%RAML 1.0
title: ApiManagementClient
types:
  AdditionalRegion:
    description: Description of an additional API Management resource location.
    properties:
      vpnconfiguration:
        type: VirtualNetworkConfiguration
  VirtualNetworkConfiguration:
    description: Configuration of a virtual network to which API Management service is deployed.
    properties:
      vnetid:
        description: The virtual network ID. This is typically a GUID. Expect a null GUID by default.
        type: string
        required: false