#%RAML 1.0
title: test title
description: test description
(termsOfService): terms of service
version: 1.1
(license):
  url: licenseUrl
  name: licenseName
mediaType:
  - application/yaml
protocols:
  - http
  - https
(contact):
  url: contactUrl
  name: contactName
  email: contactEmail
(externalDocs):
  url: externalDocsUrl
  description: externalDocsDescription
baseUriParameters:
  testUriParameter:
    description: testUriDisplay
    required: false
/levelzero:
  displayName: Name
/levelzero/level-one:
  displayName: One display name
  description: and this description!
  uriParameters:
    two:
      required: false
  get:
    displayName: Some title
    queryParameters:
      param1:
        description: Some descr
      param2?:
        type: string
    headers:
      testHeader:
        type: string
        required: true
    responses:
      200:
        description: 200 descr
        headers:
          Time-Ago:
            type: integer
            required: true
      404:
        description: Not found!
    body:
      application/json: string
baseUri: api.example.com/path