#%RAML 1.0
title: test title
description: test description
protocols:
  - http
  - https
/customers:
  displayName: Customer
  description: Customer description
/clients:
  displayName: Client
  description: Client description
(license):
  name: licenseName
  url: licenseUrl