#%RAML 1.0
title: xml body inline
/top:
  get:
    body:
      application/xml:
        properties:
          firstname:
            type: string
          lastname:
            type: string
          age:
            type: integer
            minimum: 0
            maximum: 144
