#%RAML 1.0 DocumentationItem
title: Darwin Central POS Integration
content: |
    # Unilever API
    [![N|Solid](https://s3.amazonaws.com/wetfeetproduction/companies/thumb_media/14/original/unilever-logo_reasonably_small.gif?1348509554)](https://nodesource.com/products/nsolid)
    **Darwin Central POS API** would serve as a bridge between the Darwin Central AWS system and region specific DC POS instances. 
    # Note
    **Darwin Central POS API** would be the integration layer between the Darwin Central AWS system and region specific DC instances.
    
    EPOS solutions are deployed at different retailer outlets. Darwin Central System which is hosted on AWS would be connected to the country specific DC instances. Each POS system would connect to its country specific instance to push or pull data to/from Darwin Central.   