#%RAML 1.0
title: Test API
baseUri: https://example.com
protocols:
  - HTTPS

types:
  ScalarJsonSchema:
    type: |
      {
        "type": "string"
      }

/pets:
  get:
    responses:
      200:
        body:
          application/json:
            type: ScalarJsonSchema