#%RAML 0.8
title: System NTXD API
version: v1.0
##
#baseUri: http://172.16.6.65/ords/ntxdev51/v1/
baseUri: https://mocksvc.mulesoft.com/mocks/b7043573-24c3-4735-8d69-52aa8871ccfc/ords/ntxdev51/v1/

securitySchemes:
  - basic:
      type: Basic Authentication
      describedBy: