#%RAML 1.0 Dialect
dialect: ConfigurationProperties
version: 1.0
usage: This vocabulary defines the vision of how configuration values can be injected/customized in a mule artifact (application, domain, policy, etc). Specific features will be targeted to an specific runtime release.
external:
  schema-org: "http://schema.org/"
vocabularies:
  configuration: ./mule_config.raml
nodeMappings:
   MuleConfig:
      classTerm: configuration.MuleConfig
      mapping:
         displayName:
            propertyTerm: schema-org.name
            range: string
         description:
            propertyTerm: schema-org.description
            range: string
         timeouts:
            propertyTerm: timeout
            range: Timeouts
   Timeouts:
       classTerm: configuration.Timeouts
       mapping:
          httpRequestTimeout:
             propertyTerm: http-request-timeout
             range: number
          httpListenerTimeout:
             propertyTerm: http-listener-timeout
             range: number
             default: 100
raml:
   document:
     encodes: MuleConfig