#%RAML 1.0 Vocabulary
base: http://raml.org/vocabularies/async#
dialect: RAML Async
version: 0.1
usage: Vocabulary to define Asynchronous APIs
external:
  schema-org: http://schema.org/
  shacl: http://www.w3.org/ns/shacl#
  raml-doc: http://raml.org/vocabularies/doc#
classTerms:
  AsyncAPI:
    displayName: AsyncAPI
    description: |
    extends: raml-doc.RootDomainElement
    properties:
      - schema-org.title
      - schema-org.version
      - schema-org.description
      - type-declaration
      - connection
      - transport
      - endpoints
      - bindings
      - serialization
  Connection:
    displayName: Connection
    description: |
    extends: raml-doc.DomainElement
    properties:
      - host
      - port
      - scheme
      - bindings
  EndPoint:
    displayName: End Point
    description: |
    extends: raml-doc.DomainElement
    properties:
      - schema-org.description
      - pattern
      - bindings
      - parameter
      - operation
  Parameter:
    displayName: Parameter
    description: Information about the replacement options that can be used in a parametric EndPoint
    extends: raml-doc.DomainElement
    properties:
      - schema-org.name
      - schema
  AsyncOperation:
    displayName: Async Operation
    description: Each of the operations in the asynchronous interface
    extends: raml-doc.DomainElement
    properties:
      - schema-org.name
      - schema-org.description
      - message
      - bindings
      - pattern
      - serialization
  Message:
    displayName: Message
    description: Unit of data passed as the argument of an asyn operation
    extends: raml-doc.DomainElement
    properties:
      - header
      - schema
  Header:
    displayName: Header
    description: Meta information for a message
    extends: raml-doc.DomainElement
    properties:
      - schema-org.name
      - mandatory
      - schema
  Bindings:
    extends: raml-doc.DomainElement
propertyTerms:
  schema-org.title:
    description: A short, plain-text label for the API. Its value is a string.
    range: string
  schema-org.version:
    description: String identifying the version of the API.
    range: string
  schema-org.description:
    description: A substantial, human-friendly description of the API. Its value is a string and MAY be formatted using markdown.
    range: string
  type-declaration:
    description: Declarations of data types for use within the API.
    domain: AsyncAPI
    range: shacl.Shape
    extends: raml-doc.declarationProperty
  transport:
    description: String containing an identifier for the kind of transport associated to the API, bindings in the spec will target this transport value
    domain: AsyncAPI
    range: string
  connection:
    description: Optional connection details to the system providing the messaging infrastructure.
    domain: AsyncAPI
    range: Connection
  endpoints:
    description: EndPoints declared in the API
    domain: AsyncAPI
    range: EndPoint
  host:
    description: Host machine where to establish the connection
    domain: Connection
    range: string
  port:
    description: Network port for the connection in the host machine
    domain: Connection
    range: integer
  scheme:
    description: URI scheme identifying the network protocol used for the connection
    domain: Connection
    range: string
  operation:
    description: Operation supported by an EndPoint
    domain: EndPoint
    range: AsyncOperation
  parameter:
    description: Parameters that can be replaced in the identifier of an EndPoint
    domain: EndPoint
    range: Parameter
  message:
    description: Message used as argument for an asynchronous operation
    domain: AsyncOperation
    range: Message
  header:
    description: Meta-data about a message
    domain: Message
    range: Header
  bindings:
    description: Transport specific bindings for a model element
    domain:
      - AsyncAPI
      - Connection
      - EndPoint
      - AsyncOperation
    range: Bindings
  pattern:
    description: Messaging pattern implemented by an end point
    domain:
      - EndPoint
      - AsyncOperation
    range: string
  serialization:
    description: Format used to encode some data over network transport
    domain:
      - AsyncAPI
      - AsyncOperation
    range: string
  schema:
    description: Data shape associated to some element of the domain
    domain:
      - Parameter
      - Message
      - Header
    range: shacl.Shape