#%RAML 1.0 Vocabulary
usage: Vocabulary to define Asynchronous APIs

# Namespace for the RAML Async vocabulary
base: "http://raml.org/vocabularies/async#"

# Settings for the syntax declaration
vocabulary: RAML Async
version: 0.1

# 'Raw' RDF vocabularies used in RAML Async
external:
  schema-org: "http://schema.org/"
  shacl: "http://www.w3.org/ns/shacl#"
  raml-doc: "http://raml.org/vocabularies/doc#"

classTerms:

  AsyncAPI:
    displayName: AsyncAPI
    description: |
      The top level element of any RAML Async is the AsyncAPI node. It introduces some meta-information about the API like the title, version and description of the API.
      It also holds the information of the Connection, global Bindings and the EndPoints defined in the spec.
    # AsyncAPI elements can be described as stand-alone RAML documents, that's the reason we must extend
    # raml-doc.RootDomainElement as the base class for AsyncAPI
    extends: raml-doc.RootDomainElement
    properties:
      - schema-org.title
      - schema-org.version
      - schema-org.description
      - type-declaration
      - connection
      - transport
      - endpoints
      - bindings
      - serialization
    syntax:
      title:
        term: schema-org.title
        mandatory: true
      version:
        term: schema-org.version
      description:
        term: schema-org.description
      types:
        term: type-declaration
        declaration: true
      connection:
        term: connection
        collection: true
      endpoints:
        term: endpoints
        declaration: true

  Connection:
    displayName: Connection
    description: |
      The `Connection` node contains global connection information that can be used by clients to gain access to the API endpoints and use the async operations interface.
      It can be used to define a base identifier for the end points as well as to set-up specific `Bindings` for the transport layer.
      This node can also be used to define connection parameters to a 'messaging broker' in the messaging systems that using this kind of functionality.
    extends: raml-doc.DomainElement
    properties:
      - host
      - port
      - scheme
      - bindings

  EndPoint:
    displayName: End Point
    description: |
      Each of the discoverable communication units in the API with support for the asynchronous interface are defined as EndPoint nodes.
      EndPoints are defined by an identifier, the list of asynchronous operations supported and an optional set of transport bindings.
    extends: raml-doc.DomainElement
    properties:
      - schema-org.description
      - pattern
      - bindings
      - parameter
      - operation
    syntax:
      description: schema-org.description
      parameters:
        term: parameter
        collection: true
      operation:
        term: operation
        hash: schema-org.name

  Parameter:
    displayName: Parameter
    description: Information about the replacement options that can be used in a parametric EndPoint
    extends: raml-doc.DomainElement
    properties:
      - schema-org.name
      - schema
    syntax:
      name:
        term: schema-org.name
        mandatory: true

  AsyncOperation:
    displayName: Async Operation
    description: Each of the operations in the asynchronous interface
    extends: raml-doc.DomainElement
    properties:
      - schema-org.name
      - schema-org.description
      - message
      - bindings
      - pattern
      - serialization
    syntax:
      description: schema-org.description

  Message:
    displayName: Message
    description: Unit of data passed as the argument of an asyn operation
    extends: raml-doc.DomainElement
    properties:
      - header
      - schema
    syntax:
      headers:
        term: header
        collection: true

  Header:
    displayName: Header
    description: Meta information for a message
    extends: raml-doc.DomainElement
    properties:
      - schema-org.name
      - mandatory
      - schema
    syntax:
      name:
        term: schema-org.name
        mandatory: true

  Bindings:
    extends: raml-doc.DomainElement

propertyTerms:

  # AsyncAPI properties

  schema-org.title:
    displayName: title
    description: A short, plain-text label for the API. Its value is a string.
    range: string

  schema-org.version:
    displayName: version
    description: String identifying the version of the API.
    range: string

  schema-org.description:
    displayName: description
    description: A substantial, human-friendly description of the API. Its value is a string and MAY be formatted using markdown.
    range: string

  type-declaration:
    displayName: types
    description: Declarations of data types for use within the API.
    extends: raml-doc.declarationProperty
    range: shacl.Shape

  transport:
    displayName: transport
    description: String containing an identifier for the kind of transport associated to the API, bindings in the spec will target this transport value
    range: string

  connection:
    displayName: connection
    description: Optional connection details to the system providing the messaging infrastructure.
    range: Connection

  endpoints:
    displayName: endpoints
    description: EndPoints declared in the API
    range: EndPoint

  # Connection properties

  host:
    displayName: host
    description: Host machine where to establish the connection
    range: string

  port:
    displayName: port
    description: Network port for the connection in the host machine
    range: integer

  scheme:
    displayName: scheme
    description: URI scheme identifying the network protocol used for the connection
    range: string

  # EndPoint properties

  operation:
    displayName: operation
    description: Operation supported by an EndPoint
    range: AsyncOperation

  parameter:
    displayName: parameter
    description: Parameters that can be replaced in the identifier of an EndPoint
    range: Parameter

  # Operation properties

  message:
    displayName: message
    description: Message used as argument for an asynchronous operation
    range: Message

  # Message properties

  header:
    displayName: header
    description: Meta-data about a message
    range: Header

  # Common properties

  bindings:
    displayName: bindings
    description: Transport specific bindings for a model element
    range: Bindings

  pattern:
    displayName: pattern
    description: Messaging pattern implemented by an end point
    range: string

  serialization:
    displayName: serialization
    description: Format used to encode some data over network transport
    range: string

  schema:
    displayName: schema
    description: Data shape associated to some element of the domain
    range: shacl.Shape
