#%RAML 1.0 Dialect
dialect: Validation Profile
version: 1.0
usage: Dialect to describe validations over RAML documents
external:
  schema-org: http://schema.org/
  shacl: http://www.w3.org/ns/shacl#
  validation: http://raml.org/vocabularies/amf-validation#
nodeMappings:
  functionConstraintNode:
    classTerm: shacl.JSConstraint
    mapping:
      message:
        propertyTerm: shacl.message
        mandatory: true
        range: string
      code:
        propertyTerm: validation.jsCode
        pattern: ^function\(.+\)\s*\{.+\}$
        range: string
      libraries:
        propertyTerm: shacl.jsLibrary
        range: string
        allowMultiple: true
      functionName:
        propertyTerm: shacl.jsFunctionName
        range: string
  propertyConstraintNode:
    classTerm: shacl.PropertyShape
    mapping:
      message:
        propertyTerm: shacl.message
        mandatory: true
        range: string
      name:
        propertyTerm: validation.ramlPropertyId
        mandatory: true
        range: string
      pattern:
        propertyTerm: shacl.pattern
        range: string
      maxCount:
        propertyTerm: shacl.maxCount
        range: number
      minCount:
        propertyTerm: shacl.minCount
        range: number
      minExclusive:
        propertyTerm: shacl.minExclusive
        range: number
      maxExclusive:
        propertyTerm: shacl.maxExclusive
        range: number
      minInclusive:
        propertyTerm: shacl.minInclusive
        range: number
      maxInclusive:
        propertyTerm: shacl.maxInclusive
        range: number
      in:
        propertyTerm: shacl.in
        range: string
        allowMultiple: true
  shapeValidationNode:
    classTerm: validation.Validation
    mapping:
      name:
        propertyTerm: schema-org.name
        range: string
      message:
        propertyTerm: shacl.message
        mandatory: true
        range: string
      targetClass:
        propertyTerm: validation.ramlClassId
        mandatory: true
        range: string
        allowMultiple: true
      propertyConstraints:
        propertyTerm: shacl.property
        range: propertyConstraintNode
        asMap: true
        hash: validation.ramlPropertyId
      functionConstraint:
        propertyTerm: shacl.js
        range: functionConstraintNode
      targetQuery:
        propertyTerm: validation.targetQuery
        range: string
raml:
  document:
    encodes:
      classTerm: validation.Profile
      mapping:
        profile:
          propertyTerm: schema-org.name
          mandatory: true
          range: string
        description:
          propertyTerm: schema-org.description
          range: string
        extends:
          propertyTerm: validation.extendsProfile
          range: string
        violation:
          propertyTerm: validation.setSeverityViolation
          range: string
          allowMultiple: true
        info:
          propertyTerm: validation.setSeverityInfo
          range: string
          allowMultiple: true
        warning:
          propertyTerm: validation.setSeverityWarning
          range: string
          allowMultiple: true
        disabled:
          propertyTerm: validation.disableValidation
          range: string
          allowMultiple: true
        validations:
          propertyTerm: validation.validations
          range: shapeValidationNode
          asMap: true
          hash: schema-org.name
  module:
    declares:
      validations: queryValidationNode