#%RAML 1.0 Dialect
uses:
  dlib: dialect_lib2.raml
dialect: Validation Profile
version: 1.0
usage: Dialect to describe validations over RAML documents
nodeMappings:
  functionConstraintNode: dlib.functionConstraintNode
  propertyConstraintNode: dlib.propertyConstraintNode
  functionValidationNode: dlib.functionValidationNode
  shapeValidationNode: dlib.shapeValidationNode
  queryValidationNode: dlib.queryValidationNode
  profileNode: dlib.profileNode
raml:
  document:
    encodes: dlib.profileNode
  module:
    declares:
      validations: dlib.queryValidationNode
  fragments:
    encodes:
      Validation: dlib.queryValidationNode
