#%RAML 1.0
title: API for REST Services used in the RAML tutorials on Baeldung.com
documentation:
  - title: Overview
    content: |
      This document defines the interface for the REST services
      used in the popular RAML Tutorial series at Baeldung.com.