#%RAML 1.0
documentation:
  -
    title: Descripción general
    content: |
      Este documento define la interfaz para los servicios REST
      utilizados en la popular serie de RAML Tutorial en Baeldung.com.
title: |
  API para servicios REST utilizados en los tutoriales RAML
  en Baeldung.com
