#%RAML 1.0

title: test
version: 2010-04-01
types:
  SomeType1:
    type: string
    example: "+14158675309"
  SomeType2:
    type: integer
    example: +14158675309
  SomeType3:
    type: object
    example: |
      { "message" : "Your request does not have the correct values"}