#%Container Configuration 0.1
namespace: system
schema: http://test.com/some/schema
pattern:
  template: "$container/{namespace}"
  mapping:
    - variable: namespace
      property: http://mulesoft.com/vocabularies/knowledge-graph-service#namespace
pageSize: 10
versionable: false
