#%RAML 1.0
title: test
version: v1.0
protocols: HTTPS
mediaType: application/json

types:
  auto_task:
    type: array
    items:
      type: object
      properties:
        assigned_date?: datetime
        assigned_team_name?: string
        assigned_user?: string
        completed?: boolean
        description?: string
        due_date?: datetime
        id?: string
        los_loan_application_id?: string
        percentage_completed?: number
        subject?: string
        submitted_by_user_full_name?: string
        task_state?: string


  loan:
    type: object
    properties:
      roostify_loan_application_id?: string
      auto_task?: auto_task[]

/loans:
                            
  /{loan_id}:          
    get:
      responses:
        200: 
          body:
            application/json:
              type: loan
