#%RAML 1.0 SecurityScheme
type: OAuth 1.0
description: OAuth 1.0 continues to be supported for all API requests, but OAuth 2.0 is now preferred.
settings:
  requestTokenUri: http://api.domain.com/oauth1/request_token
  authorizationUri: http://api.domain.com/oauth1/authorize
  tokenCredentialsUri: http://api.domain.com/oauth1/access_token
