#%RAML 1.0 Extension
extends: api.raml
title: OpenId Connect No Resource Template (Override Me)

uses:
  openid: library.raml

traits:
  openid-configuration: !include trait.raml

/.well-known/openid-configuration:
  get:
    is: [openid-configuration]
