#%RAML 1.0
title: main
baseUri: http://api.com/main

types:
    User:
        properties:
            name: string
            age?: integer
        example:
            name: tato
            age?: 88
