#%RAML 1.0 DataType

#This file is located at dataTypes/resources/Schedule.raml

uses:
  FHIR_commons: /exchange_modules/47f07e0a-f578-47d4-9591-d9e7afffb0fc.healthcare/fhir_commons/1.0.0/fhir_commons.raml

type: FHIR_commons.DomainResource
description: |
  A container for slots of time that may be available for booking appointments
properties:
  identifier?:
    description: External Ids for this item
    type: FHIR_commons.Identifier[]
  active?:
    description: Whether this schedule is in active use
    type: boolean
  serviceCategory?:
    description: A broad categorisation of the service that is to be performed during this appointment
    type: FHIR_commons.CodeableConcept
  serviceType?:
    description: |
      The type of appointments that can be booked into this slot (ideally this would be an identifiable service - which is at a location, rather than the location itself).
      If provided then this overrides the value provided on the availability resource
    type: FHIR_commons.CodeableConcept[]
  specialty?:
    description: The specialty of a practitioner that would be required to perform the service requested in this appointment
    type: FHIR_commons.CodeableConcept[]
  actor:
    description: |
      The resource this Schedule resource is providing availability information for.
      These are expected to usually be one of HealthcareService, Location, Practitioner, PractitionerRole, Device, Patient or RelatedPerson
    type: FHIR_commons.Reference
  planningHorizon?:
    description: |
      The period of time that the slots that are attached to this Schedule resource cover (even if none exist).
      These  cover the amount of time that an organization's planning horizon; the interval for which they are currently accepting appointments.
      This does not define a "template" for planning outside these dates
    type: FHIR_commons.Period
  comment?:
    description: |
      Comments on the availability to describe any extended information.
      Such as custom constraints on the slots that may be associated
    type: string
