#%RAML 1.0
title: API
version: 1.0

resourceTypes:
  MyRT:
    get:
      responses:
        200:
          body:
            application/json:
              type: !include type.raml
              example:
                name: John
                lastName: 50


/endpoint:
  type: MyRT