#%ABOUT-GitHub 0.1
partOf: http://hello.world/hi.git
stargazersCount: 8
owner: vromero
ownerAvatar: https://avatars0.githubusercontent.com/u/1119553?s=460&v=4
createdAt: 2012-12-31T23:57:00
languages:
  -
    language: java
    usage: 10000
  -
    language: javascript
    usage: 1234
