#%RAML 1.0 Library
usage: Contains a set of data types which are entities to be used on openid resources

types:
  configuration:
    type: object
    properties:
      response_types_supported:
        type: string