#%RAML 1.0 Trait

uses:
  gp-types : ../types/types.raml

responses:
  200:
    body:
      application/json:
        type: object
        description: Defines the default message body.
        properties:
          header:
            description: Represents the Game Plataform's header which includes invocation meta data.
            type: types.header
          data:
            description: <<business-data-description>>
            type: <<business-data>>
            required: false
        examples:
          functional-error:
            header:
              timeStamp: 2016-02-28T16:41:41.090Z
              status: false
              error:
                code: "01109"
                message: Functional Error Title
                description: Some functional error has just happened!