#%RAML 1.0
title: simple object
types:
  root:
    type: cat | dog
  cat:
    properties:
      name:
        type: string
      color:
        type: string
    type: object
  dog:
    properties:
      name:
        type: string
      fangs:
        type: string
    type: object
