#%RAML 1.0
title: test

types:
  test1: |
    {
            "properties": {
                "foo": {"type": "integer"},
                "bar": {"$ref": "#/properties/foo"}
            }
    }

/ep1:
  get:
    responses:
      200:
        body:
          application/json:
            type: test1
            example:
              bar: 3

/ep2:
  get:
    responses:
      200:
        body:
          application/json:
            type: test1
            example:
              bar: true