#%RAML 1.0 ResourceType
get?:
  responses: 
    200:
      body: 
        application/json:
          type: array
          items: <<item>>
          example: <<itemsExample>>
        application/xml:
          type: array
          items: <<item>>
          example: <<itemsExample>>
post?:
  body: 
    application/json:
      type: <<item>>
      example: <<itemExample>>
  responses: 
    201:
      headers: 
        Location:
          example: <<resourcePath>>/1234
      body: 
        application/json:
          example:
            message: Created successfully the <<resourcePathName | !singularize>>
