#%RAML 1.0
title: API with Examples
types:
  User:
    example:
      name: Bob
      lastname: Marley
    properties:
      name:
        type: string
      lastname:
        type: string
  Org:
    properties:
      name:
        type: string
      address?:
        type: string
      value?:
        type: string
/organization:
  post:
    headers:
      UserID:
        description: the identifier for the user who posts a new organization
        type: string
        example: SWED-123
    body:
      application/json:
        example:
          value:
            name: Doe Enterprise
            value: Silver
        type: Org
  get:
    description: Returns an organization entity.
    responses:
      "201":
        body:
          application/json:
            examples:
              acme:
                name: Acme
              softwareCorp:
                value:
                  name: Software Corp
                  address: 35 Central Street
                  value: Gold
            type: Org
