#%RAML 1.0
types:
  scalarString:
    enum:
      - a
      - b
    type: string
  scalarNumber:
    enum:
      - 1
      - 2
    type: integer
  objectType:
    enum:
      -
        value1: a
        value2: b
      -
        value1: c
        value2: d
    properties:
      value1:
        type: string
      value2:
        type: string
  arrayType:
    enum:
      -
        - a
        - b
      -
        - c
        - d
    items:
      type: string
title: name
version: "1.0"
