#%RAML 1.0 Overlay
extends: file://amf-client/shared/src/test/resources/org/raml/parser/overlays/scalars/master.raml
title: overlay
description: some overlaid description
/master:
  displayName: overlaid display name
  /child:
    displayName: child overlaid display name over default
