#%RAML 1.0 Overlay

documentation:
  - title: Introducción
    content: El acceso automatizado a los libros
  - title: Licencias
    content: Por favor respeta los derechos de autor de los libros
/books:
  get:
    description: A?adir un nuevo libro para la colecci?n