#%RAML 1.0
baseUri: https://anypoint.mulesoft.com/mocking/api/v1/links/324e9f06-42e9-412e-8955-eace3920af23/ # 
title: tccs-crm-system-api-v1
version: 1.0

traits:
  clientIdEnforcement: !include traits/clientIdEnforcement.raml
  correlationId: !include traits/correlationIdTracking.raml
  queryParamFields: !include traits/queryParameterFields.raml
  sparsable: !include traits/sparsable.raml

types:
  successResponse: !include dataType/successResponseType.raml
  errorResponse: !include dataType/errorResponseType.raml
  caseObjects: !include dataType/caseObjects.raml
resourceTypes:
  errorResponse: !include resorseType/errorResponse.raml
  
/account:
  is: [clientIdEnforcement,correlationId]
  get:
    description: method not implemented
  /{id}:
    get:
      description: method not implemented
/cases:
  get:
    description: method not implemented
  post:
    description: method not implemented
  /{id}:
    get:
      is: [clientIdEnforcement,correlationId,sparsable: { fieldset: New|Update }]
      responses:
        200:
          body:
            application/json:
              type: caseObjects
    put:
      body:
        application/json:
          type: caseObjects
      responses:
        200:
            body:
              application/json:
                type: successResponse
        500:
          body:
            application/json:
              type: errorResponse
    
    /attachments:
      get:
    /files:
      get:
  /amis:
    /unassigned:
      get:
        is: [clientIdEnforcement,correlationId,queryParamFields]
        responses:
          200:
            body:
              application/json:
                type: caseObjects
          500:
            body:
              application/json:
                type: errorResponse
      


