#%Dialect 1.0
dialect: TestInstance
version: 1.9
nodeMappings:
  A:
    classTerm: tmp.A
    mapping:
      a2:
        propertyTerm: tmp.a2
        range: string
      a1:
        propertyTerm: tmp.a1
        range: string
  B:
    classTerm: tmp.B
    mapping:
      a:
        propertyTerm: tmp.a1
        range: A
  RootNode:
    classTerm: tmp.Test
    mapping:
      b:
        propertyTerm: tmp.b
        range: B
documents:
  root:
    encodes: RootNode
    declares:
      Bs: B
  library:
    declares:
      as: A
external:
  tmp: http://test.com/tmp#