#%Dialect 1.0
dialect: TestInstance
version: 1.22
external:
  v: http://test.com
nodeMappings:
  NestedObject:
    patch: update
    classTerm: v.Nested
    mapping:
      objectInsert:
        propertyTerm: v.toInsert
        range: InsertedObject
      objectDelete:
        propertyTerm: v.toDelete
        range: DeletedObject
      objectUpdate:
        propertyTerm: v.toUpdate
        range: UpdateObject
      objectUpsert:
        propertyTerm: v.toUpsert
        range: UpsertObject
      objectIgnore:
        propertyTerm: v.toIgnore
        range: IgnoreObject
      objectUpsert:
        propertyTerm: v.toUpsert
        range: UpsertObject
  InsertedObject:
    classTerm: v.InsertedObject
    patch: insert
    mapping:
      a:
        propertyTerm: v.a
        range: string
        unique: true
      b:
        propertyTerm: v.b
        range: string
  DeletedObject:
    classTerm: v.DeletedObject
    patch: delete
    mapping:
      a:
        propertyTerm: v.a
        range: string
        unique: true
      b:
        propertyTerm: v.b
        range: string
  UpdateObject:
    classTerm: v.UpdateObject
    patch: update
    mapping:
      a:
        propertyTerm: v.a
        range: string
        unique: true
      b:
        propertyTerm: v.b
        range: string
  UpsertObject:
    classTerm: v.UpsertObject
    patch: upsert
    mapping:
      a:
        propertyTerm: v.a
        range: string
        unique: true
      b:
        propertyTerm: v.b
        range: string
  IgnoreObject:
    classTerm: v.IgnoreObject
    patch: ignore
    mapping:
      a:
        propertyTerm: v.a
        range: string
        unique: true
      b:
        propertyTerm: v.b
        range: string
  RootNode:
    patch: update
    classTerm: v.Test
    mapping:
      literalInsert:
        propertyTerm: v.toInsert
        range: string
        patch: insert
      literalDelete:
        propertyTerm: v.toDelete
        range: string
        patch: delete
      literalUpdate:
        propertyTerm: v.toUpdate
        range: string
        patch: update
      literalIgnore:
        propertyTerm: v.toIgnore
        range: string
        patch: ignore

      nested:
        propertyTerm: v.nested
        range: NestedObject
        patch: update

      literalArrayInsert:
        propertyTerm: v.toInsertArray
        range: string
        patch: insert
        allowMultiple: true
      literalArrayDelete:
        propertyTerm: v.toDeleteArray
        range: string
        patch: delete
        allowMultiple: true
      literalArrayUpdate:
        propertyTerm: v.toUpdateArray
        range: string
        patch: update
        allowMultiple: true
      literalArrayIgnore:
        propertyTerm: v.toIgnoreArray
        range: string
        patch: ignore
        allowMultiple: true
      literalArrayUpsert:
        propertyTerm: v.toUpsertrray
        range: string
        patch: upsert
        allowMultiple: true

      objectArrayInsert:
        propertyTerm: v.toInsertArrayObject
        range: UpdateObject
        patch: insert
        allowMultiple: true
      objectArrayDelete:
        propertyTerm: v.toDeleteArrayObject
        range: UpdateObject
        patch: delete
        allowMultiple: true
      objectArrayUpdate:
        propertyTerm: v.toUpdateArrayObject
        range: UpdateObject
        patch: update
        allowMultiple: true
      objectArrayIgnore:
        propertyTerm: v.toIgnoreArrayObject
        range: UpdateObject
        patch: ignore
        allowMultiple: true
      objectArrayUpsert:
        propertyTerm: v.toUpsertArrayObject
        range: UpdateObject
        patch: upsert
        allowMultiple: true




documents:
  root:
    encodes: RootNode