#%Dialect 1.0
dialect: TestInstance
version: 1.19
nodeMappings:
  RootNode:
    classTerm: tmp.Test
    mapping:
      str:
        propertyTerm: tmp.str
        range: string
        unique: true
      int:
        propertyTerm: tmp.int
        range: integer
        unique: true
      float:
        propertyTerm: tmp.float
        range: float
      boolean:
        propertyTerm: tmp.boolean
        range: boolean
      date:
        propertyTerm: tmp.date
        range: date
      timestamp:
        propertyTerm: tmp.timestamp
        range: dateTime
documents:
  root:
    encodes: RootNode
external:
  tmp: http://test.com/tmp#