#%Dialect 1.0
dialect: TestInstance
version: 1.20
uses:
  v: vocabulary20
nodeMappings:
  RootNode:
    classTerm: v.Test
    mapping:
      a:
        propertyTerm: v.a
        range: string
documents:
  root:
    encodes: RootNode