#%Dialect 1.0
dialect: TestInstance
version: 1.15a
nodeMappings:
  nodeB:
    classTerm: v2.A
    mapping:
      za:
        propertyTerm: v2.extension
        range: anyNode
documents:
  root:
    encodes: nodeB
external:
  v2: http://test.com/v2#