#%Dialect 1.0
dialect: TestInstance
version: 1.23
external:
  v: http://test.com#
nodeMappings:
  RootNode:
    classTerm: v.Test
    mapping:
      a:
        propertyTerm: v.a
        range: string
      lets:
        propertyTerm: v.lets
        range: NestedNode
  NestedNode:
    classTerm: v.Nested
    mapping:
      b:
        propertyTerm: v.b
        range: string
documents:
  root:
    encodes: RootNode
  options:
    selfEncoded: true