#%Dialect 1.0
dialect: Test
version: 1.25
nodeMappings:
  Local:
    classTerm: v3.Local
    mapping:
      a:
        propertyTerm: v3.a
        range: any
        mandatory: true
documents:
  root:
    encodes: Local
    declares:
external:
  v3: http://test.com/v3#
