#%Dialect 1.0
dialect: TestInstance
version: 1.16b
nodeMappings:
  nodeX:
    classTerm: v2.X
    mapping:
      x:
        propertyTerm: v2.x
        range: nodeY
  nodeY:
    classTerm: v2.Y
    mapping:
      y:
        propertyTerm: v2.y
        range: nodeZ
  nodeZ:
    classTerm: v2.Y
    mapping:
      z:
        propertyTerm: v2.z
        range: string
documents:
  root:
    encodes: nodeX
  fragments:
    encodes:
      Fragment: nodeY
external:
  v2: http://test.com/v3#