#%Dialect 1.0
dialect: TestInstance
version: 1.21
external:
  v: http://test.com
nodeMappings:
  RootNode:
    classTerm: v.Test
    patch: upsert
    mapping:
      a:
        patch: ignore
        propertyTerm: v.a
        range: string
documents:
  root:
    encodes: RootNode