#%TestInstance 1.22
nested:
  objectDelete:
    a: delete
    b: target
  objectUpdate:
    a: update
    b: target
  objectUpsert:
    a: upsert
    b: target
  objectIgnore:
    a: ignore
    b: target
