#%TestInstance 1.22
nested:
  objectInsert:
    a: inset
    b: patch
  objectUpdate:
    a: update
    b: patch
  objectUpsert:
    a: upsert
    b: patch
  objectIgnore:
    a: ignore
    b: target
