#%Patch / TestInstance 1.22
$target: example22c.raml
literalArrayInsert: [other1, patch1]
literaArrayUpdate: [other1, patch1]
literalArrayIgnore: [other1, patch1]
literalArrayUpsert: [other1, patch1]
literalArrayDelete: [other1, patch1]