#%RAML 1.0
traits:
  env-org-pair:
    description: overlay description
    displayName: overlayDisplayName
/servers:
  get:
    displayName: overlayDisplayName
    description: master description
title: overlay
