#%RAML 1.0 Trait

uses:
  gp-types : ../types/types.raml

responses:
  200:
    body:
      application/json:
        type: object
        description: Defines the default message body.
        properties:
          header:
            description: Represents the Game Plataform's header which includes invocation meta data.
            type: types.header
          data:
            description: <<business-data-description>>
            type: <<business-data>>
            required: false
        example: <<example-data>>