#%RAML 1.0 DataType
type: object
properties: 
  type:
    required: false
    type: string | nil
  seqNo:
    required: false
    type: integer | nil
  alternateCd:
    required: false
    type: string | nil
  startDate:
    required: false
    type: datetime | nil
  endDate:
    required: false
    type: datetime | nil
  description:
    required: false
    type: string | nil
  category:
    required: false
    type: string | nil