#%RAML 1.0 DataType
type: object
properties:
  elementId:
    required: false
    type: string | nil
  elementVersion:
    required: false
    type: number
  elementName:
    required: false
    type: string | nil
  acadSeqNum:
    required: false
    type: string | nil
  acadAlternateCode:
    required: false
    type: string | nil
  teachSeqNum:
    required: false
    type: string | nil
  teachAlternateCode:
    required: false
    type: string | nil
  siteId:
    required: false
    type: string | nil
  elementStartDate:
    required: false
    type: datetime | nil
  elementEndDate:
    required: false
    type: datetime | nil
  version:
    required: false
    type: number | nil
  attendanceMode:
    required: false
    type: string | nil
  sector:
    required: false
    type: string | nil
  researchFlag:
    required: false
    type: string | nil
  acadCalType:
    required: false
    type: string | nil
  teachCalType:
    required: false
    type: string | nil
