#%RAML 1.0 DataType
displayName: calCohortDtls
type: object
properties:
  cohortCd:
    required: false
    displayName: cohortCd
    type: nil | string
  sProcessType:
    required: false
    displayName: S_PROCESS_TYPE
    type: nil | string
  sequenceNo:
    required: false
    displayName: SEQUENCE_NUMBER
    type: nil | number
  trnsactionLimitNo:
    required: false
    displayName: TRANSACTION_LIMIT_NUMBER
    type: nil | number
  calType:
    required: false
    displayName: CAL_TYPE
    type: nil | string
  ciSequenceNo:
    required: false
    displayName: CI_SEQUENCE_NUMBER
    type: nil | number
  startDtAlias:
    required: false
    displayName: START_DT_ALIAS
    type: nil | string
  startSeqNo:
    required: false
    displayName: startSeqNo
    type: nil | number
  startTime:
    required: false
    displayName: startTime
    type: nil | string
  endDtAlias:
    required: false
    displayName: endDtAlias
    type: nil | string
  endDtSeqNo:
    required: false
    displayName: endDtSeqNo
    type: nil | number
  endTime:
    required: false
    displayName: endTime
    type: nil | string
  preventAccessInd:
    required: false
    displayName: preventAccessInd
    type: nil | string
  preventAccessMsg:
    required: false
    displayName: preventAccessMsg
    type: nil | string 
  calStartDt:
    required: false
    displayName: calStartDt
    type: nil | date-only
  calEndDt:
    required: false
    displayName: calEndDt
    type: nil | date-only
  calDescription:
    required: false
    displayName: calDescription
    type: nil | string
  acadStartDt:
    required: false
    displayName: acadStartDt
    type: nil | date-only
  acadAlternateCode:
    required: false
    displayName: acadAlternateCode
    type: nil | string