#%RAML 1.0 DataType
displayName: sahelpDetails
type: object
properties:
  personId:
    required: true
    displayName: studentId
    type: number
  courseId:
    required: false
    displayName: courseCd
    type: nil | string