#%RAML 1.0 DataType
displayName: studentDeclaration
type: object
properties:
  status:
    required: false
    displayName: status
    type: nil | string
  timeStamp:
    required: false
    displayName: timeStamp
    type: nil | datetime-only  
  messageNumber:
    required: false
    displayName: messageNumber
    type: nil | number
  messageDescription:
    required: false
    displayName: messageDescription
    type: nil | string