#%RAML 1.0 DataType
type: object
properties: 
  id: 
    required: false
    type: string
  description: 
    required: false
    type: string
  usage:
     required: false
     type: array
     items: boolean