#%RAML 1.0 DataType
type: object
properties: 
  studentId:
    required: false
    type: integer | nil
  surname:
    required: false
    type: string | nil
  firstName:
    required: false
    type: string | nil
  gender:
    required: false
    type: string | nil
  emailAddr:
    required: false
    type: string | nil
  dateOfBirth:
    required: false
    type: datetime | nil
  dayTelephone:
    required: false
    type: string | nil
  acadCalType:
    required: false
    type: string | nil
  acadSeqNo:
    required: false
    type: integer | nil
  acadAlternateCd:
    required: false
    type: string | nil
  teachCalType:
    required: false
    type: string | nil
  teachSeqNo:
    required: false
    type: integer | nil
  teachAlternateCd:
    required: false
    type: string | nil
  fundSourceId:
    required: false
    type: string | nil
  enrolStatus:
    required: false
    type: string | nil
  overseas:
    required: false
    type: string | nil
  courseId:
    required: false
    type: string | nil
  courseVersion:
    required: false
    type: integer | nil
  siteId:
    required: false
    type: string | nil
  organisationUnitId:
    required: false
    type: string | nil
  level:
    required: false
    type: string | nil