#%RAML 1.0 DataType
type: object
properties: 
  courseId:
    required: false
    type: string | nil
  courseVersion:
    required: false
    type: integer | nil
  courseFullName:
    required: false
    type: string | nil
  sector:
    required: false
    type: string | nil
  awardType:
    required: false
    type: string | nil
  organisationUnitId:
    required: false
    type: string | nil
  courseAbbrName:
    required: false
    type: string | nil