#%RAML 1.0 DataType
displayName: courseDetails
type: object
properties:
  courseId:
    required: false
    displayName: courseId
    type: nil | string
  courseTitle:
    required: false
    displayName: courseTitle
    type: nil | string
  courseVersionNumber:
    required: false
    displayName: courseVersionNumber
    type: nil | number
  semester:
    required: false
    displayName: semester
    type: nil | string
  locationCode:
    required: false
    displayName: locationCode
    type: nil | string
  location:
    required: false
    displayName: location
    type: nil | string
  admissionCategory:
    required: false
    displayName: admissionCategory
    type: nil | string
  sectorCode:
    required: false
    displayName: sectorCode
    type: nil | string
  orgUnit:
    required: false
    displayName: orgUnit
    type: nil | string
  stdCommencingStatus:
    required: false
    displayName: orgUnit
    type: nil | string
  studentConfirmedInd:
    required: false
    displayName: orgUnit
    type: nil | string
  commencementDate:
    required: false
    displayName: orgUnit
    type: nil | date-only
  courseAttemptStatus:
    required: false
    displayName: orgUnit
    type: nil | string