#%RAML 1.0 DataType
displayName: disability
type: object
properties:
  disabilityType:
    required: false
    displayName: disabilityType
    type: nil | string
  contactInd:
    required: false
    displayName: contactInd
    type: nil | string