#%RAML 1.0 DataType
displayName: ecafDetails
type: object
properties:
  studentId:
    required: true
    displayName: studentId
    type: nil | string
  courseCd:
    required: true
    displayName: courseCd
    type: nil | string
  firstName:
    required: false
    displayName: firstName
    type: nil | string
  lastName:
    required: false
    displayName: lastName
    type: nil | string
  gender:
    required: false
    displayName: gender
    type: nil | string
  dob:
    required: false
    displayName: dob
    type: nil | date-only
  institution:
    required: false
    displayName: institution
    type: nil | string
  campus:
    required: false
    displayName: campus
    type: nil | string
  courseName:
    required: false
    displayName: courseName
    type: nil | string
  eCAFstartdate:
    required: false
    displayName: eCAFstartdate
    type: nil | date-only
  eCAFenddate:
    required: false
    displayName: eCAFenddate
    type: nil | date-only
  locationCode:
    required: false
    displayName: locationCode
    type: nil | string
  citizenship:
    required: true
    displayName: citizenship
    type: nil | string
  taxFileNumber:
    required: false
    displayName: taxFileNumber
    type: nil | string
  taxFileCertificate:
    required: false
    displayName: taxFileCertificate
    type: nil | string
  formName:
    required: true
    displayName: formName
    type: nil | string
  obligation1:
    required: true
    displayName: obligation1
    type: nil | string
  obligation2:
    required: true
    displayName: obligation2
    type: nil | string
  obligation3:
    required: true
    displayName: obligation3
    type: nil | string
  obligation4:
    required: false
    displayName: obligation4
    type: nil | string
  obligation5:
    required: false
    displayName: obligation5
    type: nil | string
  partialUpfrontPaymentInd:
    required: false
    displayName: partialUpfrontPaymentInd
    type: nil | string
  fullUpFrontPayment:
    required: false
    displayName: fullUpFrontPayment
    type: nil | string
  hecsHelpLoanInd:
    required: false
    displayName: hecsHelpLoanInd
    type: nil | string
  austResStudy:
    required: false
    displayName:  
    type: nil | string
  ausNzResStudy:
    required: false
    displayName: ausNzResStudy
    type: nil | string
  nhResAustStudy:
    required: false
    displayName: nhResAustStudy
    type: nil | string
  cnfrmdHelpEligibleNZInd:
    required: false
    displayName: cnfrmdHelpEligibleNZInd
    type: nil | string