#%RAML 1.0 DataType
type: object
properties: 
  studentId:
    required: false
    type : integer  | nil
  familyName:
    required: false
    type : string | nil
  firstName:
    required: false
    type : string | nil
  gender:
    required: false
    type :    string  | nil
  datetimeOfBirth:
    required: false
    type :    datetime | nil
  courseId:
    required: false
    type :    string | nil
  courseVersion:
    required: false
    type :    integer | nil
  acadCalType:
    required: false
    type :    string  | nil
  acadSeqNo:
    required: false
    type :    integer | nil
  acadAlternateCd:
    required: false
    type :    string  | nil
  teachCalType:
    required: false
    type :    string  | nil
  teachSeqNo:
    required: false
    type :    integer | nil
  teachAlternateCd:
    required: false
    type :    string  | nil
  subjectId:
    required: false
    type :    string | nil
  subjectVersion:
    required: false
    type :    integer | nil
  subjectHoursReduced:
    required: false
    type :    integer | nil
  creditPoints:
    required: false
    type :    number | nil
  subjectEnroldatetime:
    required: false
    type :    datetime | nil
  subjectGradedatetime:
    required: false
    type :    datetime | nil
  grade:
    required: false
    type :    string | nil
  mark:
    required: false
    type :    integer | nil
  attendanceMode:
    required: false
    type :    string | nil
  organisationUnitId:
    required: false
    type :    string | nil
  siteId:
    required: false
    type :    string  | nil
  level:
    required: false
    type :    string | nil
  courseStartdatetime:
    required: false
    type :    datetime | nil
  subjectStartdatetime:
    required: false
    type :    datetime | nil
  subjectEnddatetime:
    required: false
    type :    datetime | nil
  fundSourceId:
    required: false
    type :    string | nil
  enrolStatus:
    required: false
    type :    string | nil
  overseas:
    required: false
    type :    string | nil
  feeAmount:
    required: false
    type :    number | nil
  hecsOption:
    required: false
    type :    string | nil