#%RAML 1.0 DataType
displayName: ErrorDTO
type: object
properties:
  code:
    required: false
    displayName: code
    type: string | nil
  message:
    required: false
    displayName: message
    type: string | nil
  stackTraceElements:
    required: false
    type: string | nil
    displayName: stackTraceElements
    description: array of srackTraceElement
   