#%RAML 1.0 DataType
displayName: hecsDetails
type: object
properties:
  studentId:
    required: false
    displayName: studentId
    type: nil | string
  firstName:
    required: false
    displayName: firstName
    type: nil | string
  lastName:
    required: false
    displayName: lastName
    type: nil | string
  gender:
    required: false
    displayName: gender
    type: nil | string
  dob:
    required: false
    displayName: dob
    type: date-only
  institution:
    required: false
    displayName: institution
    type: nil | string
  campus:
    required: false
    displayName: campus
    type: nil | number
  courseName:
    required: false
    displayName: courseName
    type: nil | number
  citizenship:
    required: false
    displayName: citizenship
    type: nil | string
  eCAFstartdate:
    required: false
    displayName: eCAFstartdate
    type: date-only
  eCAFenddate:
    required: false
    displayName: eCAFenddate
    type: date-only
  HECS-HELP:
    required: false
    displayName: HECS-HELP
    type: nil | string
  paymentOption:
    required: false
    displayName: paymentOption
    type: nil | string
  taxFileNumber:
    required: false
    displayName: taxFileNumber
    type: nil | number
  taxFileCertificate:
    required: false
    displayName: taxFileCertificate
    type: nil | boolean
