#%RAML 1.0 DataType
displayName: offer
type: object
properties:
  personId:
    required: true
    displayName: personId
    type: number
  courseId:
    required: true
    displayName: courseId
    type: string