#%RAML 1.0 DataType
displayName: offerUpdResponse
type: object
properties:
  status:
    required: false
    displayName: status
    type: nil | string
  timeStamp:
    required: false
    displayName: timeStamp
    type: nil | datetime-only
  msgId:
    required: false
    displayName: msgId
    type: nil | number
  msgText:
    required: false
    displayName: msgText
    type: nil | string
  