#%RAML 1.0 DataType
type: object
properties:
  personId:
    required: false
    type: string | nil
  personFound:
    required: false
    type: boolean | nil
  accessConnect:
    required: false
    type: boolean | nil
  accessSMS:
    required: false
    type: boolean | nil
  accessJSF:
    required: false
    type: boolean | nil