#%RAML 1.0 DataType
displayName: referenceData
type: object
properties:
  code:
    required: true
    displayName: code
    type: nil | string
  description:
    required: false
    displayName: description
    type: nil | string