#%RAML 1.0 DataType
displayName: ResultDTOPersonSecurity
type: object
properties:
  error:
    required: false
    displayName: error
    type: !include ErrorDTO.raml
  result:
    required: false
    displayName: result
    type: !include PersonSecurityDTO.raml
