#%RAML 1.0 DataType
displayName: ResultDTOAvailableSubjectDetailArray
type: object
properties:
  error:
    required: false
    displayName: error
    type: !include ErrorDTO.raml
  result:
    required: false
    displayName: result
    type: array
    items: !include AvailableSubjectDetailDTO.raml
