#%RAML 1.0 DataType
displayName: sahelpDetails
type: object
properties:
  studentId:
    required: true
    displayName: studentId
    type: number
  courseCd:
    required: false
    displayName: courseCd
    type: nil | string
  firstName:
    required: false
    displayName: firstName
    type: nil | string
  lastName:
    required: false
    displayName: lastName
    type: nil | string
  gender:
    required: false
    displayName: gender
    type: nil | string
  dob:
    required: false
    displayName: dob
    type: nil | date-only
  institution:
    required: false
    displayName: institution
    type: nil | string
  campus:
    required: false
    displayName: campus
    type: nil | string
  courseName:
    required: false
    displayName: courseName
    type: nil | string
  citizenship:
    required: false
    displayName: citizenship
    type: nil | string
  taxFileNumber:
    required: false
    displayName: taxFileNumber
    type: nil | string
  taxFileCertificate:
    required: false
    displayName: taxFileCertificate
    type: nil | string
  helpEligibilityNZind:
    required: false
    displayName: helpEligibilityNZind
    type: nil | string
  criteria:
    required: false
    displayName: criteria
    type: nil | string
  msgId:
    required: false
    displayName: msgId
    type: nil | string
  msgDesc:
    required: false
    displayName: msgDesc
    type: nil | string