#%RAML 1.0 DataType
displayName: scohortDtl
type: object
properties:
  studentId:
    required: false
    displayName: studentId
    type: nil | number
  courseCd:
    required: false
    displayName: courseCd
    type: nil | string
  calType:
    required: false
    displayName: calType
    type: nil | string
  ciSequenceNo:
    required: false
    displayName: ciSequenceNo
    type: nil | number
  startDt:
    required: false
    displayName: startDt
    type: nil | date-only
  endDt:
    required: false
    displayName: endDt
    type: nil | date-only
  altCode:
    required: false
    displayName: altCode
    type: nil | string
  enrolmentCat:
    required: false
    displayName: enrolmentCat
    type: nil | string
  enrolmentFormDueDt:
    required: false
    displayName: enrolmetnFormDueDt
    type: nil | date-only
  enrolmentPckgProdDt:
    required: false
    displayName: enrolmentPckgProdDt
    type: nil | date-only
  enrolmentFormRcvDt:
    required: false
    displayName: enrolmentFormRcvDt
    type: nil | date-only