#%RAML 1.0 DataType
displayName: studentEncumbrances
type: object
properties:
  studentEncumbranceEffect:
    required: false
    displayName: studentEncumbranceEffect
    type: nil | string
  studentEncumbranceExpiryDate:
    required: false
    displayName: studentEncumbranceExpiryDate
    type: nil | date-only
  studentEncumbranceStartDate:
    required: false
    displayName: studentEncumbranceStartDate
    type: nil | date-only
  studentEncumbranceType:
    required: false
    displayName: studentEncumbranceType
    type: nil | string
  comments:
    required: false
    displayName: comments
    type: nil | string
  courseCode:
    required: false
    displayName: courseCode
    type: nil | string
  spoSequeceNumber:
    required: false
    displayName: spoSequeceNumber
    type: nil | number
  expiryAuthorizedBy:
    required: false
    displayName: expiryAuthorizedBy
    type: nil | number
  expiryComments:
    required: false
    displayName: expiryComments
    type: nil | string
  authorisingPeron:
    required: false
    displayName: authorisingPeron
    type: nil | number
  appliedCommunicationItemId:
    required: false
    displayName: appliedCommunicationItemId
    type: nil | number
  expiredCommunicationItemId:
    required: false
    displayName: expiredCommunicationItemId
    type: nil | number
  systemGeneratedInd:
    required: false
    displayName: systemGeneratedInd
    type: nil | string