#%RAML 1.0 DataType
type: object
properties: 
  courseCd:
    required: false
    type: string | nil
  grade:
    required: false
    type: string | nil
  surname:
    required: false
    type: string | nil
  personId:
    required: false
    type: datetime | nil
  mark:
    required: false
    type: string | nil
  outcomeId:
      required: false
      type: string | nil
  unitCd:
      required: false
      type: string | nil
