#%RAML 1.0 DataType
type: object
properties: 
  studentId:
    required: false
    type: number | nil
  firstName:
    required: false
    type: string | nil
  familyName:
    required: false
    type: string | nil
  dateOfBirth:
    required: false
    type: datetime | nil
  gender:
    required: false
    type: string | nil
  preferredNameOrderCode:
    required: false
    type: string | nil
  emailAddr:
    required: false
    type: string | nil
  countryOfResidence:
    required: false
    type: string | nil
  countryOfBirth:
    required: false
    type: string | nil
  citizenshipId:
    required: false
    type: string | nil
  atsecFlag:
    required: false
    type: string | nil
  mainLanguageId:
    required: false
    type: string | nil
  mainLanguage:
    required: false
    type: string | nil
  citizenship:
    required: false
    type: string | nil
  addressType:
    required: false
    type: string | nil
  addressLine1:
    required: false
    type: string | nil
  addressLine2:
    required: false
    type: string | nil
  addressLine3:
    required: false
    type: string | nil
  addressLine4:
    required: false
    type: string | nil
  addressLine5:
    required: false
    type: string | nil
  phoneNumber1: 
    required: false
    type: string | nil
  phoneNumber2:
    required: false
    type: string | nil
  phoneNumber3:
    required: false
    type: string | nil
  otherDetails:
    required: false
    type: string | nil
  postCode:
    required: false
    type: number | nil
  overseasPostcode:
    required: false
    type: string | nil
  stopStatus:
    required: false
    type: string | nil
  chessn:
    required: false
    type: number | nil
  vtacId:
    required: false
    type: string | nil