#%RAML 1.0 DataType
displayName: studentDeclaration
type: object
properties:
  studentId:
    required: true
    displayName: studentId
    type: number
  courseCd:
    required: true
    displayName: courseCd
    type: string
  enrCalType:
    required: true
    displayName: enrCalType
    type: string
  enrCISeqNumber:
    required: true
    displayName: enrCISeqNumber
    type: number