#%RAML 1.0 DataType
type: object
properties: 
  subjectId:
    required: false
    type: string | nil
  subjectVersion:
    required: false
    type: number | nil
  acadCalType:
    required: false
    type: string | nil
  acadSeqNo:
    required: false
    type: number | nil
  acadAlternateCd:
    required: false
    type: string | nil
  teachCalType:
    required: false
    type: string | nil
  teachSeqNo:
    required: false
    type: number | nil
  teachAlternateCd:
    required: false
    type: string | nil
  subjectHours:
    required: false
    type: number | nil
  creditPoints:
    required: false
    type: number | nil