#%RAML 1.0 DataType
type: object
properties: 
  acadType:
    required: false
    type: string | nil
  acadSeqNo:
    required: false
    type: number | nil
  acadAlternateCd:
    required: false
    type: string | nil
  acadStartDate:
    required: false
    type: datetime | nil
  teachType:
    required: false
    type: string | nil
  teachSeqNo:
    required: false
    type: number | nil
  teachAlternateCd:
    required: false
    type: string | nil
  teachStartDate:
    required: false
    type: datetime | nil
  teachEndDate:
    required: false
    type: datetime | nil
  teachDescription:
    required: false
    type: string | nil
  teachCategory:
    required: false
    type: string | nil
