#%RAML 1.0 DataType
displayName: teachingCalendar
type: object
properties:
  acadCalType:
    required: false
    displayName: acadCalType
    type: nil | string
  teachStartDt:
    required: false
    displayName: teachStartDt
    type: nil | date-only
  teachAlternateCd:
    required: false
    displayName: teachAlternateCd
    type: nil | string
  teachSeqNo:
    required: false
    displayName: teachSeqNo
    type: nil | number
  teachCalType:
    required: false
    displayName: teachCalType
    type: nil | string
  acadStartDt:
    required: false
    displayName: acadStartDt
    type: nil | date-only
  acadAlternateCd:
    required: false
    displayName: acadAlternateCd
    type: nil | string
  teachCalCat:
    required: false
    displayName: teachCalCat
    type: nil | string
  teachEndDt:
    required: false
    displayName: teachEndDt
    type: nil | date-only
  teachDescription:
    required: false
    displayName: teachDescription
    type: nil | string  
  acadSeqNo:
    required: false
    displayName: acadSeqNo
    type: nil | number