#%RAML 1.0 DataType
displayName: unitResposne
type: object
properties:
  unitCd:
    required: false
    displayName: unitCd
    type: nil | string
  status:
    required: false
    displayName: status
    type: nil | string
  timeStamp:
    required: false
    displayName: timeStamp
    type: nil | datetime-only
  msgId:
    required: false
    displayName: msgId
    type: nil | number
  msgText:
    required: false
    displayName: msgText
    type: nil | string
  