#%RAML 1.0
title: test API
/resource:
  post:
    description: Create object
    body:
      application/json:
        additionalProperties: true
        properties:
          p1:
            type: string
            required: true
          p2:
            type: number
            required: true
  put:
    body:
      application/xml:
        additionalProperties: true
        properties:
          p1:
            type: string
            required: true
          p2:
            type: number
            required: true
