#%RAML 1.0
title: test API
/resource:
  post:
    description: Create object
    body:
      application/json:
        properties:
          p1:
            type: string
          p2:
            type: number
  put:
    body:
      application/xml:
        properties:
          p1:
            type: string
          p2:
            type: number
