#%RAML 1.0
title: test API

types:
  Person:
    type: object
    properties:
      name: string
      age: integer
  Employee:
    type: object
    properties:
      title: string
      person: Person
  AnyType:
    type: any
    examples: !include employee-example.raml