#%RAML 1.0
baseUri: http://api.topdanmark.dk/office365-proxyApi/{version}
title: office365-proxyApi
version: v1

uses:
  resources: libraries/ResourceTypes.raml

/users:
  type:
    resources.collection-item:
      exampleItem: |
        {
          "content": "<html>\r\n<head>\r\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\r\n<meta content=\"text/html; charset=us-ascii\">\r\n</head>\r\n<body>\r\nDiscussion about the issues!\r\n</body>\r\n</html>\r\n",
          "secondExample": "SCREEN, COARSE, 6\", TEKLEEN, FOR H.P. FI"
        }
