#%RAML 1.0
types:
  StringType:
    type: string
  ByteType:
    type: string
    (format): byte
  BinaryType:
    type: string
    (format): binary
  PasswordType:
    type: string
    (format): password
  IntegerType:
    type: integer
  NumberType:
    type: number
  BooleanType:
    type: boolean
  NilType:
    type: nil
  AnyType:
    type: any
  DateTimeType:
    type: datetime
  DateTimeOnlyType:
    type: datetime-only
  TimeOnlyType:
    type: time-only
  DateOnlyType:
    type: date-only
  ObjectType:
    type: object
  FileType:
    type: file
    fileTypes:
      - image/jpeg
      - image/png
    maxLength: 307200
  UnionType:
    type: union
    anyOf:
      -
        type: string
      -
        type: integer
title: test title
