#%RAML 1.0
title: examples
types:
  Person:
    properties:
      name:
        type: string
      lastname:
        type: string
    examples:
      titan:
        name: martin
        lastname: palermo
      apache:
        name: carlos
        lastname: tevez