#%RAML 1.0
types:
  Person:
    examples:
      titan:
        name: martin
        lastname: palermo
      apache:
        name: carlos
        lastname: tevez
    properties:
      name:
        type: string
      lastname:
        type: string
title: examples
