#%RAML 1.0
title: test title
description: test description
mediaType:
  - application/yaml
version: 1.1
(termsOfService): terms of service
protocols:
  - http
  - https
(contact):
  url: http://test.com/contactUrl
  name: contactName
  email: contactEmail
documentation:
  -
    (url): http://test.com/externalDocsUrl
    content: externalDocsDescription
(license):
  url: http://test.com/licenseUrl
  name: licenseName
/levelzero:
  displayName: Name
  get:
    description: Some description
    displayName: Some title
    (deprecated): true
    (summary): This is a summary
    (externalDocs):
      url: http://test.com/urlExternalDocs
      description: descriptionExternalDocs
    protocols:
      - http
      - https
    (consumes):
      - application/xml
    (produces):
      - application/json
  post:
    description: Some description
    displayName: Some title
    (externalDocs):
      url: http://test.com/urlExternalDocs
      description: descriptionExternalDocs
    protocols:
      - http
      - https
/levelzero/level-one:
  displayName: One display name
  description: and this description!
  get:
    description: Some description level one
    displayName: Some title level one
    (deprecated): true
    (summary): This is a summary level one
    (externalDocs):
      url: http://test.com/urlExternalDocs
      description: descriptionExternalDocs level one
    protocols:
      - http
      - https
/levelzero/another-level-one:
  displayName: some other display name
/another-levelzero:
  displayName: Root name
  post:
    description: Some description another level 0
    displayName: Some title another level 0
    (externalDocs):
      url: http://test.com/urlExternalDocs
      description: descriptionExternalDocs another level 0
    protocols:
      - http
      - https
baseUri: api.example.com/path
