#%RAML 0.8

title: GitHub API
version: v3
protocols:
  - https
baseUri: api.github.com/
/user:
  displayName: Authenticated User
/users:
  displayName: Users
  /{userId}:
   displayName: User
   baseUriParameters:
     userId:
       displayName: User ID
       type: integer