#%RAML 1.0
title: API
version: "1.0"
/levelzero:
  displayName: One display name
  description: and this description!
  get:
    displayName: Some title
    queryParameters:
      param1:
        description: Some descr
        required: true
        properties:
          name:
            type: string
      param2?:
        type: object
        properties:
          lastName:
            type: string
