#%RAML 1.0
(amf-parameters):
  a:
    name: b
    required: true
    in: path
    type: string
title: test
version: "1.0"
/a/{a}:
  get:
    body:
      properties:
        theBody?:
          type: file
    (amf-baseUriParameters):
      a: a
