#%RAML 1.0
(amf-parameters):
  a:
    required: true
    type: string
    (amf-binding): path
title: test
version: "1.0"
/a/{a}:
  get:
    body:
      properties:
        theBody?:
          type: file
    (amf-baseUriParameters):
      a: a
