#%RAML 1.0
title: Presentation
types:
  Speaker:
    description: Speaker
    type:
      - Person
      - Member
  Person:
    type: object
    description: Person
  Member:
    type: object
    description: Member
