#%RAML 1.0
types:
  MyType:
    (a): stringvalue1
    properties:
      p1:
        (a): stringValue2
        type: any
annotationTypes:
  a:
    type: string
title: test API
version: 1.0
/resource:
  get:
    body:
      application/json:
        (a): stringValue5
        type: object
        properties:
          p2:
            (a): stringValue6
            type: any
    (a): stringValue4
  (a): stringValue3
