#%RAML 1.0
types:
  MyType:
    (a): stringvalue1
    type: object
    properties:
      p1:
        (a): stringValue2
        type: string
        required: true
annotationTypes:
  a:
    type: string
title: test API
version: "1.0"
/resource:
  get:
    body:
      application/json:
        (a): stringValue5
        type: object
        properties:
          p2:
            (a): stringValue6
            type: string
            required: true
    (a): stringValue4
  (a): stringValue3
