#%RAML 1.0
title: test title
baseUri: api.example.com/path
description: test description
mediaType:
  - application/yaml
version: "1.1"
(amf-termsOfService): terms of service
protocols:
  - http
  - https
/levelzero:
  displayName: Name
/levelzero/level-one:
  displayName: One display name
  description: and this description!
  get:
    displayName: Some title
    responses:
      200:
        description: 200 descr
        headers:
          Time-Ago:
            required: true
            type: integer
      404:
        description: Not found!
