#%RAML 1.0
(amf-parameters):
  a:
    name: b
    required: true
    in: path
    type: string
  payload:
    in: body
    name: theBody
    schema:
      type: object
      properties:
        prop:
          type: string
title: test
version: "1.0"
/a/{a}:
  uriParameters:
    a: a
