#%RAML 1.0
title: Example API
version: v1
resourceTypes:
  searchableCollection:
    usage: resource type usage
    get:
      queryParameters:
        <<queryParamName>>:
          description: Return <<resourcePathName>> that have their <<queryParamName>> matching the given value
        <<fallbackParamName>>:
          description: If no values match the value given for <<queryParamName>>, use <<fallbackParamName>> instead
traits:
  secured:
    usage: trait usage
    queryParameters:
      <<tokenName>>:
        description: A valid <<tokenName>> is required
  paged:
    queryParameters:
      numPages:
        description: The number of pages to return, not to exceed <<maxPages | !singularize>>
  descr:
    description: Some requests require authentication.
/books:
  type:
    searchableCollection:
      queryParamName: title
      fallbackParamName: digest_all_fields
  is:
    - descr
  get:
    is:
      -
        secured:
          tokenName: access_token
      -
        paged:
          maxPages: 10
