#%RAML 1.0
title: test title
baseUri: api.example.com/path
description: test description
mediaType:
  - application/yaml
version: "1.1"
(amf-termsOfService): terms of service
protocols:
  - http
  - https
/level-zero:
  displayName: One display name
  description: and this description!
  get:
    displayName: Some title
    body:
      type: object
      properties:
        name?:
          type: string
        lastName?:
          type: string
        address?:
          type: object
          properties:
            city?:
              type: string
            street?:
              type: string
            number?:
              type: integer
            postal?:
              type: integer
          (amf-dependencies):
            city:
              - postal
            street:
              - number
              - postal
              - city
            number:
              - street
      application/raml:
        type: object
        properties:
          credit_card?:
            type: integer
          city?:
            type: string
          street?:
            type: string
          number?:
            type: integer
          postal?:
            type: integer
        (amf-dependencies):
          credit_card:
            - city
            - postal
          street:
            - number
            - postal
            - city
          number:
            - street
