#%RAML 1.0
title: test title
baseUri: api.example.com/path
description: test description
mediaType:
  - application/yaml
version: "1.1"
(amf-termsOfService): terms of service
protocols:
  - http
  - https
/level-zero:
  displayName: One display name
  description: and this description!
  get:
    displayName: Some title
    body:
      type: object
      properties:
        name:
          type: string
          required: false
        lastName:
          type: string
          required: false
        address:
          type: object
          properties:
            city:
              type: string
              required: false
            street:
              type: string
              required: false
            number:
              type: integer
              required: false
            postal:
              type: integer
              required: false
          (amf-dependencies):
            city:
              - postal
            street:
              - number
              - postal
              - city
            number:
              - street
          required: false
      application/raml:
        type: object
        properties:
          credit_card:
            type: integer
            required: false
          city:
            type: string
            required: false
          street:
            type: string
            required: false
          number:
            type: integer
            required: false
          postal:
            type: integer
            required: false
        (amf-dependencies):
          credit_card:
            - city
            - postal
          street:
            - number
            - postal
            - city
          number:
            - street
