#%RAML 1.0
types:
  ScalarTest:
    default: defaultValue
    enum:
      - a1
      - a2
    type: string
    minLength: 1
    maxLength: 20
    pattern: blabla.+
  IntegerTest:
    type: number
    (amf-exclusiveMinimum): false
    (amf-exclusiveMaximum): false
    minimum: 2
    maximum: 25
    multipleOf: 2
    format: int32
  ObjectTest:
    displayName: that person
    description: ooo person
    default:
      name: john doe
    (amf-externalDocs):
      url: externalDocsUrl
      description: externalDocsDescription
    xml:
      attribute: true
      wrapped: true
      name: test
      namespace: namespacetest
      prefix: blabla
    type: object
    minProperties: 1
    maxProperties: 5
    additionalProperties: true
    discriminator: ddd
    discriminatorValue: valueD
    properties:
      name?:
        (amf-readOnly): false
        type: string
title: test title
version: "1.0"
