#%RAML 1.0
title: API with Types
types:
  CustomDate:
    type: date-only
    facets:
      onlyFutureDates?:
        type: boolean
      noHolidays:
        type: boolean
  PossibleMeetingDate:
    type:
      - CustomDate
    noHolidays: true