#%RAML 0.8
title: test
schemas:
  - banks: |
      {  "$schema": "http://json-schema.org/draft-03/schema",
         "type": "array",
         "items": { "$ref": "bank-schema.json#/" }
      }
  


resourceTypes:
  - readOnlyCollection:
      description: Collection of available <<resourcePathName>> in Employee.
      get:
        description: Get a list of <<resourcePathName>>.
        responses:
          200:
            body:
              application/json:
                schema: <<schemaCollection>>
/rbs:
  displayName: Raiffeisen Banken Resource
  type:
    readOnlyCollection:
      schemaCollection: banks
/byPosition:
  displayName: Raiffeisen Bank
  type:
    readOnlyCollection:
      schemaCollection: banks