#%RAML 1.0
title: Example API
version: v1
/Users:
  post:
    responses:
      "200":
        body:
          application/json:
            type: object
            additionalProperties: true
            properties:
              name:
                type: string
                required: true
              lastName:
                type: string
                required: true
  get:
    queryParameters:
      get:
        description: A get-token pair is required
        example: get=h8duh3uhhu38
    description: Some requests require authentication
    body: {}
    responses:
      "200":
        body:
          application/json:
            type: array
            items:
              type: object
              additionalProperties: true
              properties:
                name:
                  type: string
                  required: true
                lastName:
                  type: string
                  required: true
