#%RAML 1.0
traits:
  a:
    description: Trait 'a'
    queryParameters:
      <<methodName>>-a-<<posfix>>?: string
  b:
    description: Trait 'b'
    queryParameters:
      <<methodName>>-b-<<posfix>>:
        type: string
        required: false
  c:
    description: Trait 'c'
    queryParameters:
      <<methodName>>-c-<<posfix>>: string
  d:
    description: Trait 'd'
    queryParameters:
      <<methodName>>-d: string
  e:
    description: Trait 'e'
    queryParameters:
      <<methodName>>-e: string
  f:
    description: Trait 'f'
    queryParameters:
      <<methodName>>-f: string

  g:
    description: Trait 'g'
    queryParameters:
      <<methodName>>-g-<<posfix>>: string

resourceTypes:
  p:
    is: [e, g: {posfix: <<method>>}]
    put:
    <<method>>:
    get:
      is: [f]
  o:
    type: {p: {method: head}}
    is: [d]

title: TraitsResolution

/endpoint:
  type: o
  is: [b: {posfix: alpha}, c: {posfix: alpha}]
  get:
    is: [a: {posfix: beta}, b: {posfix: beta}]
  post:
    is: [a: {posfix: beta}, b: {posfix: beta}]