#%RAML 1.0
title: Example of Optional Properties
resourceTypes:
  corpResource:
    post?:
      description: Some info about <<TextAboutPost>>.
      headers:
        X-Chargeback:
          required: true
/servers:
  get:
  post:
    headers:
      X-Chargeback:
        required: true
    description: Some info about post method.
/queues:
  get:
