#%RAML 1.0
title: Example API
version: v1
/books:
  get:
    queryParameters:
      title:
        description: Return books that have their title matching the given value
      digest_all_fields:
        description: If no values match the value given for title, use digest_all_fields instead
      access_token:
        description: A valid access_token is required
      numPages:
        description: The number of pages to return, not to exceed 10
