#%RAML 1.0
title: Test
resourceTypes:
  collection:
    post?:
      body:
        application/json:
          type: Post<<resourcePathName | !singularize | !uppercamelcase>>
/media:
  post:
    body:
      application/json:
        example:
          name: Something
        type: object
        additionalProperties: true
        properties:
          name:
            type: string
            required: true
types:
  PostMedium:
    type: object
    additionalProperties: true
    properties:
      name:
        type: string
        required: true
