#%RAML 1.0
title: Example API
version: v1
/users:
  get:
    headers:
      access_token:
        description: Access Token
        example: 5757gh76
        required: true
    description: Some requests require authentication.
/other: {}
