#%RAML 1.0
title: Test
/media:
  post:
    body:
      application/json:
        type: object
        example:
          name: Something
        additionalProperties: true
        properties:
          name:
            type: string
            required: true
