#%RAML 1.0
title: API
/products:
  get:
    headers:
      APIKey: {}
    description: override the description
    responses:
      "200":
        body:
          application/json:
            type: any
