#%RAML 1.0
title: Example with headers
traits:
  chargeable:
    headers:
      X-Dept:
        type: array
        description: |
          A department code to be charged.
          Multiple of such headers are allowed.
        items:
          pattern: ^\d+\-\w+$
          example: 230-OCTO
/users:
  get:
    is: [ chargeable ]
    headers:
      X-Dept:
        example: [ 18-FINANCE, 200-MISC ]
