#%RAML 1.0
title: test
version: "1.0"
baseUri: aaa-bbb.com/apis
/customers:
  displayName: Customer Resource
  /corporate:
    post:
      body:
        type: object
        additionalProperties: true
        properties:
          address_country:
            type: string
            required: true
          address_locality:
            type: string
            required: true
          address_region:
            type: string
            required: true
          postal_code:
            type: string
            required: true
          street_address:
            type: string
            required: true
          lei:
            type: string
            required: true
          tax_id:
            type: string
            required: true
          email:
            type: string
            required: true
          telephone:
            type: string
            required: true
          name:
            type: string
            required: true
          vat_id:
            type: string
            required: true
  /commercial:
    post:
      body:
        type: object
        additionalProperties: true
        properties:
          address_country:
            type: string
            required: true
          address_locality:
            type: string
            required: true
          address_region:
            type: string
            required: true
          postal_code:
            type: string
            required: true
          street_address:
            type: string
            required: true
          lei:
            type: string
            required: true
          tax_id:
            type: string
            required: true
          email:
            type: string
            required: true
          telephone:
            type: string
            required: true
          title:
            type: string
            enum:
              - mr
              - mrs
              - ms
              - dr
            required: false
          given_name:
            type: string
            required: true
          family_name:
            type: string
            required: true
          gender:
            type: string
            enum:
              - female
              - male
            required: true
          vat_id:
            type: string
            required: false
          birth_date:
            type: date-only
            required: true
  /{customer_id}:
    uriParameters:
      customer_id:
        type: string
    get:
      responses:
        "200":
          body:
            application/json:
              anyOf:
                -
                  discriminator: type
                  discriminatorValue: Organization
                  type: object
                  additionalProperties: true
                  properties:
                    type:
                      type: string
                      required: true
                    lei:
                      type: string
                      required: true
                    tax_id:
                      type: string
                      required: true
                    email:
                      type: string
                      required: true
                    address:
                      additionalProperties: true
                      properties:
                        address_country:
                          type: string
                          required: true
                        address_locality:
                          type: string
                          required: true
                        address_region:
                          type: string
                          required: true
                        postal_code:
                          type: string
                          required: true
                        street_address:
                          type: string
                          required: true
                      required: true
                    id:
                      type: string
                      required: true
                    name:
                      type: string
                      required: true
                    vat_id:
                      type: string
                      required: true
                -
                  discriminator: type
                  discriminatorValue: Person
                  type: object
                  additionalProperties: true
                  properties:
                    type:
                      type: string
                      required: true
                    lei:
                      type: string
                      required: true
                    tax_id:
                      type: string
                      required: true
                    email:
                      type: string
                      required: true
                    address:
                      additionalProperties: true
                      properties:
                        address_country:
                          type: string
                          required: true
                        address_locality:
                          type: string
                          required: true
                        address_region:
                          type: string
                          required: true
                        postal_code:
                          type: string
                          required: true
                        street_address:
                          type: string
                          required: true
                      required: true
                    id:
                      type: string
                      required: true
                    title:
                      type: string
                      enum:
                        - mr
                        - mrs
                        - ms
                        - dr
                      required: false
                    given_name:
                      type: string
                      required: true
                    family_name:
                      type: string
                      required: true
                    gender:
                      type: string
                      enum:
                        - female
                        - male
                      required: true
                    vat_id:
                      type: string
                      required: false
                    birth_date:
                      type: date-only
                      required: true
                    death_date:
                      type: date-only
                      required: false
    patch:
      responses:
        "200":
          body:
            application/json:
              additionalProperties: true
              properties:
                lei:
                  type: string
                  required: false
                tax_id:
                  type: string
                  required: false
                email:
                  type: string
                  required: false
                title:
                  type: string
                  enum:
                    - mr
                    - mrs
                    - ms
                    - dr
                  required: false
                name:
                  type: string
                  required: false
                family_name:
                  type: string
                  required: false
                gender:
                  type: string
                  enum:
                    - female
                    - male
                  required: false
                vat_id:
                  type: string
                  required: false
                birth_date:
                  type: date-only
                  required: false
                death_date:
                  type: date-only
                  required: false
                address_country:
                  type: string
                  required: false
                address_locality:
                  type: string
                  required: false
                address_region:
                  type: string
                  required: false
                postal_code:
                  type: string
                  required: false
                street_address:
                  type: string
                  required: false
    delete: {}
    /accounts:
      get:
        queryParameters:
          offset?:
            type: integer
            default: 10
            minimum: 0
            description: The `offset` parameter specifies the first entry to return from a collection.
          sort?:
            type: string
            example: name,-age
          limit?:
            type: integer
            default: 50
            minimum: 1
            description: The `limit` parameter restricts the number of entries returned.
          page?:
            type: integer
            default: 1
            minimum: 1
            description: The `page` parameter specifies the page of results to return.
        responses:
          "200":
            body:
              application/json:
                type: array
                items:
                  additionalProperties: true
                  properties:
                    id:
                      type: string
                      required: true
                    account_number:
                      type: string
                      required: true
                    accountType:
                      type: string
                      enum:
                        - standard
                        - saver
                      required: true
                    amount:
                      additionalProperties: true
                      properties:
                        value:
                          type: number
                          required: true
                        currency:
                          type: string
                          required: true
                      required: true
                    lei:
                      type: string
                      required: true
                    fees_and_comissions:
                      type: string
                      required: true
                    review_state:
                      type: string
                      enum:
                        - requested
                        - cancelled
                        - opened
                        - closed
                      required: true
                    interest_rate:
                      type: number
                      required: true
                    annual_interest_rate:
                      type: number
                      required: true
                    minimum_inflow:
                      additionalProperties: true
                      properties:
                        value:
                          type: number
                          required: true
                        currency:
                          type: string
                          required: true
                      required: true
                    overdraft_limit:
                      additionalProperties: true
                      properties:
                        value:
                          type: number
                          required: true
                        currency:
                          type: string
                          required: true
                      required: true
      post:
        body:
          application/json:
            additionalProperties: true
            properties:
              accountType:
                type: string
                enum:
                  - standard
                  - saver
                required: true
      /{account_id}:
        uriParameters:
          account_id:
            type: string
        get:
          responses:
            "200":
              body:
                application/json:
                  additionalProperties: true
                  properties:
                    id:
                      type: string
                      required: true
                    account_number:
                      type: string
                      required: true
                    accountType:
                      type: string
                      enum:
                        - standard
                        - saver
                      required: true
                    amount:
                      additionalProperties: true
                      properties:
                        value:
                          type: number
                          required: true
                        currency:
                          type: string
                          required: true
                      required: true
                    lei:
                      type: string
                      required: true
                    fees_and_comissions:
                      type: string
                      required: true
                    review_state:
                      type: string
                      enum:
                        - requested
                        - cancelled
                        - opened
                        - closed
                      required: true
                    interest_rate:
                      type: number
                      required: true
                    annual_interest_rate:
                      type: number
                      required: true
                    minimum_inflow:
                      additionalProperties: true
                      properties:
                        value:
                          type: number
                          required: true
                        currency:
                          type: string
                          required: true
                      required: true
                    overdraft_limit:
                      additionalProperties: true
                      properties:
                        value:
                          type: number
                          required: true
                        currency:
                          type: string
                          required: true
                      required: true
        delete: {}
    /loans:
      get:
        queryParameters:
          offset?:
            type: integer
            default: 10
            minimum: 0
            description: The `offset` parameter specifies the first entry to return from a collection.
          sort?:
            type: string
            example: name,-age
          limit?:
            type: integer
            default: 50
            minimum: 1
            description: The `limit` parameter restricts the number of entries returned.
          page?:
            type: integer
            default: 1
            minimum: 1
            description: The `page` parameter specifies the page of results to return.
        responses:
          "200":
            body:
              application/json:
                type: array
                items:
                  additionalProperties: true
                  properties:
                    id:
                      type: string
                      required: true
                    account_number:
                      type: string
                      required: true
                    accountType:
                      type: string
                      enum:
                        - standard
                        - saver
                      required: true
                    amount:
                      additionalProperties: true
                      properties:
                        value:
                          type: number
                          required: true
                        currency:
                          type: string
                          required: true
                      required: true
                    lei:
                      type: string
                      required: true
                    fees_and_comissions:
                      type: string
                      required: true
                    review_state:
                      type: string
                      enum:
                        - requested
                        - cancelled
                        - underwriting
                        - accepted
                        - opened
                        - failed
                        - closed
                      required: true
                    interest_rate:
                      type: number
                      required: true
                    annual_interest_rate:
                      type: number
                      required: true
                    minimum_inflow:
                      additionalProperties: true
                      properties:
                        value:
                          type: number
                          required: true
                        currency:
                          type: string
                          required: true
                      required: true
                    overdraft_limit:
                      additionalProperties: true
                      properties:
                        value:
                          type: number
                          required: true
                        currency:
                          type: string
                          required: true
                      required: true
                    grace_period:
                      additionalProperties: true
                      properties:
                        value:
                          type: string
                          required: true
                      required: true
      post:
        body:
          application/json:
            additionalProperties: true
            properties:
              category:
                type: string
                required: true
              amount:
                additionalProperties: true
                properties:
                  value:
                    type: number
                    required: true
                  currency:
                    type: string
                    required: true
                required: true
              term:
                additionalProperties: true
                properties:
                  value:
                    type: string
                    required: true
                required: true
              interest_rate:
                type: number
                required: true
              down_payment:
                additionalProperties: true
                properties:
                  value:
                    type: number
                    required: true
                  currency:
                    type: string
                    required: true
                required: true
              payment_amount:
                additionalProperties: true
                properties:
                  value:
                    type: number
                    required: true
                  currency:
                    type: string
                    required: true
                required: true
              payment_frequency:
                type: number
                required: true
              review_state:
                type: string
                enum:
                  - requested
                  - underwriting
                  - rejected
                  - accepted
                  - repaying
                  - failed
                  - closed
                required: true
