#%RAML 1.0
title: My API With Types
types:
  Cat:
    type: object
    properties:
      full-schema:
        type: !include external-1.json
      relative-pointer:
        type: !include external-2.json#/definitions/Cat
      xml-schema:
        type: !include external-3.xsd
