#%RAML 1.0
types:
  StringType:
    type: string
  AnyType:
    type: any
  IntegerType:
    type: number
    format: int32
  DateTimeOnlyType:
    type: datetime-only
  TimeOnlyType:
    type: string
    (amf-format): time
  UnionType:
    anyOf:
      -
        type: string
      -
        type: number
        format: int32
  FileType:
    type: file
    maxLength: 307200
    fileTypes:
      - image/jpeg
      - image/png
  BinaryType:
    type: string
    (amf-format): binary
  DateTimeType:
    type: datetime
  DateOnlyType:
    type: date-only
  BooleanType:
    type: boolean
  ObjectType:
    type: object
  ByteType:
    type: string
    (amf-format): byte
  NumberType:
    type: number
    format: float
  NilType:
    type: nil
  PasswordType:
    type: string
    (amf-format): password
title: test title
version: "1.0"
