#%RAML 0.8
---
title: Headers Test
version: v2
baseUri: https://app.zencoder.com/api/{version}/{year}

baseUriParameters:
  version:
    description: some description
    type: string

/required:
  post:
    headers:
      Zencoder-Api-Key:
        displayName: ZEncoder API Key
        required: true