#%RAML 1.0
title: test description field in example
types:
  Person:
    properties:
      name:
        type: string
      description:
        type: string
    example:
      name: juan roman
      description: el ultimo gran 10