#%RAML 1.0
title: Example
mediaType: application/json
types:
  Some: [Person, Address, UndefinedType]
  Person:
    properties:
      name: string
      age: integer
      address: Address
  Address:
        properties:
          street: string
          number: integer
/person-response:
  get:
    responses:
      200:
        body: Person
/address-response:
  get:
    responses:
      200:
        body: Address