#%RAML 1.0
title: test title
description: test description
version: "1.1"
/pets/{id}:
  post:
    responses:
      "200":
        description: ok
        body:
          type: object
          (amf-additionalProperties):
            type: string
          properties:
            builtin:
              type: number
              required: false
            /^S_/:
              type: string
              required: false
            /^I_/:
              type: integer
              required: false
