#%RAML 1.0
title: API
/levelzero:
  displayName: Name
/levelzero/level-one:
  displayName: One display name
  description: and this description!
  get:
    displayName: Some title
    queryParameters:
      param1:
        description: Some descr
        required: true
        type: string
    headers:
      param2:
        description: pisado
        required: false
        type: string
  (amf-parameters):
    -
      name: param1
      description: Some descr
      required: true
      in: query
      type: string
    -
      name: param2
      description: Some descr
      required: true
      in: header
      type: string
    -
      name: param2Endpoint
      required: false
      in: header
      type: string
