#%RAML 1.0
title: API
baseUri: /some/uri
version: "1.0"
/levelzero/level-one:
  displayName: One display name
  description: and this description!
  get:
    displayName: Some title
    responses:
      "200":
        description: 200 descr
        headers:
          Time-Ago:
            type: integer
      "404":
        description: Not found!
  (amf-payloads):
    type: string
