#%RAML 1.0
title: test title
description: test description
protocols: HTTP
baseUri: api.example.com/path

types:
  AppPerson: !include cycle/raml10/simple_example_type/app-person.raml

/people:
  displayName: People
  post:
    displayName: Create a person
    body:
      application/json:
        type: AppPerson