#%RAML 1.0
title: asd

annotationTypes:
  amazon-apigateway-integration:
    type:  amazon-apigateway-integration

types:
  amazon-apigateway-integration:
    type: number

(amazon-apigateway-integration): 1