#%Dialect 1.0

external:
  schema-org: http://schema.org/
  anypoint: http://mulesoft.org/vocab/anpoint#

dialect: Exchange Asset
version: "1.0"

nodeMappings:

  AssetObject:
    classTerm: anypoint.Asset
    mapping:
      date:
        propertyTerm: schema-org.created
        range: string
        mandatory: true
      owner:
        propertyTerm: schema-org.author
        range: string
        mandatory: true
      typeOfAsset:
        propertyTerm: anypoint.assetType
        range: string
      metadata:
        propertyTerm: anypoint.meta
        range: uri

documents:
  root:
    encodes: AssetObject