#%Container Configuration 0.2
pageSize: 10
pattern:
  template: $container/anyId/$uuid
mapping:
  -
    property: http://schema.org/name
    variable: name
  -
    property: http://schema.org/description
    variable: description
  -
    property: http://www.w3.org/ns/shacl#name
    variable: propertyName
schema: http://aml.og/schema/xyz
namespace: api_specs
