#%Container Configuration 0.2
mapping:
  -
    variable: date
    property: http://schema.org/date
namespace: assets
pattern:
  template: $container/anyId/$uuid
schema: http://aml.og/schema/xyz
pageSize: 10
links:
  -
    description: Linked asset metadata
    linkClass: http://mulesoft.org/vocab/anpoint#Asset
    linkProperty: http://mulesoft.org/vocab/anpoint#meta
    linkRange: http://mulesoft.org/vocab/anpoint#WebAPI
