#%RAML 1.0
title: New API
version: v1
securitySchemes:
  oauth_2_0:
    description: |
      Dropbox supports OAuth 2.0 for authenticating all API requests.
    type: OAuth 2.0
    describedBy:
      headers:
        Authorization?:
          description: |
            Used to send a valid OAuth 2 access token. Do not use
            with the "access_token" query string parameter.
          type: string
      queryParameters:
        access_token?:
          description: |
            Used to send a valid OAuth 2 access token. Do not use with
            the "Authorization" header.
          type: string
/test:
  post:
    queryParameters:
      limit?:
        type: integer
        default: someValue
resourceTypes:
  Resource:
    get:
      queryParameters:
        b:
          type: number
        a:
          type: boolean
        c:
          type: string
/resource:
  type: Resource
  get:
    queryParameters:
      a?:
        example: false
        type: string
      b?:
        example: 111
        type: string
      c?:
        example: stringValue
        type: string
    responses:
      "200":
        body:
          application/json:
traits:
  SomeTrait:
    queryParameters:
      <<propertyName1>>:
        type: number
      <<propertyName2>>:
        type: boolean
      <<propertyName3>>:
        type: string
/resource2:
  get:
    is:
      -
        SomeTrait:
          propertyName1: a
          propertyName2: b
          propertyName3: c
    queryParameters:
      a?:
        example: 11
        type: string
      b?:
        example: true
        type: string
      c?:
        example: stringValue
        type: string
    responses:
      "200":
        body:
          application/json:
