#%RAML 0.8
baseUri: https://mocksvc.mulesoft.com/mocks/966091c9-40d0-4454-84e3-fd70e0194ecf
title: American Flights API
version: 1.0

/flights:
 get:
    queryParameters:
      code:
    responses:
      200:
        body:
          application/json: