#%RAML 0.8

title: Example API
/resource:
  /{resourceId}:
    post:
      body:
        application/x-www-form-urlencoded:
          formParameters:
            name:
              -
                type: string
                description: The name of the resource to create
                example: Comment
              -
                type: string
                description: The name 1 of the resource to create
                example: Comment1
            description:
              type: string
              description: A description of the resource to create
              example: User-generated content pertinent to the associated blog post