#%RAML 0.8
title: Filesystem API
version: "0.1"
schemas:
  Invoice: |
    <?xml version="1.0" encoding="UTF-8" ?>
    <xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
        <xs:element name="invoice">
            <xs:complexType>
                <xs:sequence>
                    <xs:element name="accountID" type="xs:string"/>
                    <xs:element name="amount" type="xs:string"/>
                </xs:sequence>
            </xs:complexType>
        </xs:element>
    </xs:schema>
/files:
  get:
    responses:
      "200":
        body:
          application/xml: Invoice
