#%RAML 0.8
resourceTypes:
  collection:
    get:
      is:
        - paged
    post: null
  member:
    get: null
    delete: null
    patch: null
traits:
  chargeable:
    headers:
      dept_code: null
  paged:
    queryParameters:
      start:
        type: number
title: Example API
version: v1
