#%RAML 0.8
title: Example API
/resource:
  /{resourceId}:
    post:
      body:
        application/json:
          type: string
      responses:
        "200":
          body:
            application/yaml:
              type: string
    uriParameters:
      resourceId:
        type: string
