#%RAML 1.0
title: GitHub API
baseUri: api.github.com/
version: v3
protocols:
  - https
/users/{userid}/gists:
  get:
    description: List the authenticated user’s gists or if called anonymously, this will return all public gists.
  uriParameters:
    userid?:
      type: string
