#%RAML 1.0
title: New API
/test:
  post:
    queryParameters:
      limit?:
        items:
          default: someValue
          type: integer
      nonRepeatable?:
        type: string
      common?:
        type: string
