#%RAML 1.0
title: test title
description: test description
mediaType: application/yaml
version: "1.1"
(amf-termsOfService): terms of service
protocols:
  - http
  - https
baseUri: api.example.com/path
