#%RAML 1.0
types:
  Person:
    properties:
      name: string
      age: integer
      address: Address
      parent: (Person | UndefinedType)[]
  Address:
        properties:
          street: string
          number: integer
/person-response:
  get:
    responses:
      200:
        body: Person
/address-response:
  get:
    responses:
      200:
        body: Address