#%RAML 1.0
version: refactor
title: experience
/customers:
  delete:
    responses:
      200: {}
  put:
    responses:
      200: {}
  get:
    responses:
      200:
        body:
          application/json:
            additionalProperties: true
            properties:
              firstName:
                type: string
                required: true
              lastName:
                type: string
                required: true
  description: |
    an individual customer within the collection
    of customerss
