#%RAML 1.0 Overlay
title: Pet Shop Overlay
extends: file://amf-client/shared/src/test/resources/org/raml/parser/overlays/trait-annotation/api.raml
annotationTypes:
  Test3:
    properties:
      name:
        type: string
traits:
  FilterableByPrice:
    (Test3):
      name: Blah
