#%RAML 1.0
title: test

types:
  test1: |
     {
       "type": "object",
       "properties": {
          "builtin": { "type": "number" }
       },
       "patternProperties": {
         "^S_": { "type": "string" },
         "^I_": { "type": "integer" }
       },
       "additionalProperties": {
         "type": "string"
       }
     }

/ep1:
  get:
    responses:
      200:
        body:
          application/json:
            type: test1
            example:
              a: true
              b: "false"
              builtin: 1
              S_0: 1
              S_1: "dos"
              I_2: 3
              I_4: "cuatro"