#%RAML 1.0
title: My API With Types
types:
  Person:
    type: object
    discriminator: kind # refers to the `kind` property of object `Person`
    properties:
      kind: string # contains name of the kind of a `Person` instance
      name: string
  Employee: # kind can equal `Employee`; default value for `discriminatorValue`
    type: Person
    properties:
      employeeId: integer
  User: # kind can equal `User`; default value for `discriminatorValue`
    type: Person
    properties:
      userId: integer
    discriminatorValue: user
  Manager:
    type: Employee
    discriminatorValue: Boss
    properties:
      salary: number

/resource:
  get:
    responses:
      200:
        body:
          application/json:
            type: Person
            examples:
              bad1:
                kind: Empleado
                employeeId: 1
                name: Santiago
              good1:
                kind: Employee
                name: Santiago
                employeeId: 3443
              bad2:
                kind: Employee
                name: Santiago
                employeeId: "ho"
              bad3:
                kind: Manager
                name: Test Boss
                employeeId: 2
                salary: 3
              good2:
                kind: Boss
                name: Test Boss 2
                employeeId: 3
                salary: 4