#%RAML 1.0
title: some title
/some:
  get:
    body:
      application/json:
        type: string
        example:
      application/xml:
        type: string
        examples:
          one:
          two: some
          three: null