#%RAML 1.0 Library

types:

  A:
    type: object
    properties:
      a:
        type: string
      b:
        type: integer
    example:
      a: data
      b: error

  B:
    type: object
    properties:
      a:
        type: string
      b:
        type: integer
    example:
      a: data
      b: 10

  C:
    type: integer
    example: 3

  D:
    type: integer
    example: data

  E:
    type:
      properties:
        f: string
        g: string
    example: |
      {
        "f": "hey",
        "g": "world"
      }

  H:
    type:
      properties:
        f: string
        g: string
    example: |
      {
        "f": "hey",
        "d": "world"
      }

  I:
    type:
      properties:
        f: string
        g: string
    example: |
      <data>
        <f>hey</f>
        <g>world</g>
      </data>
