#%RAML 1.0
title: CountyConnect
version: 1.1.dev
types:
  Bla:
    description: URL-encoded JSON string
    example: '[{"type":"string","comparison":"eq","value":"DAY","field":"groupInterval"},{"type":"date","comparison":"eq","value":"2017-01-16T00:00:00-07:00","field":"lowts"},{"type":"date","comparison":"eq","value":"2017-01-23T23:59:59-07:00","field":"hights"}]'
    type: string