#%RAML 1.0
title: inline type inheritance
version: v1
baseUri: http://api.samplehost.com/{version}
/teams:
  get:
    body:
      application/xml:
        type:
          properties:
            prop1: string
            prop2: number
            prop3: number
            prop4: number
        example:
          prop1: hola
          prop2: true
          prop3: 3.0
          prop4: 3
