#%RAML 1.0
title: Using null type and union

types:
  NullValue:
    type: object
    properties:
      name: string
      age: integer
      valid: boolean
    example:
      name: Fred
      age: 28
      valid: true