#%RAML 1.0

title: Twilio API
version: 2010-04-01
baseUri: https://api.com

types:
  SomeType:
    type: string
    examples:
      invalidInt1: 1
      invalidInt2: +14158675309
      invalidBoolean: true
      invalidNumber: 3.5
      validDate: 2002-12-10
