#%RAML 1.0

title: test

types:
  A: |
    {
      "$schema": "http://json-schema.org/draft-03/schema#",
      "type": "object",
      "properties": {
        "someProp" : {
          "required": true
        },
        "otherProp" : {
          "type": "string",
          "required": true
        }
      },
      "required": true
    }
