#%RAML 1.0
title: test
types:
  jsonSchema: |
    {
      "$schema": "http://json-schema.org/draft-04/schema#",
      "$ref": "#/definitions/root",
      "definitions": {
        "root": {
          "type": "object",
          "additionalProperties": true,
          "required": [
            "age"
          ],
          "properties": {
            "age": {
              "type": "number"
            }
          }
        }
      }
    }
