#%RAML 1.0
title: asd

types:
  TestType1: object
  TestType2: integer
  TestType3: string

/reprints:
  get:
    responses:
      200:
        body:
          application/json:
            type: TestType1 | TestType2 | TestType3