#%RAML 1.0 Vocabulary

usage: Vocabulary to describe the Transports for  the Evented API Structure
version: 0.1
base: http://raml.org/vocabularies/eventedapi#

classTerms:



    description: subject of a channel

propertyTerms:


  eventProducer:
    range: Producer

  eventConsumer:
    range: Consumer


  channelId:
    description: Identifier of a channel
    range: string


  applicationID:
    range: string

  userID:
    range: string

  channel:
    range: Channel

  eventPattern:
    range: string
