#%RAML 1.0
title: response-payload-bug
mediaType: application/json

resourceTypes:
  resType:
    get:
      responses:
        200:
          body:
            application/json:
              properties:
                prop1: string

/test:
  type: resType
  get:
    responses:
      200:
        body:
          example:
            status: OK