#%RAML 1.0
title: Sample API
version: v1
protocols: [HTTPS]
mediaType: application/json

types:
  employeeRequestSchema:
    type: !include schemas/employee-schema.json      
         
/employee:
  post:
    body:
      application/json:
        type: employeeRequestSchema
        example: !include example/employee-inbound-request.json
    responses:
      200 : 
        body:
          application/json:
            example: !include example/employee-response-200.json
      

           
      
      