#%RAML 1.0 Overlay
extends: file://amf-client/shared/src/test/resources/org/raml/parser/overlays/documentation-empty/master.raml
documentation:
  -
    title: overlay1
    content: lorem ipsum dolor
  -
    title: overlay2
    content: lorem ipsum dolor sit
