#%RAML 1.0
title: something

annotationTypes:
  something:
    type: string

/test:
  (other): 44
  get:
    responses:
      (something): blablabla
      200:
        body:
          application/json:
            (something): sarasa
            type: string
