#%RAML 1.0
title: something

annotationTypes:
  something:
    type: string

/test:
  get:
    responses:
      200:
        body:
          application/json:
            (something): sarasa
            type: string
