#%RAML 1.0 NamedExample
value:
  [
    {
      "id": "RG001",
      "description": "Iowa East",
      "zip-codes":
        [
          "52404",
          "52402",
          "52403",
          "52401"
        ]
    },
    {
      "id": "RG002",
      "description": "Iowa Central",
      "zip-codes":
        [
          "50309"
        ]
    },
    {
      "id": "00001",
      "description": "Minnesota Central",
      "zip-codes":
        [
          "55101",
          "55105",
          "55165"
        ]
    }
  ]