#%RAML 1.0
securitySchemes:
  basic:
    type: Basic Authentication
    description: |
      This API supports Basic Authentication.
  custom_auth:
    type: x-custom
    settings:
      custom: Setting
title: Dropbox API
version: "1.0"
securedBy:
  - basic
  - custom_auth
