#%RAML 1.0
title: api
types:
  baseType1:
    properties:
      baseProp1:
        type: string
  baseType2:
    properties:
      baseProp2:
        type: string
  myArray:
    items: baseType1
  myMatrix:
    items:
      items: baseType1
  myNode:
    properties:
      baseType1: baseType1
      baseType2: baseType2
  myUnion:
    type: baseType1 | baseType2
